# -*- coding: utf-8 -*-

words = [
    # Category 1: Finanzgrundlagen & Geld (1-100)
    ("das Bargeld, (nur Sg.)", "Noun", "B1", "наличные деньги", "cash", "Finanzgrundlagen & Geld"),
    ("die Währung, die Währungen", "Noun", "B1", "валюта", "currency", "Finanzgrundlagen & Geld"),
    ("das Einkommen, die Einkommen", "Noun", "B1", "доход (оклад/заработок)", "income", "Finanzgrundlagen & Geld"),
    ("die Ausgabe, die Ausgaben", "Noun", "B1", "расход", "expense", "Finanzgrundlagen & Geld"),
    ("die Einnahme, die Einnahmen", "Noun", "B1", "доход (выручка/поступления)", "revenue / income", "Finanzgrundlagen & Geld"),
    ("das Budget, die Budgets", "Noun", "B1", "бюджет", "budget", "Finanzgrundlagen & Geld"),
    ("das Vermögen, die Vermögen", "Noun", "B2", "имущество / состояние", "wealth / assets", "Finanzgrundlagen & Geld"),
    ("das Kapital, die Kapitale", "Noun", "B2", "капитал", "capital", "Finanzgrundlagen & Geld"),
    ("die Zinsen, (nur Pl.)", "Noun", "B1", "проценты (по кредиту/вкладу)", "interest", "Finanzgrundlagen & Geld"),
    ("die Gebühr, die Gebühren", "Noun", "B1", "пошлина / сбор / плата", "fee / charge", "Finanzgrundlagen & Geld"),
    ("das Guthaben, die Guthaben", "Noun", "B2", "баланс счета / актив", "credit / balance", "Finanzgrundlagen & Geld"),
    ("die Schuld, die Schulden", "Noun", "B1", "долг", "debt", "Finanzgrundlagen & Geld"),
    ("sparen", "Verb", "B1", "сберегать / копить", "to save", "Finanzgrundlagen & Geld"),
    ("ausgeben", "Verb", "B1", "тратить", "to spend", "Finanzgrundlagen & Geld"),
    ("verdienen", "Verb", "B1", "зарабатывать", "to earn", "Finanzgrundlagen & Geld"),
    ("finanzieren", "Verb", "B2", "финансировать", "to finance", "Finanzgrundlagen & Geld"),
    ("verschulden", "Verb", "B2", "задолжать / влезть в долги", "to run into debt", "Finanzgrundlagen & Geld"),
    ("kostenlos", "Adjective", "B1", "бесплатный", "free of charge", "Finanzgrundlagen & Geld"),
    ("teuer", "Adjective", "B1", "дорогой", "expensive", "Finanzgrundlagen & Geld"),
    ("günstig", "Adjective", "B1", "выгодный / недорогой", "favorable / cheap", "Finanzgrundlagen & Geld"),
    ("wertvoll", "Adjective", "B1", "ценный", "valuable", "Finanzgrundlagen & Geld"),
    ("wertlos", "Adjective", "B2", "бесценный / не имеющий ценности", "worthless", "Finanzgrundlagen & Geld"),
    ("die Inflation, die Inflationen", "Noun", "B2", "инфляция", "inflation", "Finanzgrundlagen & Geld"),
    ("die Deflation, die Deflationen", "Noun", "B2", "дефляция", "deflation", "Finanzgrundlagen & Geld"),
    ("der Geldfluss, die Geldflüsse", "Noun", "B2", "денежный поток", "cash flow", "Finanzgrundlagen & Geld"),
    ("das Taschengeld, (nur Sg.)", "Noun", "B1", "карманные деньги", "pocket money", "Finanzgrundlagen & Geld"),
    ("der Wechselkurs, die Wechselkurse", "Noun", "B2", "валютный курс", "exchange rate", "Finanzgrundlagen & Geld"),
    ("wechseln", "Verb", "B1", "менять / обменивать", "to exchange", "Finanzgrundlagen & Geld"),
    ("überweisen", "Verb", "B1", "переводить (деньги)", "to transfer", "Finanzgrundlagen & Geld"),
    ("die Überweisung, die Überweisungen", "Noun", "B1", "денежный перевод", "bank transfer", "Finanzgrundlagen & Geld"),
    ("bar", "Adjective", "B1", "наличный", "cash", "Finanzgrundlagen & Geld"),
    ("bargeldlos", "Adjective", "B2", "безналичный", "cashless", "Finanzgrundlagen & Geld"),
    ("die Kaufkraft, (nur Sg.)", "Noun", "B2", "покупательная способность", "purchasing power", "Finanzgrundlagen & Geld"),
    ("der Betrag, die Beträge", "Noun", "B1", "сумма / величина", "amount / sum", "Finanzgrundlagen & Geld"),
    ("die Summe, die Summen", "Noun", "B1", "сумма", "sum", "Finanzgrundlagen & Geld"),
    ("der Wert, die Werte", "Noun", "B1", "стоимость / ценность", "value", "Finanzgrundlagen & Geld"),
    ("beitragen", "Verb", "B2", "вносить вклад", "to contribute", "Finanzgrundlagen & Geld"),
    ("der Beitrag, die Beiträge", "Noun", "B1", "взнос / вклад", "contribution / fee", "Finanzgrundlagen & Geld"),
    ("kalkulieren", "Verb", "B2", "калькулировать / просчитывать", "to calculate", "Finanzgrundlagen & Geld"),
    ("die Kalkulation, die Kalkulationen", "Noun", "B2", "расчет / калькуляция", "calculation", "Finanzgrundlagen & Geld"),
    ("der Verlust, die Verluste", "Noun", "B1", "убыток / потеря", "loss", "Finanzgrundlagen & Geld"),
    ("verlieren", "Verb", "B1", "терять", "to lose", "Finanzgrundlagen & Geld"),
    ("der Gewinn, die Gewinne", "Noun", "B1", "прибыль / выигрыш", "profit / gain", "Finanzgrundlagen & Geld"),
    ("gewinnen", "Verb", "B1", "получать прибыль / выигрывать", "to win / gain", "Finanzgrundlagen & Geld"),
    ("leihen", "Verb", "B1", "одалживать", "to lend / borrow", "Finanzgrundlagen & Geld"),
    ("das Darlehen, die Darlehen", "Noun", "B2", "ссуда / заем", "loan", "Finanzgrundlagen & Geld"),
    ("die Spende, die Spenden", "Noun", "B1", "пожертвование", "donation", "Finanzgrundlagen & Geld"),
    ("spenden", "Verb", "B1", "жертвовать", "to donate", "Finanzgrundlagen & Geld"),
    ("der Zuschuss, die Zuschüsse", "Noun", "B2", "субсидия / прибавка", "subsidy / grant", "Finanzgrundlagen & Geld"),
    ("bezuschussen", "Verb", "B2", "субсидировать", "to subsidize", "Finanzgrundlagen & Geld"),
    ("der Puffer, die Puffer", "Noun", "B2", "резерв / буфер", "buffer", "Finanzgrundlagen & Geld"),
    ("die Reserve, die Reserven", "Noun", "B2", "резерв", "reserve", "Finanzgrundlagen & Geld"),
    ("reservieren", "Verb", "B1", "резервировать", "to reserve", "Finanzgrundlagen & Geld"),
    ("das Portemonnaie, die Portemonnaies", "Noun", "B1", "кошелек", "wallet", "Finanzgrundlagen & Geld"),
    ("die Geldbörse, die Geldbörsen", "Noun", "B1", "кошелек для монет", "purse", "Finanzgrundlagen & Geld"),
    ("das Gold, (nur Sg.)", "Noun", "B1", "золото", "gold", "Finanzgrundlagen & Geld"),
    ("das Silber, (nur Sg.)", "Noun", "B1", "серебро", "silver", "Finanzgrundlagen & Geld"),
    ("die Münze, die Münzen", "Noun", "B1", "монета", "coin", "Finanzgrundlagen & Geld"),
    ("der Geldschein, die Geldscheine", "Noun", "B1", "банкнота", "banknote", "Finanzgrundlagen & Geld"),
    ("die Note, die Noten", "Noun", "B1", "банкнота / купюра", "note / bill", "Finanzgrundlagen & Geld"),
    ("fälschen", "Verb", "B2", "фальсифицировать / подделывать", "to counterfeit / forge", "Finanzgrundlagen & Geld"),
    ("das Falschgeld, (nur Sg.)", "Noun", "B2", "фальшивые деньги", "counterfeit money", "Finanzgrundlagen & Geld"),
    ("der Wohlstand, (nur Sg.)", "Noun", "B2", "благосостояние / достаток", "prosperity / wealth", "Finanzgrundlagen & Geld"),
    ("die Armut, (nur Sg.)", "Noun", "B1", "бедность", "poverty", "Finanzgrundlagen & Geld"),
    ("reich", "Adjective", "B1", "богатый", "rich", "Finanzgrundlagen & Geld"),
    ("arm", "Adjective", "B1", "бедный", "poor", "Finanzgrundlagen & Geld"),
    ("die Finanzen, (nur Pl.)", "Noun", "B1", "финансы", "finances", "Finanzgrundlagen & Geld"),
    ("finanziell", "Adjective", "B1", "финансовый", "financial", "Finanzgrundlagen & Geld"),
    ("der Finanzmarkt, die Finanzmärkte", "Noun", "B2", "финансовый рынок", "financial market", "Finanzgrundlagen & Geld"),
    ("flüssig", "Adjective", "B2", "ликвидный", "liquid", "Finanzgrundlagen & Geld"),
    ("das Liquiditätsrisiko, die Risiken", "Noun", "B2", "риск ликвидности", "liquidity risk", "Finanzgrundlagen & Geld"),
    ("die Zahlungsunfähigkeit, (nur Sg.)", "Noun", "B2", "неплатежеспособность", "insolvency", "Finanzgrundlagen & Geld"),
    ("zahlungsunfähig", "Adjective", "B2", "неплатежеспособный", "insolvent", "Finanzgrundlagen & Geld"),
    ("die Insolvenz, die Insolvenzen", "Noun", "B2", "банкротство", "bankruptcy", "Finanzgrundlagen & Geld"),
    ("angemessen", "Adjective", "B2", "соответствующий / умеренный", "appropriate / reasonable", "Finanzgrundlagen & Geld"),
    ("übertreiben", "Verb", "B2", "преувеличивать (расходы)", "to exaggerate / overdo", "Finanzgrundlagen & Geld"),
    ("die Verschwendung, die Verschwendugen", "Noun", "B2", "расточительство", "waste / extravagance", "Finanzgrundlagen & Geld"),
    ("verschwenden", "Verb", "B2", "расточать / тратить впустую", "to waste", "Finanzgrundlagen & Geld"),
    ("sparsam", "Adjective", "B1", "экономный", "thrifty / economical", "Finanzgrundlagen & Geld"),
    ("die Sparsamkeit, (nur Sg.)", "Noun", "B2", "бережливость", "thrift / economy", "Finanzgrundlagen & Geld"),
    ("großzügig", "Adjective", "B1", "щедрый", "generous", "Finanzgrundlagen & Geld"),
    ("geizig", "Adjective", "B2", "скупой / жадный", "stingy / mean", "Finanzgrundlagen & Geld"),
    ("der Geiz, (nur Sg.)", "Noun", "B2", "скупость", "stinginess", "Finanzgrundlagen & Geld"),
    ("das Entgelt, die Entgelte", "Noun", "B2", "плата / вознаграждение", "remuneration / fee", "Finanzgrundlagen & Geld"),
    ("entgeltlich", "Adjective", "B2", "возмездный / платный", "for a fee", "Finanzgrundlagen & Geld"),
    ("unentgeltlich", "Adjective", "B2", "безвозмездный / бесплатный", "free of charge", "Finanzgrundlagen & Geld"),
    ("das Honorar, die Honorare", "Noun", "B2", "гонорар / вознаграждение", "fee / honorarium", "Finanzgrundlagen & Geld"),
    ("der Lohn, die Löhne", "Noun", "B1", "заработная плата (сдельная)", "wage", "Finanzgrundlagen & Geld"),
    ("das Gehalt, die Gehälter", "Noun", "B1", "оклад / зарплата (служащего)", "salary", "Finanzgrundlagen & Geld"),
    ("das Netto, (nur Sg.)", "Noun", "B1", "нетто (чистый доход/вес)", "net", "Finanzgrundlagen & Geld"),
    ("das Brutto, (nur Sg.)", "Noun", "B1", "брутто (грязный доход/вес)", "gross", "Finanzgrundlagen & Geld"),
    ("die Abgabe, die Abgaben", "Noun", "B2", "налог / пошлина / сбор", "tax / levy", "Finanzgrundlagen & Geld"),
    ("die Finanzierungquelle, die Quellen", "Noun", "B2", "источник финансирования", "funding source", "Finanzgrundlagen & Geld"),
    ("die Subvention, die Subventionen", "Noun", "B2", "субсидия", "subsidy", "Finanzgrundlagen & Geld"),
    ("subventionieren", "Verb", "B2", "субсидировать", "to subsidize", "Finanzgrundlagen & Geld"),
    ("die Kasse, die Kassen", "Noun", "B1", "касса / кассовый аппарат", "cash register / cash desk", "Finanzgrundlagen & Geld"),
    ("der Kassierer, die Kassierer", "Noun", "B1", "кассир", "cashier", "Finanzgrundlagen & Geld"),
    ("kassieren", "Verb", "B1", "принимать оплату", "to collect cash", "Finanzgrundlagen & Geld"),
    ("das Wechselgeld, (nur Sg.)", "Noun", "B1", "сдача", "change", "Finanzgrundlagen & Geld"),
    ("der Quittungsbeleg, die Belege", "Noun", "B2", "чек / квитанция", "receipt / slip", "Finanzgrundlagen & Geld"),

    # Category 2: Buchhaltung & Bilanz (101-200)
    ("die Buchhaltung, die Buchhaltungen", "Noun", "B2", "бухгалтерия / бухучет", "accounting / bookkeeping", "Buchhaltung & Bilanz"),
    ("die Buchführung, (nur Sg.)", "Noun", "B2", "ведение бухучета", "bookkeeping", "Buchhaltung & Bilanz"),
    ("der Buchhalter, die Buchhalter", "Noun", "B2", "бухгалтер", "accountant / bookkeeper", "Buchhaltung & Bilanz"),
    ("buchen", "Verb", "B1", "проводить по бухгалтерии / бронировать", "to post / book", "Buchhaltung & Bilanz"),
    ("die Buchung, die Buchungen", "Noun", "B2", "бухгалтерская проводка / бронь", "entry / booking", "Buchhaltung & Bilanz"),
    ("das Soll, (nur Sg.)", "Noun", "B2", "дебет", "debit", "Buchhaltung & Bilanz"),
    ("das Haben, (nur Sg.)", "Noun", "B2", "кредит (бухгалтерский)", "credit", "Buchhaltung & Bilanz"),
    ("die Bilanz, die Bilanzen", "Noun", "B2", "баланс", "balance sheet", "Buchhaltung & Bilanz"),
    ("bilanzieren", "Verb", "B2", "составлять баланс", "to balance / draw up balance", "Buchhaltung & Bilanz"),
    ("der Jahresabschluss, die Abschlüsse", "Noun", "B2", "годовой финансовый отчет", "annual financial statements", "Buchhaltung & Bilanz"),
    ("die Abschreibung, die Abschreibungen", "Noun", "B2", "амортизация / списание", "depreciation / amortization", "Buchhaltung & Bilanz"),
    ("abschreiben", "Verb", "B2", "амортизировать / списывать", "to write off / depreciate", "Buchhaltung & Bilanz"),
    ("das Wirtschaftjahr, die Wirtschaftjahre", "Noun", "B2", "отчетный / финансовый год", "fiscal year / financial year", "Buchhaltung & Bilanz"),
    ("das Geschäftsjahr, die Geschäftsjahre", "Noun", "B2", "финансовый год", "fiscal year", "Buchhaltung & Bilanz"),
    ("der Prüfer, die Prüfer", "Noun", "B2", "аудитор / ревизор", "auditor / examiner", "Buchhaltung & Bilanz"),
    ("prüfen", "Verb", "B1", "проверять / аудировать", "to audit / check", "Buchhaltung & Bilanz"),
    ("die Wirtschaftprüfung, die Prüfungen", "Noun", "B2", "аудит предприятия", "auditing", "Buchhaltung & Bilanz"),
    ("die Inventur, die Inventuren", "Noun", "B2", "инвентаризация", "inventory / stocktaking", "Buchhaltung & Bilanz"),
    ("das Inventar, die Inventare", "Noun", "B2", "опись имущества / инвентарь", "inventory / assets list", "Buchhaltung & Bilanz"),
    ("der Bestand, die Bestände", "Noun", "B2", "запас / остаток на складе", "stock / inventory", "Buchhaltung & Bilanz"),
    ("das Anlagevermögen, (nur Sg.)", "Noun", "B2", "основные средства / внеоборотные активы", "fixed assets", "Buchhaltung & Bilanz"),
    ("das Umlaufvermögen, (nur Sg.)", "Noun", "B2", "оборотные средства / активы", "current assets", "Buchhaltung & Bilanz"),
    ("das Eigenkapital, (nur Sg.)", "Noun", "B2", "собственный капитал", "equity / own capital", "Buchhaltung & Bilanz"),
    ("das Fremdkapital, (nur Sg.)", "Noun", "B2", "заемный капитал", "debt capital / liabilities", "Buchhaltung & Bilanz"),
    ("die Verbindlichkeit, die Verbindlichkeiten", "Noun", "B2", "обязательство / задолженность", "liabilities / obligations", "Buchhaltung & Bilanz"),
    ("die Forderung, die Forderungen", "Noun", "B2", "дебиторская задолженность / требование", "receivables / claims", "Buchhaltung & Bilanz"),
    ("die Rückstellung, die Rückstellungen", "Noun", "B2", "резерв предстоящих расходов", "provision / accrual", "Buchhaltung & Bilanz"),
    ("die Rechnung, die Rechnungen", "Noun", "B1", "счет / инвойс", "invoice / bill", "Buchhaltung & Bilanz"),
    ("der Beleg, die Belege", "Noun", "B2", "подтверждающий документ / квитанция", "voucher / document", "Buchhaltung & Bilanz"),
    ("belegen", "Verb", "B2", "подтверждать документально", "to prove / verify", "Buchhaltung & Bilanz"),
    ("nachweisen", "Verb", "B1", "доказывать / подтверждать", "to prove / document", "Buchhaltung & Bilanz"),
    ("der Nachweis, die Nachweise", "Noun", "B1", "подтверждение / свидетельство", "proof / verification", "Buchhaltung & Bilanz"),
    ("die Quittung, die Quittungen", "Noun", "B1", "квитанция / расписка", "receipt", "Buchhaltung & Bilanz"),
    ("quittieren", "Verb", "B2", "подписывать квитанцию / подтверждать", "to receipt", "Buchhaltung & Bilanz"),
    ("der Posten, die Posten", "Noun", "B2", "статья баланса / позиция счета", "item / entry", "Buchhaltung & Bilanz"),
    ("die Buchungsperiode, die Perioden", "Noun", "B2", "период проводки / отчетный период", "accounting period", "Buchhaltung & Bilanz"),
    ("stornieren", "Verb", "B2", "сторнировать / аннулировать проводку", "to reverse / cancel", "Buchhaltung & Bilanz"),
    ("die Stornierung, die Stornierungen", "Noun", "B2", "сторнирование / отмена", "cancellation / reversal", "Buchhaltung & Bilanz"),
    ("der Kontenrahmen, die Kontenrahmen", "Noun", "B2", "план счетов", "chart of accounts", "Buchhaltung & Bilanz"),
    ("das Hauptbuch, die Hauptbücher", "Noun", "B2", "главная книга", "general ledger", "Buchhaltung & Bilanz"),
    ("das Journal, die Journale", "Noun", "B2", "журнал учета проводок", "journal", "Buchhaltung & Bilanz"),
    ("die Kostenstelle, die Kostenstellen", "Noun", "B2", "центр затрат", "cost center", "Buchhaltung & Bilanz"),
    ("der Kostenträger, die Kostenträger", "Noun", "B2", "носитель затрат", "cost unit", "Buchhaltung & Bilanz"),
    ("die Kostenrechnung, die Kostenrechnungen", "Noun", "B2", "расчет издержек / учет затрат", "cost accounting", "Buchhaltung & Bilanz"),
    ("der Rechnungsprüfer, die Prüfer", "Noun", "B2", "аудитор счетов / ревизор", "auditor", "Buchhaltung & Bilanz"),
    ("die Rechnungslegung, die Legungen", "Noun", "B2", "финансовая отчетность", "financial reporting", "Buchhaltung & Bilanz"),
    ("der Standard, die Standards", "Noun", "B1", "стандарт", "standard", "Buchhaltung & Bilanz"),
    ("konform", "Adjective", "B2", "соответствующий / конформный", "compliant / aligned", "Buchhaltung & Bilanz"),
    ("die Einhaltung, (nur Sg.)", "Noun", "B2", "соблюдение (правил)", "compliance", "Buchhaltung & Bilanz"),
    ("einhalten", "Verb", "B1", "соблюдать", "to comply with / keep", "Buchhaltung & Bilanz"),
    ("die Richtlinie, die Richtlinien", "Noun", "B2", "руководство / директива / правило", "guideline / directive", "Buchhaltung & Bilanz"),
    ("der Grundsatz, die Grundsätze", "Noun", "B2", "принцип / основа", "principle / policy", "Buchhaltung & Bilanz"),
    ("die Bewertung, die Bewertungen", "Noun", "B2", "оценка стоимости", "valuation / appraisal", "Buchhaltung & Bilanz"),
    ("bewerten", "Verb", "B2", "оценивать", "to value / assess", "Buchhaltung & Bilanz"),
    ("der Anschaffungspreis, die Preise", "Noun", "B2", "первоначальная стоимость / цена покупки", "purchase price", "Buchhaltung & Bilanz"),
    ("die Anschaffungskosten, (nur Pl.)", "Noun", "B2", "затраты на приобретение", "acquisition costs", "Buchhaltung & Bilanz"),
    ("der Buchwert, die Buchwerte", "Noun", "B2", "балансовая стоимость", "book value", "Buchhaltung & Bilanz"),
    ("der Marktwert, die Marktwerte", "Noun", "B2", "рыночная стоимость", "market value", "Buchhaltung & Bilanz"),
    ("der Zeitwert, die Zeitwerte", "Noun", "B2", "текущая / временная стоимость", "fair value / present value", "Buchhaltung & Bilanz"),
    ("der Restwert, die Restwerte", "Noun", "B2", "остаточная стоимость", "residual value", "Buchhaltung & Bilanz"),
    ("die Wertminderung, die Minderungen", "Noun", "B2", "обесценение / снижение стоимости", "impairment / depreciation", "Buchhaltung & Bilanz"),
    ("wertmindern", "Verb", "B2", "обесценивать / снижать стоимость", "to impair / depreciate", "Buchhaltung & Bilanz"),
    ("die Aufwertung, die Aufwertungen", "Noun", "B2", "переоценка в сторону увеличения", "revaluation / appreciation", "Buchhaltung & Bilanz"),
    ("aufwerten", "Verb", "B2", "переоценивать / повышать стоимость", "to appreciate / revalue", "Buchhaltung & Bilanz"),
    ("die Gewinn- und Verlustrechnung, (GuV)", "Noun", "B2", "отчет о прибылях и убытках", "income statement / P&L", "Buchhaltung & Bilanz"),
    ("der Postenbericht, die Berichte", "Noun", "B2", "отчет по позициям", "item report", "Buchhaltung & Bilanz"),
    ("der Saldo, die Salden", "Noun", "B2", "сальдо / остаток", "balance / margin", "Buchhaltung & Bilanz"),
    ("saldieren", "Verb", "B2", "выводить сальдо / подводить итог", "to balance / offset", "Buchhaltung & Bilanz"),
    ("die Saldenbilanz, die Bilanzen", "Noun", "B2", "оборотная ведомость / пробный баланс", "trial balance", "Buchhaltung & Bilanz"),
    ("der Kontostand, die Stände", "Noun", "B1", "баланс счета", "account balance", "Buchhaltung & Bilanz"),
    ("ausgleichen", "Verb", "B2", "компенсировать / выравнивать", "to balance / compensate", "Buchhaltung & Bilanz"),
    ("der Ausgleich, die Ausgleiche", "Noun", "B2", "выравнивание / компенсация", "settlement / compensation", "Buchhaltung & Bilanz"),
    ("die Buchungszeile, die Zeilen", "Noun", "B2", "строка проводки", "posting line", "Buchhaltung & Bilanz"),
    ("die Gegenbuchung, die Gegenbuchungen", "Noun", "B2", "обратная проводка", "counter-entry", "Buchhaltung & Bilanz"),
    ("die Erfassung, die Erfassungen", "Noun", "B2", "учет / регистрация данных", "recording / entry", "Buchhaltung & Bilanz"),
    ("erfassen", "Verb", "B2", "учитывать / вносить в базу данных", "to record / enter", "Buchhaltung & Bilanz"),
    ("manuell", "Adjective", "B1", "ручной (ввод)", "manual", "Buchhaltung & Bilanz"),
    ("automatisch", "Adjective", "B1", "автоматический", "automatic", "Buchhaltung & Bilanz"),
    ("die Automatisierung, die Automatisierungen", "Noun", "B2", "автоматизация", "automation", "Buchhaltung & Bilanz"),
    ("digitalisieren", "Verb", "B2", "оцифровывать", "to digitalize", "Buchhaltung & Bilanz"),
    ("das ERP-System, die Systeme", "Noun", "B2", "ERP-система", "ERP system", "Buchhaltung & Bilanz"),
    ("die Software, die Softwares", "Noun", "B1", "программное обеспечение", "software", "Buchhaltung & Bilanz"),
    ("der Datenimport, die Importe", "Noun", "B2", "импорт данных", "data import", "Buchhaltung & Bilanz"),
    ("der Datenexport, die Exporte", "Noun", "B2", "экспорт данных", "data export", "Buchhaltung & Bilanz"),
    ("die Schnittstelle, die Schnittstellen", "Noun", "B2", "интерфейс / интеграция / стык", "interface", "Buchhaltung & Bilanz"),
    ("fehlerhaft", "Adjective", "B2", "ошибочный / содержащий ошибки", "faulty / incorrect", "Buchhaltung & Bilanz"),
    ("korrigieren", "Verb", "B1", "исправлять", "to correct", "Buchhaltung & Bilanz"),
    ("die Korrektur, die Korrekturen", "Noun", "B1", "исправление / корректировка", "correction", "Buchhaltung & Bilanz"),
    ("die Differenz, die Differenzen", "Noun", "B2", "разница / расхождение", "difference / discrepancy", "Buchhaltung & Bilanz"),
    ("die Abweichung, die Abweichungen", "Noun", "B2", "отклонение", "deviation / variance", "Buchhaltung & Bilanz"),
    ("abweichen", "Verb", "B2", "отклоняться", "to deviate / differ", "Buchhaltung & Bilanz"),
    ("konsolidieren", "Verb", "B2", "консолидировать (отчетность)", "to consolidate", "Buchhaltung & Bilanz"),
    ("die Konsolidierung, die Konsolidierungen", "Noun", "B2", "консолидация", "consolidation", "Buchhaltung & Bilanz"),
    ("der Konzern, die Konzerne", "Noun", "B2", "концерн / группа компаний", "corporate group / enterprise", "Buchhaltung & Bilanz"),
    ("die Muttergesellschaft, die Gesellschaften", "Noun", "B2", "материнская компания", "parent company", "Buchhaltung & Bilanz"),
    ("die Tochtergesellschaft, die Gesellschaften", "Noun", "B2", "дочерняя компания", "subsidiary", "Buchhaltung & Bilanz"),
    ("der Abschlussbericht, die Berichte", "Noun", "B2", "итоговый отчет", "final report", "Buchhaltung & Bilanz"),
    ("die Transparenz, (nur Sg.)", "Noun", "B2", "прозрачность", "transparency", "Buchhaltung & Bilanz"),
    ("transparent", "Adjective", "B2", "прозрачный", "transparent", "Buchhaltung & Bilanz"),
    ("die Offenlegung, die Offenlegungen", "Noun", "B2", "раскрытие информации", "disclosure", "Buchhaltung & Bilanz"),

    # Category 3: Banken & Kredite (201-300)
    ("die Bank, die Banken", "Noun", "B1", "банк", "bank", "Banken & Kredite"),
    ("das Konto, die Konten", "Noun", "B1", "счет (банковский)", "account", "Banken & Kredite"),
    ("das Girokonto, die Girokonten", "Noun", "B1", "текущий / расчетный счет", "checking account", "Banken & Kredite"),
    ("das Sparkonto, die Sparkonten", "Noun", "B1", "сберегательный счет", "savings account", "Banken & Kredite"),
    ("eröffnen", "Verb", "B1", "открывать (счет)", "to open", "Banken & Kredite"),
    ("die Kontoeröffnung, die Eröffnungen", "Noun", "B2", "открытие счета", "account opening", "Banken & Kredite"),
    ("schließen", "Verb", "B1", "закрывать", "to close", "Banken & Kredite"),
    ("die Kontoschließung, die Schließungen", "Noun", "B2", "закрытие счета", "account closure", "Banken & Kredite"),
    ("die Kontogebühr, die Gebühren", "Noun", "B2", "комиссия за обслуживание счета", "account fee", "Banken & Kredite"),
    ("der Kontoauszug, die Auszüge", "Noun", "B1", "выписка по счету", "bank statement", "Banken & Kredite"),
    ("abheben", "Verb", "B1", "снимать (деньги с карты)", "to withdraw", "Banken & Kredite"),
    ("einzahlen", "Verb", "B1", "вносить на счет", "to deposit", "Banken & Kredite"),
    ("die Einzahlung, die Einzahlungen", "Noun", "B1", "взнос наличных / депозит", "deposit", "Banken & Kredite"),
    ("die Auszahlung, die Auszahlungen", "Noun", "B1", "выплата наличных", "withdrawal / payout", "Banken & Kredite"),
    ("der Geldautomat, die Automaten", "Noun", "B1", "банкомат", "ATM", "Banken & Kredite"),
    ("die Bankkarte, die Karten", "Noun", "B1", "банковская карта", "bank card", "Banken & Kredite"),
    ("die Kreditkarte, die Karten", "Noun", "B1", "кредитная карта", "credit card", "Banken & Kredite"),
    ("die Geheimzahl, die Geheimzahlen", "Noun", "B1", "ПИН-код", "PIN number", "Banken & Kredite"),
    ("die PIN, die PINs", "Noun", "B1", "ПИН-код", "PIN", "Banken & Kredite"),
    ("sperren", "Verb", "B1", "блокировать (карту)", "to block / freeze", "Banken & Kredite"),
    ("die Kartensperrung, die Sperrungen", "Noun", "B2", "блокировка карты", "card blocking", "Banken & Kredite"),
    ("das Online-Banking, (nur Sg.)", "Noun", "B1", "интернет-банкинг", "online banking", "Banken & Kredite"),
    ("der Dauerauftrag, die Aufträge", "Noun", "B2", "автоплатеж / постоянное поручение", "standing order", "Banken & Kredite"),
    ("die Lastschrift, die Lastschriften", "Noun", "B2", "прямое списание (со счета)", "direct debit", "Banken & Kredite"),
    ("abbuchen", "Verb", "B2", "списывать со счета", "to debit", "Banken & Kredite"),
    ("gutschreiben", "Verb", "B2", "зачислять на счет", "to credit", "Banken & Kredite"),
    ("die Gutschrift, die Gutschriften", "Noun", "B2", "зачисление средств / кредит-нота", "credit note / credit", "Banken & Kredite"),
    ("der Kredit, die Kredite", "Noun", "B1", "кредит", "credit / loan", "Banken & Kredite"),
    ("beantragen", "Verb", "B1", "подавать заявку / ходатайствовать", "to apply for", "Banken & Kredite"),
    ("der Kreditantrag, die Anträge", "Noun", "B2", "заявка на кредит", "loan application", "Banken & Kredite"),
    ("gewähren", "Verb", "B2", "предоставлять / удовлетворять (запрос)", "to grant / approve", "Banken & Kredite"),
    ("bewilligen", "Verb", "B2", "одобрять / утверждать (кредит)", "to approve / grant", "Banken & Kredite"),
    ("die Bewilligung, die Bewilligungen", "Noun", "B2", "одобрение / разрешение", "approval / grant", "Banken & Kredite"),
    ("ablehnen", "Verb", "B1", "отклонять / отказывать", "to reject / decline", "Banken & Kredite"),
    ("die Ablehnung, die Ablehnungen", "Noun", "B2", "отказ", "rejection / refusal", "Banken & Kredite"),
    ("die Kreditwürdigkeit, (nur Sg.)", "Noun", "B2", "кредитоспособность", "creditworthiness", "Banken & Kredite"),
    ("die Bonität, (nur Sg.)", "Noun", "B2", "кредитный рейтинг / платежеспособность", "credit rating / solvency", "Banken & Kredite"),
    ("die Schufa, (nur Sg.)", "Noun", "B2", "ШУФА (кредитная история в ФРГ)", "credit bureau (SCHUFA)", "Banken & Kredite"),
    ("der Zinssatz, die Sätze", "Noun", "B2", "процентная ставка", "interest rate", "Banken & Kredite"),
    ("die Tilgung, die Tilgungen", "Noun", "B2", "погашение / амортизация долга", "repayment / amortization", "Banken & Kredite"),
    ("tilgen", "Verb", "B2", "гасить (долг)", "to repay / amortize", "Banken & Kredite"),
    ("die Rate, die Raten", "Noun", "B1", "взнос (ежемесячный) / ставка", "installment / rate", "Banken & Kredite"),
    ("die Ratenzahlung, die Zahlungen", "Noun", "B1", "рассрочка / оплата частями", "payment by installments", "Banken & Kredite"),
    ("die Laufzeit, die Laufzeiten", "Noun", "B2", "срок действия / срок кредита", "term / duration", "Banken & Kredite"),
    ("die Hypothek, die Hypotheken", "Noun", "B2", "ипотека", "mortgage", "Banken & Kredite"),
    ("die Absicherung, die Absicherungen", "Noun", "B2", "обеспечение / страхование рисков", "collateral / hedging", "Banken & Kredite"),
    ("absichern", "Verb", "B2", "обезопасить / страховать (сделку)", "to hedge / secure", "Banken & Kredite"),
    ("die Bürgschaft, die Bürgschaften", "Noun", "B2", "поручительство / гарантия", "guaranty / suretyship", "Banken & Kredite"),
    ("der Bürge, die Bürgen", "Noun", "B2", "поручитель", "guarantor", "Banken & Kredite"),
    ("bürgen", "Verb", "B2", "ручаться / выступать поручителем", "to guarantee / bail", "Banken & Kredite"),
    ("die Zinsbindung, die Bindungen", "Noun", "B2", "фиксация процентной ставки", "interest rate lock", "Banken & Kredite"),
    ("festverzinslich", "Adjective", "B2", "с фиксированной процентной ставкой", "fixed-interest", "Banken & Kredite"),
    ("variabel", "Adjective", "B2", "переменный / плавающий (курс)", "variable", "Banken & Kredite"),
    ("der Dispokredit, die Kredite", "Noun", "B2", "овердрафт", "overdraft facility", "Banken & Kredite"),
    ("überziehen", "Verb", "B2", "превышать лимит (счета)", "to overdraw", "Banken & Kredite"),
    ("die Überziehung, die Überziehungen", "Noun", "B2", "овердрафт / перерасход средств", "overdraft", "Banken & Kredite"),
    ("der Zinseszins, die Zinseszinsen", "Noun", "B2", "сложные проценты", "compound interest", "Banken & Kredite"),
    ("die Bankfiliale, die Filialen", "Noun", "B1", "отделение банка", "bank branch", "Banken & Kredite"),
    ("der Bankberater, die Berater", "Noun", "B2", "банковский консультант", "bank advisor", "Banken & Kredite"),
    ("beraten", "Verb", "B1", "консультировать", "to advise / consult", "Banken & Kredite"),
    ("die Beratung, die Beratungen", "Noun", "B1", "консультация", "consultation / advice", "Banken & Kredite"),
    ("die Schließfach, die Schließfächer", "Noun", "B2", "банковская ячейка / сейф", "safe deposit box", "Banken & Kredite"),
    ("das Depot, die Depots", "Noun", "B2", "брокерский счет / депо", "custody account / depot", "Banken & Kredite"),
    ("das Wertpapier, die Wertpapiere", "Noun", "B2", "ценная бумага", "security / financial paper", "Banken & Kredite"),
    ("anlegen", "Verb", "B2", "инвестировать / вкладывать", "to invest", "Banken & Kredite"),
    ("die Geldanlage, die Geldanlagen", "Noun", "B2", "инвестиция / вклад денег", "investment", "Banken & Kredite"),
    ("das Festgeld, (nur Sg.)", "Noun", "B2", "срочный вклад", "fixed-term deposit", "Banken & Kredite"),
    ("das Tagesgeld, (nur Sg.)", "Noun", "B2", "депозит до востребования", "call money", "Banken & Kredite"),
    ("der Gläubiger, die Gläubiger", "Noun", "B2", "кредитор", "creditor / lender", "Banken & Kredite"),
    ("der Schuldner, die Schuldner", "Noun", "B2", "должник", "debtor / borrower", "Banken & Kredite"),
    ("die Ratezahlung, die Ratenzahlungen", "Noun", "B1", "оплата в рассрочку", "installment payment", "Banken & Kredite"),
    ("die Kreditlinie, die Kreditlinien", "Noun", "B2", "кредитная линия", "line of credit", "Banken & Kredite"),
    ("die Bonitätsprüfung, die Prüfungen", "Noun", "B2", "проверка платежеспособности", "credit check", "Banken & Kredite"),
    ("der Kleinkredit, die Kredite", "Noun", "B2", "микрокредит / малый заем", "microloan", "Banken & Kredite"),
    ("die Umschuldung, die Umschuldungen", "Noun", "B2", "рефинансирование долга", "debt restructuring", "Banken & Kredite"),
    ("umschulden", "Verb", "B2", "рефинансировать долг", "to restructure debt", "Banken & Kredite"),
    ("der Verzug, die Verzüge", "Noun", "B2", "просрочка платежа", "default / delay", "Banken & Kredite"),
    ("die Verzugszinsen, (nur Pl.)", "Noun", "B2", "пени / проценты за просрочку", "default interest", "Banken & Kredite"),
    ("die Mahnung, die Mahnungen", "Noun", "B2", "напоминание о платеже / претензия", "dunning letter / reminder", "Banken & Kredite"),
    ("mahnen", "Verb", "B2", "напоминать о платеже / требовать", "to dun / remind", "Banken & Kredite"),
    ("das Inkassobüro, die Inkassobüros", "Noun", "B2", "коллекторское агентство", "collection agency", "Banken & Kredite"),
    ("das Inkasso, die Inkassos", "Noun", "B2", "инкассо / взыскание долгов", "debt collection", "Banken & Kredite"),
    ("die Vollmacht, die Vollmachten", "Noun", "B2", "доверенность", "power of attorney", "Banken & Kredite"),
    ("bevollmächtigen", "Verb", "B2", "уполномочивать / давать доверенность", "to authorize / empower", "Banken & Kredite"),
    ("der Kontoinhaber, die Inhaber", "Noun", "B2", "владелец счета", "account holder", "Banken & Kredite"),
    ("der Mitinhaber, die Mitinhaber", "Noun", "B2", "совладелец счета", "joint holder", "Banken & Kredite"),
    ("das Gemeinschaftkonto, die Konten", "Noun", "B2", "совместный счет", "joint account", "Banken & Kredite"),
    ("die Bankvollmacht, die Vollmachten", "Noun", "B2", "доверенность по счету", "bank authority", "Banken & Kredite"),
    ("die Kreditgewährung, die Gewährungen", "Noun", "B2", "предоставление кредита", "loan granting", "Banken & Kredite"),
    ("sicherstellen", "Verb", "B2", "гарантировать / обеспечивать безопасность", "to secure / guarantee", "Banken & Kredite"),
    ("die Sicherheit, die Sicherheiten", "Noun", "B1", "обеспечение / залог / безопасность", "security / collateral", "Banken & Kredite"),
    ("das Pfand, die Pfänder", "Noun", "B2", "залог", "pledge / pawn", "Banken & Kredite"),
    ("verpfänden", "Verb", "B2", "отдавать в залог", "to pledge / pawn", "Banken & Kredite"),
    ("die Pfändung, die Pfändungen", "Noun", "B2", "арест имущества / изъятие", "attachment / seizure", "Banken & Kredite"),
    ("pfänden", "Verb", "B2", "налагать арест на имущество", "to seize / attach", "Banken & Kredite"),
    ("der Zinsschein, die Zinsscheine", "Noun", "B2", "купон / процентный талон", "coupon", "Banken & Kredite"),
    ("die Zinszahlung, die Zahlungen", "Noun", "B2", "выплата процентов", "interest payment", "Banken & Kredite"),
    ("die Erstattung, die Erstattungen", "Noun", "B2", "возмещение / возврат (средств)", "refund / reimbursement", "Banken & Kredite"),
    ("erstatten", "Verb", "B2", "возмещать / возвращать деньги", "to refund / reimburse", "Banken & Kredite"),
    ("rückzahlen", "Verb", "B1", "выплачивать обратно / погашать", "to repay / refund", "Banken & Kredite"),

    # Category 4: Steuern & Finanzamt (301-400)
    ("die Steuer, die Steuern", "Noun", "B1", "налог", "tax", "Steuern & Finanzamt"),
    ("besteuern", "Verb", "B2", "облагать налогом", "to tax", "Steuern & Finanzamt"),
    ("die Besteuerung, die Besteuerungen", "Noun", "B2", "налогообложение", "taxation", "Steuern & Finanzamt"),
    ("das Finanzamt, die Finanzämter", "Noun", "B1", "налоговая инспекция", "tax office", "Steuern & Finanzamt"),
    ("der Steuerberater, die Steuerberater", "Noun", "B2", "налоговый консультант", "tax advisor", "Steuern & Finanzamt"),
    ("die Steuererklärung, die Erklärungen", "Noun", "B1", "налоговая декларация", "tax return", "Steuern & Finanzamt"),
    ("abgeben", "Verb", "B1", "подавать (декларацию)", "to submit / hand in", "Steuern & Finanzamt"),
    ("die Steuerabgabe, die Abgaben", "Noun", "B2", "налоговый сбор", "tax payment", "Steuern & Finanzamt"),
    ("die Einkommensteuer, die Steuern", "Noun", "B2", "подоходный налог", "income tax", "Steuern & Finanzamt"),
    ("die Mehrwertsteuer, (MwSt.)", "Noun", "B1", "НДС", "value added tax (VAT)", "Steuern & Finanzamt"),
    ("die Umsatzsteuer, (USt.)", "Noun", "B2", "налог с оборота (НДС в бизнесе)", "sales tax / VAT", "Steuern & Finanzamt"),
    ("die Gewerbesteuer, die Steuern", "Noun", "B2", "промысловый налог (на бизнес)", "trade tax", "Steuern & Finanzamt"),
    ("die Körperschaftsteuer, die Steuern", "Noun", "B2", "корпоративный налог", "corporate income tax", "Steuern & Finanzamt"),
    ("die Lohnsteuer, die Lohnsteuern", "Noun", "B2", "подоходный налог с зарплаты", "wage tax", "Steuern & Finanzamt"),
    ("die Kirchensteuer, die Kirchensteuern", "Noun", "B2", "церковный налог", "church tax", "Steuern & Finanzamt"),
    ("die Grundsteuer, die Grundsteuern", "Noun", "B2", "налог на недвижимость", "property tax", "Steuern & Finanzamt"),
    ("die Hundesteuer, die Hundesteuern", "Noun", "B1", "налог на собак", "dog tax", "Steuern & Finanzamt"),
    ("die Kfz-Steuer, die Kfz-Steuern", "Noun", "B2", "транспортный налог", "motor vehicle tax", "Steuern & Finanzamt"),
    ("die Erbschaftsteuer, die Steuern", "Noun", "B2", "налог на наследство", "inheritance tax", "Steuern & Finanzamt"),
    ("die Schenkungsteuer, die Steuern", "Noun", "B2", "налог на дарение", "gift tax", "Steuern & Finanzamt"),
    ("die Kapitalertragsteuer, die Steuern", "Noun", "B2", "налог на доходы от капитала", "capital gains tax", "Steuern & Finanzamt"),
    ("der Steuersatz, die Steuersätze", "Noun", "B2", "налоговая ставка", "tax rate", "Steuern & Finanzamt"),
    ("die Steuerklasse, die Steuerklassen", "Noun", "B2", "налоговый класс", "tax bracket / class", "Steuern & Finanzamt"),
    ("der Freibetrag, die Freibeträge", "Noun", "B2", "необлагаемый минимум", "tax allowance / exemption", "Steuern & Finanzamt"),
    ("absetzen", "Verb", "B2", "списывать с налогов", "to deduct from taxes", "Steuern & Finanzamt"),
    ("steuerlich absetzbar", "Adjective/Phrase", "B2", "списываемый с налогов", "tax-deductible", "Steuern & Finanzamt"),
    ("die Werbungskosten, (nur Pl.)", "Noun", "B2", "расходы на получение дохода", "income-related expenses", "Steuern & Finanzamt"),
    ("die Sonderausgaben, (nur Pl.)", "Noun", "B2", "особые расходы (вычитаемые)", "special expenses", "Steuern & Finanzamt"),
    ("die außergewöhnliche Belastung, die Belastungen", "Noun", "B2", "чрезвычайные расходы", "extraordinary burden", "Steuern & Finanzamt"),
    ("die Steuerhinterziehung, die Hinterziehungen", "Noun", "B2", "уклонение от уплаты налогов", "tax evasion", "Steuern & Finanzamt"),
    ("hinterziehen", "Verb", "B2", "уклоняться (от уплаты налогов)", "to evade (taxes)", "Steuern & Finanzamt"),
    ("die Steuerflucht, (nur Sg.)", "Noun", "B2", "бегство от налогов (в офшоры)", "tax avoidance / flight", "Steuern & Finanzamt"),
    ("die Steueroase, die Steueroasen", "Noun", "B2", "налоговая гавань / оффшор", "tax haven", "Steuern & Finanzamt"),
    ("die Steuerprüfung, die Prüfungen", "Noun", "B2", "налоговая проверка / аудит", "tax audit", "Steuern & Finanzamt"),
    ("der Steuerbescheid, die Bescheide", "Noun", "B2", "налоговое уведомление", "tax assessment notice", "Steuern & Finanzamt"),
    ("die Nachzahlung, die Nachzahlungen", "Noun", "B2", "доплата / недоимка", "additional payment", "Steuern & Finanzamt"),
    ("nachzahlen", "Verb", "B2", "доплачивать", "to pay retrospectively", "Steuern & Finanzamt"),
    ("die Rückerstattung, die Rückerstattungen", "Noun", "B2", "возврат переплаты", "tax refund", "Steuern & Finanzamt"),
    ("zurückerstatten", "Verb", "B2", "возвращать / возмещать", "to refund", "Steuern & Finanzamt"),
    ("die Steuerbefreiung, die Befreiungen", "Noun", "B2", "освобождение от налогов", "tax exemption", "Steuern & Finanzamt"),
    ("steuerfrei", "Adjective", "B1", "не облагаемый налогом", "tax-free / tax-exempt", "Steuern & Finanzamt"),
    ("steuerpflichtig", "Adjective", "B2", "подлежащий налогообложению", "subject to tax", "Steuern & Finanzamt"),
    ("der Steuerzahler, die Steuerzahler", "Noun", "B1", "налогоплательщик", "taxpayer", "Steuern & Finanzamt"),
    ("die Steuernummer, die Steuernummern", "Noun", "B1", "ИНН (налоговый номер)", "tax number", "Steuern & Finanzamt"),
    ("die Steueridentifikationsnummer, (Steuer-ID)", "Noun", "B1", "идентификационный налоговый номер", "tax ID", "Steuern & Finanzamt"),
    ("die Vorsteuer, (nur Sg.)", "Noun", "B2", "предварительный налог (входящий НДС)", "input tax", "Steuern & Finanzamt"),
    ("die Vorsteuerabzug, die Abzüge", "Noun", "B2", "вычет входящего НДС", "deduction of input tax", "Steuern & Finanzamt"),
    ("die Veranlagung, die Veranlagungen", "Noun", "B2", "расчет налоговой базы", "tax assessment", "Steuern & Finanzamt"),
    ("veranlagen", "Verb", "B2", "оценивать для налогообложения", "to assess for tax", "Steuern & Finanzamt"),
    ("die Abgabefrist, die Fristen", "Noun", "B2", "срок подачи (документов)", "submission deadline", "Steuern & Finanzamt"),
    ("verlängern", "Verb", "B1", "продлевать", "to extend / prolong", "Steuern & Finanzamt"),
    ("die Fristverlängerung, die Verlängerungen", "Noun", "B2", "продление срока", "extension of time", "Steuern & Finanzamt"),
    ("der Verspätungszuschlag, die Zuschläge", "Noun", "B2", "штраф за просрочку подачи", "late filing penalty", "Steuern & Finanzamt"),
    ("einlegen", "Verb", "B2", "подавать (апелляцию/протест)", "to file / lodge", "Steuern & Finanzamt"),
    ("der Einspruch, die Einsprüche", "Noun", "B2", "протест / возражение", "objection / appeal", "Steuern & Finanzamt"),
    ("das Steuerrecht, (nur Sg.)", "Noun", "B2", "налоговое законодательство", "tax law", "Steuern & Finanzamt"),
    ("die Gesetzgebung, die Gesetzgebungen", "Noun", "B2", "законодательство", "legislation", "Steuern & Finanzamt"),
    ("reformieren", "Verb", "B2", "реформировать", "to reform", "Steuern & Finanzamt"),
    ("die Steuerreform, die Reformen", "Noun", "B2", "налоговая реформа", "tax reform", "Steuern & Finanzamt"),
    ("die Progression, die Progressionen", "Noun", "B2", "прогрессивное налогообложение", "tax progression", "Steuern & Finanzamt"),
    ("der Steuerfuss, die Steuerfüsse", "Noun", "B2", "коэффициент налога / ставка", "tax multiplier", "Steuern & Finanzamt"),
    ("die Quellensteuer, die Steuern", "Noun", "B2", "налог у источника (выплаты)", "withholding tax", "Steuern & Finanzamt"),
    ("die Abgeltungsteuer, die Steuern", "Noun", "B2", "единый налог на доход от капитала", "flat-rate withholding tax", "Steuern & Finanzamt"),
    ("die Doppelbesteuerung, die Doppelbesteuerungen", "Noun", "B2", "двойное налогообложение", "double taxation", "Steuern & Finanzamt"),
    ("das Abkommen, die Abkommen", "Noun", "B2", "соглашение / договор", "agreement / treaty", "Steuern & Finanzamt"),
    ("die Steuerbelastung, die Belastungen", "Noun", "B2", "налоговая нагрузка", "tax burden", "Steuern & Finanzamt"),
    ("senken", "Verb", "B1", "снижать / опускать", "to lower / reduce", "Steuern & Finanzamt"),
    ("erhöhen", "Verb", "B1", "повышать", "to raise / increase", "Steuern & Finanzamt"),
    ("die Entlastung, die Entlastungen", "Noun", "B2", "облегчение / снижение нагрузки", "relief / deduction", "Steuern & Finanzamt"),
    ("entlasten", "Verb", "B2", "разгружать / снижать нагрузку", "to relieve / ease", "Steuern & Finanzamt"),
    ("die Freigrenze, die Freigrenzen", "Noun", "B2", "лимит освобождения от налога", "tax exemption limit", "Steuern & Finanzamt"),
    ("pauschal", "Adjective", "B2", "фиксированный / единый (о расходах)", "flat-rate / lump-sum", "Steuern & Finanzamt"),
    ("die Pauschale, die Pauschalen", "Noun", "B2", "фиксированная сумма / паушальный платеж", "lump sum", "Steuern & Finanzamt"),
    ("der Pauschbetrag, die Beträge", "Noun", "B2", "фиксированная сумма вычета", "lump-sum allowance", "Steuern & Finanzamt"),
    ("die Quittungbelegpflicht, die Pflichten", "Noun", "B2", "обязанность выдачи чеков", "obligation to issue receipts", "Steuern & Finanzamt"),
    ("das Kassengesetz, die Gesetze", "Noun", "B2", "закон о кассовых операциях", "cash register law", "Steuern & Finanzamt"),
    ("manipulieren", "Verb", "B2", "манипулировать / подтасовывать", "to manipulate / tamper with", "Steuern & Finanzamt"),
    ("die Manipulation, die Manipulationen", "Noun", "B2", "манипуляция / подделка", "manipulation", "Steuern & Finanzamt"),
    ("die Kassenprüfung, die Prüfungen", "Noun", "B2", "аудит кассы", "cash audit", "Steuern & Finanzamt"),
    ("der Steuerprüfer, die Prüfer", "Noun", "B2", "налоговый инспектор", "tax auditor", "Steuern & Finanzamt"),
    ("die Zollbehörde, die Behörden", "Noun", "B2", "таможня", "customs authority", "Steuern & Finanzamt"),
    ("der Zoll, die Zölle", "Noun", "B2", "таможенная пошлина / таможня", "customs / duty", "Steuern & Finanzamt"),
    ("verzollen", "Verb", "B2", "декларировать на таможне", "to declare / pay duty", "Steuern & Finanzamt"),
    ("zollfrei", "Adjective", "B1", "беспошлинный", "duty-free", "Steuern & Finanzamt"),
    ("die Einfuhrumsatzsteuer, (EUSt.)", "Noun", "B2", "импортный НДС", "import turnover tax", "Steuern & Finanzamt"),
    ("die Ausfuhr, die Ausfuhren", "Noun", "B2", "экспорт / вывоз", "export", "Steuern & Finanzamt"),
    ("die Einfuhr, die Einfuhren", "Noun", "B2", "импорт / ввоз", "import", "Steuern & Finanzamt"),
    ("ausführen", "Verb", "B1", "экспортировать", "to export", "Steuern & Finanzamt"),
    ("einführen", "Verb", "B1", "импортировать", "to import", "Steuern & Finanzamt"),
    ("die Verjährung, (nur Sg.)", "Noun", "B2", "исковая давность", "statute of limitations", "Steuern & Finanzamt"),
    ("verjähren", "Verb", "B2", "истекать (по сроку давности)", "to lapse / become statute-barred", "Steuern & Finanzamt"),
    ("die Fristabwicklung, die Abwicklungen", "Noun", "B2", "обработка в установленный срок", "processing in deadline", "Steuern & Finanzamt"),
    ("der Bescheid, die Bescheide", "Noun", "B2", "уведомление / решение", "decision / notification", "Steuern & Finanzamt"),
    ("bescheiden", "Verb", "B2", "выносить решение", "to decide / inform", "Steuern & Finanzamt"),
    ("die Steuerfahndung, die Fahndungen", "Noun", "B2", "налоговая полиция / розыск", "tax investigation", "Steuern & Finanzamt"),
    ("der Fahnder, die Fahnder", "Noun", "B2", "следователь / инспектор розыска", "investigator", "Steuern & Finanzamt"),
    ("durchsuchen", "Verb", "B2", "обыскивать / производить досмотр", "to search / inspect", "Steuern & Finanzamt"),
    ("die Durchsuchung, die Durchsuchungen", "Noun", "B2", "обыск / досмотр", "search", "Steuern & Finanzamt"),
    ("beschlagnahmen", "Verb", "B2", "конфисковать / налагать арест", "to seize / confiscate", "Steuern & Finanzamt"),
    ("die Beschlagnahme, die Beschlagnahmen", "Noun", "B2", "конфискация / арест имущества", "seizure / confiscation", "Steuern & Finanzamt"),

    # Category 5: Investition & Börse (401-500)
    ("die Investition, die Investitionen", "Noun", "B2", "инвестиция / вложение капиталов", "investment", "Investition & Börse"),
    ("investieren", "Verb", "B2", "инвестировать", "to invest", "Investition & Börse"),
    ("der Investor, die Investoren", "Noun", "B2", "инвестор", "investor", "Investition & Börse"),
    ("der Anleger, die Anleger", "Noun", "B2", "вкладчик / инвестор", "investor / depositor", "Investition & Börse"),
    ("die Aktie, die Aktien", "Noun", "B1", "акция", "stock / share", "Investition & Börse"),
    ("der Aktionär, die Aktionäre", "Noun", "B2", "акционер", "shareholder", "Investition & Börse"),
    ("die Börse, die Börsen", "Noun", "B2", "биржа", "stock exchange", "Investition & Börse"),
    ("der Aktienkurs, die Aktienkurse", "Noun", "B2", "курс акций", "stock price", "Investition & Börse"),
    ("steigen", "Verb", "B1", "расти / повышаться", "to rise / climb", "Investition & Börse"),
    ("fallen", "Verb", "B1", "падать / снижаться", "to fall / drop", "Investition & Börse"),
    ("sinken", "Verb", "B1", "снижаться / падать", "to sink / decrease", "Investition & Börse"),
    ("der Wertpapierhandel, (nur Sg.)", "Noun", "B2", "торговля ценными бумагами", "securities trading", "Investition & Börse"),
    ("handeln", "Verb", "B1", "торговать", "to trade", "Investition & Börse"),
    ("der Händler, die Händler", "Noun", "B1", "трейдер / торговец", "trader / dealer", "Investition & Börse"),
    ("der Broker, die Broker", "Noun", "B2", "брокер", "broker", "Investition & Börse"),
    ("die Provision, die Provisionen", "Noun", "B2", "комиссия / провизия", "commission", "Investition & Börse"),
    ("die Rendite, die Renditen", "Noun", "B2", "доходность / рентабельность", "yield / returns", "Investition & Börse"),
    ("die Dividende, die Dividenden", "Noun", "B2", "дивиденд", "dividend", "Investition & Börse"),
    ("ausschütten", "Verb", "B2", "выплачивать (дивиденды)", "to distribute / pay out", "Investition & Börse"),
    ("die Ausschüttung, die Ausschüttungen", "Noun", "B2", "выплата / распределение", "distribution / payout", "Investition & Börse"),
    ("das Risiko, die Risiken", "Noun", "B1", "риск", "risk", "Investition & Börse"),
    ("riskieren", "Verb", "B1", "рисковать", "to risk", "Investition & Börse"),
    ("risikoreich", "Adjective", "B2", "рискованный", "risky / high-risk", "Investition & Börse"),
    ("risikoarm", "Adjective", "B2", "малорискованный", "low-risk", "Investition & Börse"),
    ("die Anleihe, die Anleihen", "Noun", "B2", "облигация / заем", "bond", "Investition & Börse"),
    ("die Staatsanleihe, die Anleihen", "Noun", "B2", "государственная облигация", "government bond", "Investition & Börse"),
    ("der Fonds, die Fonds", "Noun", "B2", "фонд", "fund", "Investition & Börse"),
    ("der Investmentfonds, die Fonds", "Noun", "B2", "паевой инвестиционный фонд", "mutual fund", "Investition & Börse"),
    ("der ETF, die ETFs", "Noun", "B2", "ETF-фонд", "ETF", "Investition & Börse"),
    ("das Portfolio, die Portfolios", "Noun", "B2", "портфель активов", "portfolio", "Investition & Börse"),
    ("spekulieren", "Verb", "B2", "спекулировать / играть на бирже", "to speculate", "Investition & Börse"),
    ("die Spekulation, die Spekulationen", "Noun", "B2", "спекуляция", "speculation", "Investition & Börse"),
    ("der Crash, die Crashes", "Noun", "B2", "обвал / крах", "crash", "Investition & Börse"),
    ("das Depotkonto, die Konten", "Noun", "B2", "депозитарный счет", "custody account", "Investition & Börse"),
    ("der Nennwert, die Nennwerte", "Noun", "B2", "номинальная стоимость", "nominal value", "Investition & Börse"),
    ("der Kurswert, die Kurswerte", "Noun", "B2", "рыночный курс", "market value / price", "Investition & Börse"),
    ("die Kursschwankung, die Schwankungen", "Noun", "B2", "колебание курса", "price fluctuation", "Investition & Börse"),
    ("schwanken", "Verb", "B2", "колебаться", "to fluctuate / vary", "Investition & Börse"),
    ("die Volatilität, (nur Sg.)", "Noun", "B2", "волатильность", "volatility", "Investition & Börse"),
    ("volatil", "Adjective", "B2", "волатильный / изменчивый", "volatile", "Investition & Börse"),
    ("der Bullenmarkt, die Märkte", "Noun", "B2", "бычий рынок (растущий)", "bull market", "Investition & Börse"),
    ("der Bärenmarkt, die Märkte", "Noun", "B2", "медвежий рынок (падающий)", "bear market", "Investition & Börse"),
    ("die Renditeerwartung, die Erwartungen", "Noun", "B2", "ожидаемая доходность", "yield expectation", "Investition & Börse"),
    ("diversifizieren", "Verb", "B2", "диверсифицировать", "to diversify", "Investition & Börse"),
    ("die Diversifikation, die Diversifikationen", "Noun", "B2", "диверсификация", "diversification", "Investition & Börse"),
    ("der Zinsertrag, die Erträge", "Noun", "B2", "процентный доход", "interest income", "Investition & Börse"),
    ("die Dividendenrendite, die Renditen", "Noun", "B2", "дивидендная доходность", "dividend yield", "Investition & Börse"),
    ("die Gewinnspanne, die Gewinspannen", "Noun", "B2", "маржа прибыли", "profit margin", "Investition & Börse"),
    ("der Nettogewinn, die Gewinne", "Noun", "B2", "чистая прибыль", "net profit", "Investition & Börse"),
    ("der Bruttogewinn, die Gewinne", "Noun", "B2", "валовая прибыль", "gross profit", "Investition & Börse"),
    ("der Kostenfaktor, die Kostenfaktoren", "Noun", "B2", "фактор затрат", "cost factor", "Investition & Börse"),
    ("die Kostenanalyse, die Analysen", "Noun", "B2", "анализ затрат", "cost analysis", "Investition & Börse"),
    ("die Rentabilität, (nur Sg.)", "Noun", "B2", "рентабельность", "profitability / rentability", "Investition & Börse"),
    ("rentabel", "Adjective", "B2", "рентабельный / доходный", "profitable", "Investition & Börse"),
    ("das Leasing, (nur Sg.)", "Noun", "B2", "лизинг", "leasing", "Investition & Börse"),
    ("leasen", "Verb", "B2", "брать в лизинг", "to lease", "Investition & Börse"),
    ("die Tilgungsrate, die Raten", "Noun", "B2", "размер взноса по долгу", "repayment rate", "Investition & Börse"),
    ("die Fristigkeit, (nur Sg.)", "Noun", "B2", "срочность (обязательств)", "maturity", "Investition & Börse"),
    ("fristgerecht", "Adjective", "B2", "в срок / своевременный", "timely / within deadline", "Investition & Börse"),
    ("fristwidrig", "Adjective", "B2", "несвоевременный / с нарушением срока", "contrary to deadline", "Investition & Börse"),
    ("das Budgetdefizit, die Defizite", "Noun", "B2", "дефицит бюджета", "budget deficit", "Investition & Börse"),
    ("ausgleichen", "Verb", "B2", "сбалансировать (бюджет)", "to balance", "Investition & Börse"),
    ("die Rücklage, die Rücklagen", "Noun", "B2", "резервный фонд / накопления", "reserve / backlog", "Investition & Börse"),
    ("die Kapitalerhöhung, die Erhöhungen", "Noun", "B2", "увеличение капитала", "capital increase", "Investition & Börse"),
    ("die Kapitalherabsetzung, die Setzungen", "Noun", "B2", "уменьшение капитала", "capital reduction", "Investition & Börse"),
    ("die Emission, die Emissionen", "Noun", "B2", "эмиссия / выпуск ценных бумаг", "issuance / emission", "Investition & Börse"),
    ("emittieren", "Verb", "B2", "выпускать ценные бумаги", "to issue", "Investition & Börse"),
    ("der Emittent, die Emittenten", "Noun", "B2", "эмитент", "issuer", "Investition & Börse"),
    ("die Erstplatzierung, die Erstplatzierungen", "Noun", "B2", "первичное публичное размещение (IPO)", "initial public offering (IPO)", "Investition & Börse"),
    ("das IPO, die IPOs", "Noun", "B2", "IPO (первичное размещение)", "IPO", "Investition & Börse"),
    ("die Zeichnung, die Zeichnungen", "Noun", "B2", "подписка (на ценные бумаги)", "subscription", "Investition & Börse"),
    ("zeichnen", "Verb", "B2", "подписываться (на акции)", "to subscribe", "Investition & Börse"),
    ("das Agio, die Agios", "Noun", "B2", "ажио / надбавка к номиналу", "premium / agio", "Investition & Börse"),
    ("das Disagio, die Disagios", "Noun", "B2", "дизажио / скидка с номинала", "discount / disagio", "Investition & Börse"),
    ("der Nennwertkurs, die Kurse", "Noun", "B2", "номинальный курс", "par value rate", "Investition & Börse"),
    ("die Gewinnbeteiligung, die Beteiligungen", "Noun", "B2", "участие в прибылях", "profit sharing", "Investition & Börse"),
    ("beteiligen", "Verb", "B1", "участвовать / привлекать", "to participate / share", "Investition & Börse"),
    ("die Beteiligung, die Beteiligungen", "Noun", "B2", "доля (в капитале) / участие", "share / participation", "Investition & Börse"),
    ("der Mehrheitsgesellschafter, die Gesellschafter", "Noun", "B2", "мажоритарный акционер", "majority shareholder", "Investition & Börse"),
    ("der Minderheitsgesellschafter, die Gesellschafter", "Noun", "B2", "миноритарный акционер", "minority shareholder", "Investition & Börse"),
    ("die Hauptversammlung, die Versammlungen", "Noun", "B2", "общее собрание акционеров", "annual general meeting", "Investition & Börse"),
    ("beschließen", "Verb", "B1", "принимать решение (на собрании)", "to resolve / decide", "Investition & Börse"),
    ("der Beschluss, die Beschlüsse", "Noun", "B2", "решение / резолюция", "resolution / decision", "Investition & Börse"),
    ("das Stimmrecht, die Stimmrechte", "Noun", "B2", "право голоса", "voting right", "Investition & Börse"),
    ("stimmen", "Verb", "B1", "голосовать", "to vote", "Investition & Börse"),
    ("die Abstimmung, die Abstimmungen", "Noun", "B1", "голосование", "voting / vote", "Investition & Börse"),
    ("der Aufsichtsrat, die Aufsichtsräte", "Noun", "B2", "наблюдательный совет", "supervisory board", "Investition & Börse"),
    ("der Vorstand, die Vorstände", "Noun", "B2", "правление / совет директоров", "management board", "Investition & Börse"),
    ("das Risikomanagement, (nur Sg.)", "Noun", "B2", "управление рисками", "risk management", "Investition & Börse"),
    ("minimieren", "Verb", "B2", "минимизировать", "to minimize", "Investition & Börse"),
    ("maximieren", "Verb", "B2", "максимизировать", "to maximize", "Investition & Börse"),
    ("die Verlustbegrenzung, die Begrenzungen", "Noun", "B2", "ограничение убытков (стоп-лосс)", "stop-loss / limit loss", "Investition & Börse"),
    ("der Stop-Loss, die Stop-Losses", "Noun", "B2", "стоп-лосс", "stop-loss", "Investition & Börse"),
    ("der Gewinnvortrag, die Vorträge", "Noun", "B2", "нераспределенная прибыль", "retained earnings", "Investition & Börse"),
    ("der Verlustvortrag, die Vorträge", "Noun", "B2", "непокрытый убыток прошлых лет", "loss carryforward", "Investition & Börse"),
    ("die Rücklagebildung, die Bildungen", "Noun", "B2", "формирование резервов", "reserve creation", "Investition & Börse"),
    ("die Liquiditätsplanung, die Planungen", "Noun", "B2", "планирование ликвидности", "liquidity planning", "Investition & Börse"),
    ("das Anlagekapital, (nur Sg.)", "Noun", "B2", "инвестированный капитал", "investment capital", "Investition & Börse"),
    ("die Vermögensverwaltung, die Verwaltungen", "Noun", "B2", "управление активами", "asset management", "Investition & Börse"),
    ("verwalten", "Verb", "B1", "управлять", "to manage / administer", "Investition & Börse"),
]
