# -*- coding: utf-8 -*-

words = [
    # Category 1: Bewerbung & Lebenslauf (1-100)
    ("die Bewerbung, die Bewerbungen", "Noun", "B1", "заявление о приеме на работу / резюме", "job application", "Bewerbung & Lebenslauf"),
    ("der Lebenslauf, die Lebensläufe", "Noun", "B1", "автобиография / резюме", "curriculum vitae (CV)", "Bewerbung & Lebenslauf"),
    ("das Anschreiben, die Anschreiben", "Noun", "B2", "сопроводительное письмо", "cover letter", "Bewerbung & Lebenslauf"),
    ("das Zeugnis, die Zeugnisse", "Noun", "B1", "свидетельство / аттестат / рекомендация", "certificate / reference", "Bewerbung & Lebenslauf"),
    ("das Arbeitszeugnis, die Arbeitszeugnisse", "Noun", "B2", "рекомендательное письмо с места работы", "employment reference", "Bewerbung & Lebenslauf"),
    ("das Motivationsschreiben, die Motivationsschreiben", "Noun", "B2", "мотивационное письмо", "letter of motivation", "Bewerbung & Lebenslauf"),
    ("die Unterlagen, (nur Pl.)", "Noun", "B1", "документы / бумаги", "documents / dossier", "Bewerbung & Lebenslauf"),
    ("der Anhang, die Anhänge", "Noun", "B1", "приложение / вложение", "attachment / appendix", "Bewerbung & Lebenslauf"),
    ("die Stellenanzeige, die Stellenanzeigen", "Noun", "B1", "объявление о вакансии", "job advertisement", "Bewerbung & Lebenslauf"),
    ("das Jobportal, die Jobportale", "Noun", "B1", "портал по поиску работы", "job portal", "Bewerbung & Lebenslauf"),
    ("sich bewerben", "Verb", "B1", "подавать заявление о приеме на работу", "to apply for a job", "Bewerbung & Lebenslauf"),
    ("einreichen", "Verb", "B2", "подавать / представлять (документы)", "to submit / hand in", "Bewerbung & Lebenslauf"),
    ("hochladen", "Verb", "B1", "загружать / выгружать (в сеть)", "to upload", "Bewerbung & Lebenslauf"),
    ("verfassen", "Verb", "B2", "составлять / сочинять (текст)", "to write / draft", "Bewerbung & Lebenslauf"),
    ("die Berufserfahrung, die Berufserfahrungen", "Noun", "B1", "опыт работы", "work experience", "Bewerbung & Lebenslauf"),
    ("der Werdegang, (nur Sg.)", "Noun", "B2", "профессиональный путь / карьера", "career path / background", "Bewerbung & Lebenslauf"),
    ("die Qualifikation, die Qualifikationen", "Noun", "B1", "квалификация", "qualification", "Bewerbung & Lebenslauf"),
    ("die Kenntnisse, (nur Pl.)", "Noun", "B1", "знания / умения", "knowledge / skills", "Bewerbung & Lebenslauf"),
    ("die Ausbildung, die Ausbildungen", "Noun", "B1", "профессиональное обучение / образование", "vocational training / education", "Bewerbung & Lebenslauf"),
    ("das Studium, die Studien", "Noun", "B1", "учеба в вузе", "university studies", "Bewerbung & Lebenslauf"),
    ("der Studienabschluss, die Studienabschlüsse", "Noun", "B2", "диплом об окончании вуза", "university degree", "Bewerbung & Lebenslauf"),
    ("die Fachrichtung, die Fachrichtungen", "Noun", "B2", "специализация / направление", "field of specialization", "Bewerbung & Lebenslauf"),
    ("der Schwerpunkt, die Schwerpunkte", "Noun", "B2", "основной упор / специализация", "main focus / specialization", "Bewerbung & Lebenslauf"),
    ("das Zertifikat, die Zertifikate", "Noun", "B1", "сертификат / свидетельство", "certificate", "Bewerbung & Lebenslauf"),
    ("die Referenz, die Referenzen", "Noun", "B2", "рекомендация / отзыв", "reference / recommendation", "Bewerbung & Lebenslauf"),
    ("das Praktikum, die Praktika", "Noun", "B1", "практика / стажировка", "internship / placement", "Bewerbung & Lebenslauf"),
    ("der Praktikant, die Praktikanten", "Noun", "B1", "практикант / стажер", "intern / trainee", "Bewerbung & Lebenslauf"),
    ("die Aushilfsstelle, die Aushilfsstellen", "Noun", "B2", "временная работа / подработка", "temporary / assistant position", "Bewerbung & Lebenslauf"),
    ("die Teilzeitstelle, die Teilzeitstellen", "Noun", "B1", "работа на неполную ставку", "part-time job", "Bewerbung & Lebenslauf"),
    ("die Vollzeitstelle, die Vollzeitstellen", "Noun", "B1", "работа на полную ставку", "full-time job", "Bewerbung & Lebenslauf"),
    ("die Festanstellung, die Festanstellungen", "Noun", "B2", "постоянная работа (в штате)", "permanent position", "Bewerbung & Lebenslauf"),
    ("befristet", "Adjective", "B2", "ограниченный сроком / временный", "temporary / fixed-term", "Bewerbung & Lebenslauf"),
    ("unbefristet", "Adjective", "B2", "бессрочный / постоянный", "permanent / open-ended", "Bewerbung & Lebenslauf"),
    ("das Stellenangebot, die Stellenangebote", "Noun", "B1", "предложение о работе / вакансия", "job offer / vacancy", "Bewerbung & Lebenslauf"),
    ("die Initiativbewerbung, die Initiativbewerbungen", "Noun", "B2", "инициативное резюме (без открытой вакансии)", "speculative application", "Bewerbung & Lebenslauf"),
    ("das Bewerbungsfoto, die Bewerbungsfotos", "Noun", "B1", "фотография для резюме", "application photo", "Bewerbung & Lebenslauf"),
    ("die E-Mail-Bewerbung, die E-Mail-Bewerbungen", "Noun", "B1", "отклик по электронной почте", "email application", "Bewerbung & Lebenslauf"),
    ("das Profil, die Profile", "Noun", "B1", "профиль / характеристика", "profile", "Bewerbung & Lebenslauf"),
    ("die Stellenausschreibung, die Stellenausschreibungen", "Noun", "B2", "объявление о вакансии", "job posting", "Bewerbung & Lebenslauf"),
    ("der Bewerber, die Bewerber", "Noun", "B1", "кандидат / соискатель", "applicant / candidate", "Bewerbung & Lebenslauf"),
    ("die Bewerberin, die Bewerberinnen", "Noun", "B1", "кандидатка / соискательница", "female applicant", "Bewerbung & Lebenslauf"),
    ("die Bewerbungsfrist, die Bewerbungsfristen", "Noun", "B2", "срок подачи резюме", "application deadline", "Bewerbung & Lebenslauf"),
    ("das Bewerbungsverfahren, die Bewerbungsverfahren", "Noun", "B2", "процесс отбора кандидатов", "application process", "Bewerbung & Lebenslauf"),
    ("die Bewerbungsmappe, die Bewerbungsmappen", "Noun", "B2", "папка с документами соискателя", "application portfolio", "Bewerbung & Lebenslauf"),
    ("der Karriereweg, die Karrierewege", "Noun", "B2", "путь карьерного роста", "career path", "Bewerbung & Lebenslauf"),
    ("die Kompetenz, die Kompetenzen", "Noun", "B2", "компетенция / квалификация", "competence / skill", "Bewerbung & Lebenslauf"),
    ("die Soft Skills, (nur Pl.)", "Noun", "B2", "гибкие навыки (личные качества)", "soft skills", "Bewerbung & Lebenslauf"),
    ("die Hard Skills, (nur Pl.)", "Noun", "B2", "профессиональные / жесткие навыки", "hard skills", "Bewerbung & Lebenslauf"),
    ("das Fachwissen, (nur Sg.)", "Noun", "B2", "профессиональные знания", "expert knowledge", "Bewerbung & Lebenslauf"),
    ("die Sprachkenntnisse, (nur Pl.)", "Noun", "B1", "знание языков", "language skills", "Bewerbung & Lebenslauf"),
    ("die IT-Kenntnisse, (nur Pl.)", "Noun", "B1", "компьютерная грамотность / знание IT", "IT skills", "Bewerbung & Lebenslauf"),
    ("die Weiterbildung, die Weiterbildungen", "Noun", "B1", "повышение квалификации", "further training / education", "Bewerbung & Lebenslauf"),
    ("der Quereinsteiger, die Quereinsteiger", "Noun", "B2", "специалист из другой сферы", "lateral entrant", "Bewerbung & Lebenslauf"),
    ("die Umschulung, die Umschulungen", "Noun", "B2", "переобучение / переквалификация", "retraining", "Bewerbung & Lebenslauf"),
    ("die Referenzperson, die Referenzpersonen", "Noun", "B2", "лицо, дающее рекомендацию", "referee", "Bewerbung & Lebenslauf"),
    ("das Empfehlungsschreiben, die Empfehlungsschreiben", "Noun", "B2", "рекомендательное письмо", "letter of recommendation", "Bewerbung & Lebenslauf"),
    ("die Lücke, die Lücken", "Noun", "B2", "пробел (в резюме/биографии)", "gap (in CV)", "Bewerbung & Lebenslauf"),
    ("der Lebenslauf-Entwurf, die Entwürfe", "Noun", "B2", "черновик резюме", "CV draft", "Bewerbung & Lebenslauf"),
    ("aktuell", "Adjective", "B1", "текущий / актуальный", "current / up-to-date", "Bewerbung & Lebenslauf"),
    ("lückenlos", "Adjective", "B2", "без пробелов (о биографии)", "without gaps / continuous", "Bewerbung & Lebenslauf"),
    ("ausführlich", "Adjective", "B1", "подробный / детальный", "detailed", "Bewerbung & Lebenslauf"),
    ("kurzgefasst", "Adjective", "B2", "краткий / сжатый", "summarized / concise", "Bewerbung & Lebenslauf"),
    ("aussagekräftig", "Adjective", "B2", "информативный / содержательный", "meaningful / significant", "Bewerbung & Lebenslauf"),
    ("der Bildungsabschluss, die Bildungsabschlüsse", "Noun", "B2", "уровень образования (степень)", "educational qualification", "Bewerbung & Lebenslauf"),
    ("die Berufsausbildung, die Berufsausbildungen", "Noun", "B1", "профтехобразование", "vocational training", "Bewerbung & Lebenslauf"),
    ("die Eignung, die Eignungen", "Noun", "B2", "пригодность / соответствие требованиям", "suitability / fitness", "Bewerbung & Lebenslauf"),
    ("geeignet", "Adjective", "B1", "подходящий / пригодный", "suitable / qualified", "Bewerbung & Lebenslauf"),
    ("der Arbeitsmarkt, die Arbeitsmärkte", "Noun", "B2", "рынок труда", "labor market", "Bewerbung & Lebenslauf"),
    ("die Jobbörse, die Jobbörsen", "Noun", "B1", "биржа труда / сайт вакансий", "job board", "Bewerbung & Lebenslauf"),
    ("die Vermittlung, die Vermittlungen", "Noun", "B2", "трудоустройство / посредничество", "placement / agency", "Bewerbung & Lebenslauf"),
    ("der Headhunter, die Headhunter", "Noun", "B2", "охотник за головами / рекрутер", "headhunter", "Bewerbung & Lebenslauf"),
    ("die Personalberatung, die Personalberatungen", "Noun", "B2", "агентство по подбору персонала", "recruitment consultancy", "Bewerbung & Lebenslauf"),
    ("das Anschreiben-Muster, die Muster", "Noun", "B2", "образец сопроводительного письма", "cover letter template", "Bewerbung & Lebenslauf"),
    ("die Unterschrift, die Unterschriften", "Noun", "B1", "подпись", "signature", "Bewerbung & Lebenslauf"),
    ("die Kontaktdaten, (nur Pl.)", "Noun", "B1", "контактные данные", "contact details", "Bewerbung & Lebenslauf"),
    ("das Anschreiben-Layout, die Layouts", "Noun", "B2", "оформление сопроводительного письма", "cover letter layout", "Bewerbung & Lebenslauf"),
    ("die PDF-Datei, die PDF-Dateien", "Noun", "B1", "файл формата PDF", "PDF file", "Bewerbung & Lebenslauf"),
    ("die Formatierung, die Formatierungen", "Noun", "B2", "форматирование", "formatting", "Bewerbung & Lebenslauf"),
    ("das Anschreiben-Design, die Designs", "Noun", "B2", "дизайн сопроводительного письма", "cover letter design", "Bewerbung & Lebenslauf"),
    ("der Lebenslauf-Aufbau, (nur Sg.)", "Noun", "B2", "структура резюме", "CV structure", "Bewerbung & Lebenslauf"),
    ("die Berufspraxis, (nur Sg.)", "Noun", "B2", "профессиональная практика", "professional practice", "Bewerbung & Lebenslauf"),
    ("die Zusatzqualifikation, die Zusatzqualifikationen", "Noun", "B2", "дополнительная квалификация", "additional qualification", "Bewerbung & Lebenslauf"),
    ("das Schulzeugnis, die Schulzeugnisse", "Noun", "B1", "школьный аттестат", "school certificate", "Bewerbung & Lebenslauf"),
    ("das Diplom, die Diplome", "Noun", "B1", "диплом", "diploma", "Bewerbung & Lebenslauf"),
    ("das Bachelorzeugnis, die Bachelorzeugnisse", "Noun", "B2", "диплом бакалавра", "bachelor's certificate", "Bewerbung & Lebenslauf"),
    ("das Masterzeugnis, die Masterzeugnisse", "Noun", "B2", "диплом магистра", "master's certificate", "Bewerbung & Lebenslauf"),
    ("das Empfehlungsdokument, die Dokumente", "Noun", "B2", "рекомендательный документ", "recommendation document", "Bewerbung & Lebenslauf"),
    ("das Anschreiben-Ziel, die Ziele", "Noun", "B2", "цель сопроводительного письма", "cover letter goal", "Bewerbung & Lebenslauf"),
    ("die Initiativstelle, die Initiativstellen", "Noun", "B2", "инициативная вакансия", "speculative vacancy", "Bewerbung & Lebenslauf"),
    ("der Ansprechpartner, die Ansprechpartner", "Noun", "B1", "контактное лицо", "contact person", "Bewerbung & Lebenslauf"),
    ("anpassen", "Verb", "B1", "адаптировать / подгонять", "to adapt / customize", "Bewerbung & Lebenslauf"),
    ("überarbeiten", "Verb", "B2", "перерабатывать / редактировать", "to revise / edit", "Bewerbung & Lebenslauf"),
    ("kontrollieren", "Verb", "B1", "контролировать / проверять", "to check / control", "Bewerbung & Lebenslauf"),
    ("korrekturlesen", "Verb", "B2", "вычитывать / корректировать", "to proofread", "Bewerbung & Lebenslauf"),
    ("speichern", "Verb", "B1", "сохранять", "to save", "Bewerbung & Lebenslauf"),
    ("ausdrucken", "Verb", "B1", "распечатывать", "to print", "Bewerbung & Lebenslauf"),
    ("versenden", "Verb", "B1", "отправлять / рассылать", "to send", "Bewerbung & Lebenslauf"),
    ("erwarten", "Verb", "B1", "ожидать / требовать", "to expect", "Bewerbung & Lebenslauf"),
    ("erfüllen", "Verb", "B1", "выполнять / удовлетворять (требованиям)", "to fulfill / satisfy", "Bewerbung & Lebenslauf"),
    ("die Stellensuche, (nur Sg.)", "Noun", "B1", "поиск работы", "job search", "Bewerbung & Lebenslauf"),

    # Category 2: Gesprächsablauf & Fragen (101-200)
    ("die Einladung, die Einladungen", "Noun", "B1", "приглашение", "invitation", "Gesprächsablauf & Fragen"),
    ("das Vorstellungsgespräch, die Vorstellungsgespräche", "Noun", "B1", "собеседование (при приеме на работу)", "job interview", "Gesprächsablauf & Fragen"),
    ("der Termin, die Termine", "Noun", "B1", "встреча / назначенное время", "appointment", "Gesprächsablauf & Fragen"),
    ("zusagen", "Verb", "B1", "соглашаться / подтверждать", "to accept / confirm", "Gesprächsablauf & Fragen"),
    ("absagen", "Verb", "B1", "отказываться / отменять", "to reject / cancel", "Gesprächsablauf & Fragen"),
    ("die Vorbereitung, die Vorbereitungen", "Noun", "B1", "подготовка", "preparation", "Gesprächsablauf & Fragen"),
    ("sich vorbereiten", "Verb", "B1", "готовиться", "to prepare oneself", "Gesprächsablauf & Fragen"),
    ("die Anreise, die Anreisen", "Noun", "B1", "прибытие / приезд", "travel / arrival", "Gesprächsablauf & Fragen"),
    ("pünktlich", "Adjective", "B1", "пунктуальный / вовремя", "punctual", "Gesprächsablauf & Fragen"),
    ("die Pünktlichkeit, (nur Sg.)", "Noun", "B1", "пунктуальность", "punctuality", "Gesprächsablauf & Fragen"),
    ("der Empfang, die Empfänge", "Noun", "B1", "прием / стойка регистрации", "reception", "Gesprächsablauf & Fragen"),
    ("begrüßen", "Verb", "B1", "приветствовать", "to greet", "Gesprächsablauf & Fragen"),
    ("der Händedruck, die Händedrücke", "Noun", "B2", "рукопожатие", "handshake", "Gesprächsablauf & Fragen"),
    ("die Körpersprache, (nur Sg.)", "Noun", "B2", "язык тела / мимика и жесты", "body language", "Gesprächsablauf & Fragen"),
    ("der Augenkontakt, die Augenkontakte", "Noun", "B2", "визуальный контакт", "eye contact", "Gesprächsablauf & Fragen"),
    ("die Haltung, die Haltungen", "Noun", "B2", "осанка / отношение / позиция", "posture / attitude", "Gesprächsablauf & Fragen"),
    ("aufgeregt", "Adjective", "B1", "взволнованный / нервный", "excited / nervous", "Gesprächsablauf & Fragen"),
    ("die Aufregung, (nur Sg.)", "Noun", "B1", "волнение / возбуждение", "excitement / nervousness", "Gesprächsablauf & Fragen"),
    ("der Gesprächspartner, die Gesprächspartner", "Noun", "B1", "собеседник", "interview partner", "Gesprächsablauf & Fragen"),
    ("der Personalleiter, die Personalleiter", "Noun", "B2", "руководитель отдела кадров", "HR manager", "Gesprächsablauf & Fragen"),
    ("der Abteilungsleiter, die Abteilungsleiter", "Noun", "B2", "начальник отдела", "department manager", "Gesprächsablauf & Fragen"),
    ("die Vorstellung, die Vorstellungen", "Noun", "B1", "представление / презентация", "introduction", "Gesprächsablauf & Fragen"),
    ("sich vorstellen", "Verb", "B1", "представляться / презентовать себя", "to introduce oneself", "Gesprächsablauf & Fragen"),
    ("der Ablauf, die Abläufe", "Noun", "B1", "ход событий / процесс", "process / flow", "Gesprächsablauf & Fragen"),
    ("der Einstieg, die Einstiege", "Noun", "B2", "введение / начало / вступление", "intro / entry", "Gesprächsablauf & Fragen"),
    ("die Frage, die Fragen", "Noun", "B1", "вопрос", "question", "Gesprächsablauf & Fragen"),
    ("antworten", "Verb", "B1", "отвечать", "to answer", "Gesprächsablauf & Fragen"),
    ("die Antwort, die Antworten", "Noun", "B1", "ответ", "answer", "Gesprächsablauf & Fragen"),
    ("fragen", "Verb", "B1", "спрашивать", "to ask", "Gesprächsablauf & Fragen"),
    ("nachfragen", "Verb", "B2", "расспрашивать / уточнять", "to ask for details / inquire", "Gesprächsablauf & Fragen"),
    ("die Nachfrage, die Nachfragen", "Noun", "B2", "запрос / расспросы / уточнение", "inquiry / demand", "Gesprächsablauf & Fragen"),
    ("ausweichen", "Verb", "B2", "уклоняться / избегать (вопроса)", "to evade", "Gesprächsablauf & Fragen"),
    ("ausweichend", "Adjective", "B2", "уклончивый (ответ)", "evasive", "Gesprächsablauf & Fragen"),
    ("eingehen auf", "Verb", "B2", "останавливаться на / реагировать на", "to go into / address", "Gesprächsablauf & Fragen"),
    ("erklären", "Verb", "B1", "объяснять", "to explain", "Gesprächsablauf & Fragen"),
    ("begründen", "Verb", "B2", "обосновывать / аргументировать", "to justify", "Gesprächsablauf & Fragen"),
    ("die Begründung, die Begründungen", "Noun", "B2", "обоснование / аргумент", "justification", "Gesprächsablauf & Fragen"),
    ("das Interesse, die Interessen", "Noun", "B1", "интерес", "interest", "Gesprächsablauf & Fragen"),
    ("das Desinteresse, (nur Sg.)", "Noun", "B2", "безучастие / отсутствие интереса", "disinterest", "Gesprächsablauf & Fragen"),
    ("betonen", "Verb", "B2", "подчеркивать / акцентировать", "to emphasize", "Gesprächsablauf & Fragen"),
    ("hervorheben", "Verb", "B2", "выделять / отмечать", "to highlight", "Gesprächsablauf & Fragen"),
    ("beschreiben", "Verb", "B1", "описывать", "to describe", "Gesprächsablauf & Fragen"),
    ("darstellen", "Verb", "B2", "представлять / излагать", "to present / depict", "Gesprächsablauf & Fragen"),
    ("die Darstellung, die Darstellungen", "Noun", "B2", "описание / изложение", "presentation / depiction", "Gesprächsablauf & Fragen"),
    ("schildern", "Verb", "B2", "описывать / живописать", "to portray / describe", "Gesprächsablauf & Fragen"),
    ("die Schilderung, die Schilderungen", "Noun", "B2", "описание / рассказ", "portrayal / description", "Gesprächsablauf & Fragen"),
    ("die Situation, die Situationen", "Noun", "B1", "ситуация", "situation", "Gesprächsablauf & Fragen"),
    ("das Beispiel, die Beispiele", "Noun", "B1", "пример", "example", "Gesprächsablauf & Fragen"),
    ("veranschaulichen", "Verb", "B2", "иллюстрировать / делать наглядным", "to illustrate", "Gesprächsablauf & Fragen"),
    ("ausführen", "Verb", "B2", "разъяснять / подробно излагать", "to elaborate", "Gesprächsablauf & Fragen"),
    ("die Ausführung, die Ausführungen", "Noun", "B2", "детализация / подробное изложение", "elaboration", "Gesprächsablauf & Fragen"),
    ("die Rückfrage, die Rückfragen", "Noun", "B2", "уточняющий вопрос", "follow-up question", "Gesprächsablauf & Fragen"),
    ("aufmerksam", "Adjective", "B1", "внимательный", "attentive", "Gesprächsablauf & Fragen"),
    ("die Aufmerksamkeit, (nur Sg.)", "Noun", "B1", "внимание", "attention", "Gesprächsablauf & Fragen"),
    ("zuhören", "Verb", "B1", "слушать / прислушиваться", "to listen", "Gesprächsablauf & Fragen"),
    ("ausreden lassen", "Verb", "B2", "дать выговориться / не перебивать", "to let finish speaking", "Gesprächsablauf & Fragen"),
    ("die Pause, die Pausen", "Noun", "B1", "пауза", "pause", "Gesprächsablauf & Fragen"),
    ("die Denkpause, die Denkpausen", "Noun", "B2", "пауза для размышления", "pause for thought", "Gesprächsablauf & Fragen"),
    ("ruhig bleiben", "Verb", "B1", "сохранять спокойствие", "to stay calm", "Gesprächsablauf & Fragen"),
    ("die Ruhe, (nur Sg.)", "Noun", "B1", "спокойствие", "calmness", "Gesprächsablauf & Fragen"),
    ("die Nervosität, (nur Sg.)", "Noun", "B2", "нервозность", "nervousness", "Gesprächsablauf & Fragen"),
    ("lächeln", "Verb", "B1", "улыбаться", "to smile", "Gesprächsablauf & Fragen"),
    ("das Lächeln, (nur Sg.)", "Noun", "B1", "улыбка", "smile", "Gesprächsablauf & Fragen"),
    ("sympathisch", "Adjective", "B1", "симпатичный / приятный", "likeable / sympathetic", "Gesprächsablauf & Fragen"),
    ("die Sympathie, die Sympathien", "Noun", "B2", "симпатия / взаимное притяжение", "sympathy", "Gesprächsablauf & Fragen"),
    ("professionell", "Adjective", "B1", "профессиональный", "professional", "Gesprächsablauf & Fragen"),
    ("die Professionalität, (nur Sg.)", "Noun", "B2", "профессионализм", "professionalism", "Gesprächsablauf & Fragen"),
    ("offen", "Adjective", "B1", "открытый / откровенный", "open / candid", "Gesprächsablauf & Fragen"),
    ("die Offenheit, (nur Sg.)", "Noun", "B2", "открытость", "openness", "Gesprächsablauf & Fragen"),
    ("ehrlich", "Adjective", "B1", "честный", "honest", "Gesprächsablauf & Fragen"),
    ("die Ehrlichkeit, (nur Sg.)", "Noun", "B2", "честность", "honesty", "Gesprächsablauf & Fragen"),
    ("authentisch", "Adjective", "B2", "подлинный / естественный", "authentic", "Gesprächsablauf & Fragen"),
    ("die Authentizität, (nur Sg.)", "Noun", "B2", "подлинность / искренность", "authenticity", "Gesprächsablauf & Fragen"),
    ("überzeugend", "Adjective", "B2", "убедительный", "convincing", "Gesprächsablauf & Fragen"),
    ("überzeugen", "Verb", "B2", "убеждать", "to convince", "Gesprächsablauf & Fragen"),
    ("die Überzeugung, die Überzeugungen", "Noun", "B2", "убеждение / уверенность", "conviction", "Gesprächsablauf & Fragen"),
    ("der Eindruck, die Eindrücke", "Noun", "B1", "впечатление", "impression", "Gesprächsablauf & Fragen"),
    ("Eindruck machen", "Verb", "B2", "произвести впечатление", "to make an impression", "Gesprächsablauf & Fragen"),
    ("hinterlassen", "Verb", "B2", "оставлять (после себя)", "to leave (an impression)", "Gesprächsablauf & Fragen"),
    ("der Gesprächsstoff, die Gesprächsstoffe", "Noun", "B2", "тема для разговора", "conversation topic", "Gesprächsablauf & Fragen"),
    ("das Feedback, die Feedbacks", "Noun", "B2", "обратная связь", "feedback", "Gesprächsablauf & Fragen"),
    ("sich verabschieden", "Verb", "B1", "прощаться", "to say goodbye", "Gesprächsablauf & Fragen"),
    ("die Verabschiedung, die Verabschiedungen", "Noun", "B2", "proщание", "farewell", "Gesprächsablauf & Fragen"),
    ("der Ausgang, die Ausgänge", "Noun", "B1", "выход", "exit", "Gesprächsablauf & Fragen"),
    ("die Nachbereitung, die Nachbereitungen", "Noun", "B2", "подведение итогов / разбор", "follow-up", "Gesprächsablauf & Fragen"),
    ("sich bedanken", "Verb", "B1", "благодарить", "to thank", "Gesprächsablauf & Fragen"),
    ("der Dank, (nur Sg.)", "Noun", "B1", "благодарность", "thanks", "Gesprächsablauf & Fragen"),
    ("das Dankschreiben, die Dankschreiben", "Noun", "B2", "благодарственное письмо", "thank you letter", "Gesprächsablauf & Fragen"),
    ("abwarten", "Verb", "B2", "выжидать / ждать результатов", "to wait and see", "Gesprächsablauf & Fragen"),
    ("die Entscheidung, die Entscheidungen", "Noun", "B1", "решение", "decision", "Gesprächsablauf & Fragen"),
    ("entscheiden", "Verb", "B1", "решать / принимать решение", "to decide", "Gesprächsablauf & Fragen"),
    ("die Rückmeldung, die Rückmeldungen", "Noun", "B2", "ответ / отклик / обратная связь", "feedback / response", "Gesprächsablauf & Fragen"),
    ("die Zusage, die Zusagen", "Noun", "B2", "согласие (прием на работу)", "acceptance / offer", "Gesprächsablauf & Fragen"),
    ("die Absage, die Absagen", "Noun", "B2", "отказ (приеме на работу)", "rejection", "Gesprächsablauf & Fragen"),
    ("das Telefoninterview, die Telefoninterviews", "Noun", "B2", "телефонное интервью", "telephone interview", "Gesprächsablauf & Fragen"),
    ("das Videointerview, die Videointerviews", "Noun", "B2", "видеоинтервью", "video interview", "Gesprächsablauf & Fragen"),
    ("das Online-Gespräch, die Gespräche", "Noun", "B1", "онлайн-беседа", "online talk", "Gesprächsablauf & Fragen"),
    ("der Lebenslauf-Check, die Checks", "Noun", "B2", "проверка резюме", "CV check", "Gesprächsablauf & Fragen"),
    ("antwortbereit", "Adjective", "B2", "готовый ответить", "ready to answer", "Gesprächsablauf & Fragen"),
    ("die Frage-Antwort-Runde, die Runden", "Noun", "B2", "сессия вопросов и ответов", "Q&A session", "Gesprächsablauf & Fragen"),

    # Category 3: Stärken & Kompetenzen (201-300)
    ("die Stärke, die Stärken", "Noun", "B1", "сильная сторона / достоинство", "strength", "Stärken & Kompetenzen"),
    ("die Schwäche, die Schwächen", "Noun", "B1", "слабая сторона / недостаток", "weakness", "Stärken & Kompetenzen"),
    ("die Kompetenz, die Kompetenzen", "Noun", "B2", "компетенция / сфера ведения", "competence", "Stärken & Kompetenzen"),
    ("die Schlüsselqualifikation, die Schlüsselqualifikationen", "Noun", "B2", "ключевая квалификация", "key qualification", "Stärken & Kompetenzen"),
    ("teamfähig", "Adjective", "B1", "способный работать в команде", "capable of working in a team", "Stärken & Kompetenzen"),
    ("die Teamfähigkeit, (nur Sg.)", "Noun", "B1", "умение работать в команде", "ability to work in a team", "Stärken & Kompetenzen"),
    ("flexibel", "Adjective", "B1", "гибкий / быстро приспосабливающийся", "flexible", "Stärken & Kompetenzen"),
    ("die Flexibilität, (nur Sg.)", "Noun", "B1", "гибкость", "flexibility", "Stärken & Kompetenzen"),
    ("belastbar", "Adjective", "B2", "стрессоустойчивый", "resilient / under pressure", "Stärken & Kompetenzen"),
    ("die Belastbarkeit, (nur Sg.)", "Noun", "B2", "стрессоустойчивость / выносливость", "resilience / ability to work under pressure", "Stärken & Kompetenzen"),
    ("zuverlässig", "Adjective", "B1", "надежный", "reliable", "Stärken & Kompetenzen"),
    ("die Zuverlässigkeit, (nur Sg.)", "Noun", "B1", "надежность", "reliability", "Stärken & Kompetenzen"),
    ("selbstständig", "Adjective", "B1", "самостоятельный", "independent", "Stärken & Kompetenzen"),
    ("die Selbstständigkeit, (nur Sg.)", "Noun", "B1", "самостоятельность", "independence", "Stärken & Kompetenzen"),
    ("engagiert", "Adjective", "B1", "активный / преданный делу", "committed / engaged", "Stärken & Kompetenzen"),
    ("das Engagement, die Engagements", "Noun", "B2", "вовлеченность / активность", "commitment / engagement", "Stärken & Kompetenzen"),
    ("motiviert", "Adjective", "B1", "мотивированный", "motivated", "Stärken & Kompetenzen"),
    ("die Motivation, die Motivationen", "Noun", "B1", "мотивация", "motivation", "Stärken & Kompetenzen"),
    ("kommunikativ", "Adjective", "B1", "общительный / коммуникабельный", "communicative", "Stärken & Kompetenzen"),
    ("die Kommunikationsfähigkeit, (nur Sg.)", "Noun", "B2", "коммуникабельность", "communication skills", "Stärken & Kompetenzen"),
    ("zielstrebig", "Adjective", "B2", "целеустремленный", "purposeful / goal-oriented", "Stärken & Kompetenzen"),
    ("die Zielstrebigkeit, (nur Sg.)", "Noun", "B2", "целеустремленность", "purposefulness / determination", "Stärken & Kompetenzen"),
    ("kreativ", "Adjective", "B1", "творческий / креативный", "creative", "Stärken & Kompetenzen"),
    ("die Kreativität, (nur Sg.)", "Noun", "B1", "креативность", "creativity", "Stärken & Kompetenzen"),
    ("lernbereit", "Adjective", "B2", "готовый учиться", "willing to learn", "Stärken & Kompetenzen"),
    ("die Lernbereitschaft, (nur Sg.)", "Noun", "B2", "готовность к обучению", "willingness to learn", "Stärken & Kompetenzen"),
    ("anpassungsfähig", "Adjective", "B2", "способный адаптироваться", "adaptable", "Stärken & Kompetenzen"),
    ("die Anpassungsfähigkeit, (nur Sg.)", "Noun", "B2", "адаптируемость", "adaptability", "Stärken & Kompetenzen"),
    ("verantwortungsbewusst", "Adjective", "B2", "ответственный", "responsible", "Stärken & Kompetenzen"),
    ("das Verantwortungsbewusstsein, (nur Sg.)", "Noun", "B2", "чувство ответственности", "sense of responsibility", "Stärken & Kompetenzen"),
    ("organisiert", "Adjective", "B1", "организованный", "organized", "Stärken & Kompetenzen"),
    ("das Organisationstalent, die Organisationstalente", "Noun", "B2", "организаторские способности", "organizational talent", "Stärken & Kompetenzen"),
    ("lösungsorientiert", "Adjective", "B2", "нацеленный на решение", "solution-oriented", "Stärken & Kompetenzen"),
    ("das Problemlösungsverhalten, (nur Sg.)", "Noun", "B2", "подход к решению проблем", "problem-solving behavior", "Stärken & Kompetenzen"),
    ("kundenorientiert", "Adjective", "B2", "клиентоориентированный", "customer-oriented", "Stärken & Kompetenzen"),
    ("die Kundenorientierung, (nur Sg.)", "Noun", "B2", "ориентированность на клиента", "customer orientation", "Stärken & Kompetenzen"),
    ("analytisch", "Adjective", "B2", "аналитический", "analytical", "Stärken & Kompetenzen"),
    ("das analytische Denken, (nur Sg.)", "Noun", "B2", "аналитическое мышление", "analytical thinking", "Stärken & Kompetenzen"),
    ("strukturiert", "Adjective", "B2", "структурированный / систематический", "structured", "Stärken & Kompetenzen"),
    ("gewissenhaft", "Adjective", "B2", "добросовестный / тщательный", "conscientious", "Stärken & Kompetenzen"),
    ("die Gewissenhaftigkeit, (nur Sg.)", "Noun", "B2", "добросовестность / пунктуальность", "conscientiousness", "Stärken & Kompetenzen"),
    ("ehrgeizig", "Adjective", "B2", "честолюбивый / амбициозный", "ambitious", "Stärken & Kompetenzen"),
    ("der Ehrgeiz, (nur Sg.)", "Noun", "B2", "честолюбие / амбиции", "ambition", "Stärken & Kompetenzen"),
    ("durchsetzungsstark", "Adjective", "B2", "настойчивый / умеющий добиваться своего", "assertive", "Stärken & Kompetenzen"),
    ("die Durchsetzungsfähigkeit, (nur Sg.)", "Noun", "B2", "способность добиваться своей цели", "assertiveness", "Stärken & Kompetenzen"),
    ("kritikfähig", "Adjective", "B2", "способный воспринимать критику", "capable of taking criticism", "Stärken & Kompetenzen"),
    ("die Kritikfähigkeit, (nur Sg.)", "Noun", "B2", "восприимчивость к критике", "ability to take criticism", "Stärken & Kompetenzen"),
    ("stressresistent", "Adjective", "B2", "устойчивый к стрессу", "stress resistant", "Stärken & Kompetenzen"),
    ("die Stressresistenz, (nur Sg.)", "Noun", "B2", "устойчивость к нагрузкам", "stress resistance", "Stärken & Kompetenzen"),
    ("loyal", "Adjective", "B2", "верный / лояльный", "loyal", "Stärken & Kompetenzen"),
    ("die Loyalität, (nur Sg.)", "Noun", "B2", "верность / преданность", "loyalty", "Stärken & Kompetenzen"),
    ("geduldig", "Adjective", "B1", "терпеливый", "patient", "Stärken & Kompetenzen"),
    ("die Geduld, (nur Sg.)", "Noun", "B1", "терпение", "patience", "Stärken & Kompetenzen"),
    ("initiativ", "Adjective", "B2", "инициативный", "initiative", "Stärken & Kompetenzen"),
    ("die Eigeninitiative, die Eigeninitiativen", "Noun", "B2", "собственная инициатива", "personal initiative", "Stärken & Kompetenzen"),
    ("die Überzeugungskraft, (nur Sg.)", "Noun", "B2", "дар убеждения", "persuasiveness", "Stärken & Kompetenzen"),
    ("redegewandt", "Adjective", "B2", "красноречивый", "eloquent", "Stärken & Kompetenzen"),
    ("die Redegewandtheit, (nur Sg.)", "Noun", "B2", "красноречие / ораторский дар", "eloquence", "Stärken & Kompetenzen"),
    ("freundlich", "Adjective", "B1", "дружелюбный", "friendly", "Stärken & Kompetenzen"),
    ("die Freundlichkeit, (nur Sg.)", "Noun", "B1", "дружелюбие / любезность", "friendliness", "Stärken & Kompetenzen"),
    ("höflich", "Adjective", "B1", "вежливый", "polite", "Stärken & Kompetenzen"),
    ("die Höflichkeit, (nur Sg.)", "Noun", "B1", "вежливость", "politeness", "Stärken & Kompetenzen"),
    ("hilfsbereit", "Adjective", "B1", "готовый помочь", "helpful", "Stärken & Kompetenzen"),
    ("die Hilfsbereitschaft, (nur Sg.)", "Noun", "B1", "готовность прийти на помощь", "helpfulness", "Stärken & Kompetenzen"),
    ("diszipliniert", "Adjective", "B2", "дисциплинированный", "disciplined", "Stärken & Kompetenzen"),
    ("die Disziplin, (nur Sg.)", "Noun", "B1", "дисциплина", "discipline", "Stärken & Kompetenzen"),
    ("sorgfältig", "Adjective", "B2", "тщательный / аккуратный", "careful / diligent", "Stärken & Kompetenzen"),
    ("die Sorgfalt, (nur Sg.)", "Noun", "B2", "тщательность / аккуратность", "carefulness / diligence", "Stärken & Kompetenzen"),
    ("die Arbeitsweise, die Arbeitsweisen", "Noun", "B2", "стиль / метод работы", "working style", "Stärken & Kompetenzen"),
    ("selbstbewusst", "Adjective", "B1", "уверенный в себе", "self-confident", "Stärken & Kompetenzen"),
    ("das Selbstbewusstsein, (nur Sg.)", "Noun", "B1", "уверенность в себе", "self-confidence", "Stärken & Kompetenzen"),
    ("kompromissbereit", "Adjective", "B2", "готовый к компромиссу", "ready to compromise", "Stärken & Kompetenzen"),
    ("die Kompromissbereitschaft, (nur Sg.)", "Noun", "B2", "склонность к согласию", "readiness to compromise", "Stärken & Kompetenzen"),
    ("diplomatisch", "Adjective", "B2", "дипломатичный", "diplomatic", "Stärken & Kompetenzen"),
    ("das Diplomatiegespür, (nur Sg.)", "Noun", "B2", "дипломатический такт", "sense of diplomacy", "Stärken & Kompetenzen"),
    ("motivieren", "Verb", "B1", "мотивировать", "to motivate", "Stärken & Kompetenzen"),
    ("leiten", "Verb", "B1", "руководить / вести", "to lead", "Stärken & Kompetenzen"),
    ("führen", "Verb", "B1", "управлять / вести за собой", "to guide / lead", "Stärken & Kompetenzen"),
    ("die Führungskompetenz, die Kompetenzen", "Noun", "B2", "лидерские качества", "leadership competence", "Stärken & Kompetenzen"),
    ("koordinieren", "Verb", "B2", "координировать", "to coordinate", "Stärken & Kompetenzen"),
    ("die Kooperationsfähigkeit, (nur Sg.)", "Noun", "B2", "способность к сотрудничеству", "ability to cooperate", "Stärken & Kompetenzen"),
    ("das Team, die Teams", "Noun", "B1", "команда / коллектив", "team", "Stärken & Kompetenzen"),
    ("der Teamgeist, (nur Sg.)", "Noun", "B1", "командный дух", "team spirit", "Stärken & Kompetenzen"),
    ("unterstützen", "Verb", "B1", "поддерживать / помогать", "to support", "Stärken & Kompetenzen"),
    ("die Unterstützung, die Unterstützungen", "Noun", "B1", "поддержка", "support", "Stärken & Kompetenzen"),
    ("bewältigen", "Verb", "B2", "справляться (с задачей)", "to master / cope with", "Stärken & Kompetenzen"),
    ("die Herausforderung, die Herausforderungen", "Noun", "B1", "вызов / сложная задача", "challenge", "Stärken & Kompetenzen"),
    ("lösen", "Verb", "B1", "решать / разрешать (проблему)", "to solve", "Stärken & Kompetenzen"),
    ("das Problem, die Probleme", "Noun", "B1", "проблема", "problem", "Stärken & Kompetenzen"),
    ("der Erfolg, die Erfolge", "Noun", "B1", "успех", "success", "Stärken & Kompetenzen"),
    ("erfolgreich", "Adjective", "B1", "успешный", "successful", "Stärken & Kompetenzen"),
    ("scheitern", "Verb", "B2", "потерпеть неудачу", "to fail", "Stärken & Kompetenzen"),
    ("der Misserfolg, die Misserfolge", "Noun", "B2", "неудача / фиаско", "failure", "Stärken & Kompetenzen"),
    ("die Erfahrung, die Erfahrungen", "Noun", "B1", "опыт", "experience", "Stärken & Kompetenzen"),
    ("erfahren", "Adjective", "B2", "опытный / знающий", "experienced", "Stärken & Kompetenzen"),
    ("lösungsorientiert", "Adjective", "B2", "нацеленный на решение", "solution-oriented", "Stärken & Kompetenzen"),
    ("das Multitasking, (nur Sg.)", "Noun", "B2", "многозадачность", "multitasking", "Stärken & Kompetenzen"),
    ("verhandlungsstark", "Adjective", "B2", "успешный в переговорах", "strong in negotiations", "Stärken & Kompetenzen"),
    ("das Durchsetzungsvermögen, (nur Sg.)", "Noun", "B2", "пробивные способности / упорство", "assertive power", "Stärken & Kompetenzen"),

    # Category 4: Arbeitsbedingungen & Gehalt (301-400)
    ("das Gehalt, die Gehälter", "Noun", "B1", "оклад / заработная плата служащего", "salary", "Arbeitsbedingungen & Gehalt"),
    ("der Lohn, die Löhne", "Noun", "B1", "сдельная заработная плата", "wage", "Arbeitsbedingungen & Gehalt"),
    ("die Gehaltsvorstellung, die Gehaltsvorstellungen", "Noun", "B2", "желаемый уровень зарплаты", "salary expectation", "Arbeitsbedingungen & Gehalt"),
    ("das Bruttogehalt, die Gehälter", "Noun", "B2", "грязная заработная плата (до вычетов)", "gross salary", "Arbeitsbedingungen & Gehalt"),
    ("das Nettogehalt, die Gehälter", "Noun", "B2", "чистая заработная плата (на руки)", "net salary", "Arbeitsbedingungen & Gehalt"),
    ("verhandeln", "Verb", "B2", "вести переговоры / договариваться", "to negotiate", "Arbeitsbedingungen & Gehalt"),
    ("die Gehaltsverhandlung, die Gehaltsverhandlungen", "Noun", "B2", "переговоры о зарплате", "salary negotiation", "Arbeitsbedingungen & Gehalt"),
    ("der Tarifvertrag, die Tarifverträge", "Noun", "B2", "тарифное соглашение / коллективный договор", "collective agreement", "Arbeitsbedingungen & Gehalt"),
    ("der Mindestlohn, die Mindestlöhne", "Noun", "B2", "минимальный размер оплаты труда", "minimum wage", "Arbeitsbedingungen & Gehalt"),
    ("das Einstiegsgehalt, die Einstiegsgehälter", "Noun", "B2", "начальная зарплата", "starting salary", "Arbeitsbedingungen & Gehalt"),
    ("die Zulage, die Zulagen", "Noun", "B2", "доплата / надбавка", "allowance / bonus", "Arbeitsbedingungen & Gehalt"),
    ("der Bonus, die Bonusse", "Noun", "B2", "бонус / премия", "bonus", "Arbeitsbedingungen & Gehalt"),
    ("das Weihnachtsgeld, (nur Sg.)", "Noun", "B1", "рождественская премия (13-я зарплата)", "Christmas bonus", "Arbeitsbedingungen & Gehalt"),
    ("das Urlaubsgeld, die Urlaubsgelder", "Noun", "B1", "отпускные / премия к отпуску", "holiday bonus", "Arbeitsbedingungen & Gehalt"),
    ("die Sonderzahlung, die Sonderzahlungen", "Noun", "B2", "единовременная выплата", "special payment", "Arbeitsbedingungen & Gehalt"),
    ("die betriebliche Altersvorsorge, die Altersvorsorgen", "Noun", "B2", "производственное пенсионное обеспечение", "company pension scheme", "Arbeitsbedingungen & Gehalt"),
    ("der Arbeitgeberanteil, die Arbeitgeberanteile", "Noun", "B2", "взнос работодателя (в соцстрах)", "employer share", "Arbeitsbedingungen & Gehalt"),
    ("der Arbeitnehmeranteil, die Arbeitnehmeranteile", "Noun", "B2", "взнос работника (в соцстрах)", "employee share", "Arbeitsbedingungen & Gehalt"),
    ("die Sozialabgaben, (nur Pl.)", "Noun", "B2", "социальные отчисления", "social security contributions", "Arbeitsbedingungen & Gehalt"),
    ("die Arbeitszeit, die Arbeitszeiten", "Noun", "B1", "рабочее время", "working hours", "Arbeitsbedingungen & Gehalt"),
    ("die Gleitzeit, (nur Sg.)", "Noun", "B2", "скользящий / гибкий график", "flexible working hours", "Arbeitsbedingungen & Gehalt"),
    ("die Kernarbeitszeit, die Kernarbeitszeiten", "Noun", "B2", "фиксированные часы присутствия", "core working hours", "Arbeitsbedingungen & Gehalt"),
    ("die Vollzeit, (nur Sg.)", "Noun", "B1", "полная занятость", "full-time", "Arbeitsbedingungen & Gehalt"),
    ("die Teilzeit, (nur Sg.)", "Noun", "B1", "неполная занятость", "part-time", "Arbeitsbedingungen & Gehalt"),
    ("die Überstunden, (nur Pl.)", "Noun", "B1", "сверхурочные часы", "overtime", "Arbeitsbedingungen & Gehalt"),
    ("abfeiern", "Verb", "B2", "отрабатывать / брать отгул за переработку", "to take time off in lieu of overtime", "Arbeitsbedingungen & Gehalt"),
    ("das Zeitkonto, die Zeitkonten", "Noun", "B2", "учет рабочего времени (учетный лист)", "time account", "Arbeitsbedingungen & Gehalt"),
    ("die Schichtarbeit, (nur Sg.)", "Noun", "B2", "работа по сменам", "shift work", "Arbeitsbedingungen & Gehalt"),
    ("das Homeoffice, die Homeoffices", "Noun", "B1", "работа на дому / удаленка", "home office", "Arbeitsbedingungen & Gehalt"),
    ("das mobile Arbeiten, (nur Sg.)", "Noun", "B2", "удаленная мобильная работа", "mobile working", "Arbeitsbedingungen & Gehalt"),
    ("die Arbeitsbedingungen, (nur Pl.)", "Noun", "B1", "условия труда", "working conditions", "Arbeitsbedingungen & Gehalt"),
    ("der Arbeitsplatz, die Arbeitsplätze", "Noun", "B1", "рабочее место", "workplace", "Arbeitsbedingungen & Gehalt"),
    ("die Ausstattung, die Ausstattungen", "Noun", "B2", "оборудование / оснащение", "equipment", "Arbeitsbedingungen & Gehalt"),
    ("der Dienstwagen, die Dienstwagen", "Noun", "B2", "служебный автомобиль", "company car", "Arbeitsbedingungen & Gehalt"),
    ("das Diensthandy, die Diensthandys", "Noun", "B2", "служебный мобильный телефон", "company phone", "Arbeitsbedingungen & Gehalt"),
    ("das Ticket, die Tickets", "Noun", "B1", "билет / проездной", "ticket", "Arbeitsbedingungen & Gehalt"),
    ("der Fahrtkostenzuschuss, die Zuschüsse", "Noun", "B2", "компенсация расходов на проезд", "travel allowance", "Arbeitsbedingungen & Gehalt"),
    ("die Verpflegung, (nur Sg.)", "Noun", "B2", "питание / продовольствие", "catering / meals", "Arbeitsbedingungen & Gehalt"),
    ("die Kantine, die Kantinen", "Noun", "B1", "столовая (на предприятии)", "canteen", "Arbeitsbedingungen & Gehalt"),
    ("der Urlaub, die Urlaube", "Noun", "B1", "отпуск", "vacation / holiday", "Arbeitsbedingungen & Gehalt"),
    ("der Urlaubsanspruch, die Urlaubsansprüche", "Noun", "B2", "право на отпуск / количество дней отпуска", "vacation entitlement", "Arbeitsbedingungen & Gehalt"),
    ("der Urlaubstag, die Urlaubstage", "Noun", "B1", "день отпуска", "vacation day", "Arbeitsbedingungen & Gehalt"),
    ("der Sonderurlaub, die Sonderurlaube", "Noun", "B2", "дополнительный отпуск (по особым обстоятельствам)", "special leave", "Arbeitsbedingungen & Gehalt"),
    ("die Elternzeit, die Elternzeiten", "Noun", "B2", "отпуск по уходу за ребенком", "parental leave", "Arbeitsbedingungen & Gehalt"),
    ("der Mutterschutz, (nur Sg.)", "Noun", "B2", "отпуск по беременности и родам (охрана материнства)", "maternity protection", "Arbeitsbedingungen & Gehalt"),
    ("die Krankschreibung, die Krankschreibungen", "Noun", "B1", "больничный лист", "sick certificate", "Arbeitsbedingungen & Gehalt"),
    ("der Krankheitsfall, die Krankheitsfälle", "Noun", "B2", "случай болезни / недомогание", "case of illness", "Arbeitsbedingungen & Gehalt"),
    ("die Lohnfortzahlung, die Lohnfortzahlungen", "Noun", "B2", "сохранение зарплаты во время болезни", "continued payment of wages", "Arbeitsbedingungen & Gehalt"),
    ("die Arbeitsunfähigkeit, (nur Sg.)", "Noun", "B2", "нетрудоспособность", "incapacity for work", "Arbeitsbedingungen & Gehalt"),
    ("der Arbeitsvertrag, die Arbeitsverträge", "Noun", "B1", "трудовой договор", "employment contract", "Arbeitsbedingungen & Gehalt"),
    ("die Probezeit, die Probezeiten", "Noun", "B1", "испытательный срок", "probationary period", "Arbeitsbedingungen & Gehalt"),
    ("die Kündigung, die Kündigungen", "Noun", "B2", "увольнение", "termination / notice", "Arbeitsbedingungen & Gehalt"),
    ("kündigen", "Verb", "B1", "увольняться / расторгать договор", "to resign / terminate", "Arbeitsbedingungen & Gehalt"),
    ("die Kündigungsfrist, die Kündigungsfristen", "Noun", "B2", "срок уведомления об увольнении", "notice period", "Arbeitsbedingungen & Gehalt"),
    ("der Kündigungsschutz, (nur Sg.)", "Noun", "B2", "защита от необоснованного увольнения", "protection against dismissal", "Arbeitsbedingungen & Gehalt"),
    ("die Abfindung, die Abfindungen", "Noun", "B2", "выходное пособие", "severance pay", "Arbeitsbedingungen & Gehalt"),
    ("das Aufhebungsabkommen, die Aufhebungsabkommen", "Noun", "B2", "соглашение о расторжении договора", "termination agreement", "Arbeitsbedingungen & Gehalt"),
    ("der Betriebsrat, die Betriebsräte", "Noun", "B2", "производственный совет (профком)", "works council", "Arbeitsbedingungen & Gehalt"),
    ("die Gewerkschaft, die Gewerkschaften", "Noun", "B2", "профсоюз", "trade union", "Arbeitsbedingungen & Gehalt"),
    ("die Betriebsvereinbarung, die Betriebsvereinbarungen", "Noun", "B2", "коллективное соглашение на предприятии", "company agreement", "Arbeitsbedingungen & Gehalt"),
    ("der Arbeitsschutz, (nur Sg.)", "Noun", "B2", "охрана труда", "occupational safety", "Arbeitsbedingungen & Gehalt"),
    ("die Unfallversicherung, die Unfallversicherungen", "Noun", "B2", "страхование от несчастных случаев", "accident insurance", "Arbeitsbedingungen & Gehalt"),
    ("die Rentenversicherung, die Rentenversicherungen", "Noun", "B2", "пенсионное страхование", "pension insurance", "Arbeitsbedingungen & Gehalt"),
    ("die Krankenversicherung, die Krankenversicherungen", "Noun", "B1", "медицинское страхование", "health insurance", "Arbeitsbedingungen & Gehalt"),
    ("die Arbeitslosenversicherung, die Arbeitslosenversicherungen", "Noun", "B2", "страхование на случай безработицы", "unemployment insurance", "Arbeitsbedingungen & Gehalt"),
    ("die Pflegeversicherung, die Pflegeversicherungen", "Noun", "B2", "страхование на случай потребности в уходе", "nursing care insurance", "Arbeitsbedingungen & Gehalt"),
    ("die Lohnsteuer, die Lohnsteuern", "Noun", "B2", "подоходный налог с заработной платы", "income tax", "Arbeitsbedingungen & Gehalt"),
    ("die Steuerklasse, die Steuerklassen", "Noun", "B2", "налоговый класс / налоговая группа", "tax bracket", "Arbeitsbedingungen & Gehalt"),
    ("der Nettoverdienst, die Nettoverdienste", "Noun", "B2", "чистый заработок", "net earnings", "Arbeitsbedingungen & Gehalt"),
    ("der Bruttoverdienst, die Bruttoverdienste", "Noun", "B2", "заработок до налогообложения", "gross earnings", "Arbeitsbedingungen & Gehalt"),
    ("das Einkommen, die Einkommen", "Noun", "B1", "доход", "income", "Arbeitsbedingungen & Gehalt"),
    ("die Einkunft, die Einkünfte", "Noun", "B2", "поступление / доход (источник дохода)", "revenue / earnings", "Arbeitsbedingungen & Gehalt"),
    ("die Beschäftigung, die Beschäftigungen", "Noun", "B1", "занятость / деятельность", "employment", "Arbeitsbedingungen & Gehalt"),
    ("das Beschäftigungsverhältnis, die Beschäftigungsverhältnisse", "Noun", "B2", "трудовые отношения", "employment relationship", "Arbeitsbedingungen & Gehalt"),
    ("die Zeitarbeit, (nur Sg.)", "Noun", "B2", "временная работа (через агентство)", "temporary work", "Arbeitsbedingungen & Gehalt"),
    ("der Minijob, die Minijobs", "Noun", "B1", "работа с минимальной оплатой (мини-джоб)", "minijob", "Arbeitsbedingungen & Gehalt"),
    ("die Gleitzeitregelung, die Gleitzeitregelungen", "Noun", "B2", "правила гибкого времени", "flexitime regulation", "Arbeitsbedingungen & Gehalt"),
    ("die Zeiterfassung, die Zeiterfassungen", "Noun", "B2", "учет рабочего времени", "time recording", "Arbeitsbedingungen & Gehalt"),
    ("die Stechuhr, die Stechuhren", "Noun", "B2", "контрольные часы (электронный пропуск)", "time clock", "Arbeitsbedingungen & Gehalt"),
    ("das Überstundenkonto, die Konten", "Noun", "B2", "баланс сверхурочных часов", "overtime account", "Arbeitsbedingungen & Gehalt"),
    ("auszahlen", "Verb", "B2", "выплачивать", "to pay out", "Arbeitsbedingungen & Gehalt"),
    ("vergüten", "Verb", "B2", "компенсировать / вознаграждать", "to remunerate", "Arbeitsbedingungen & Gehalt"),
    ("die Vergütung, die Vergütungen", "Noun", "B2", "вознаграждение / плата", "remuneration", "Arbeitsbedingungen & Gehalt"),
    ("das Entgelt, die Entgelte", "Noun", "B2", "компенсация / плата", "payment / fee", "Arbeitsbedingungen & Gehalt"),
    ("die Gehaltserhöhung, die Gehaltserhöhungen", "Noun", "B2", "повышение зарплаты", "salary increase", "Arbeitsbedingungen & Gehalt"),
    ("die Gehaltsstufe, die Gehaltsstufen", "Noun", "B2", "ступень оклада / тарифный разряд", "salary grade", "Arbeitsbedingungen & Gehalt"),
    ("die Gehaltsstabelle, die Gehaltstabellen", "Noun", "B2", "тарифная сетка", "salary scale", "Arbeitsbedingungen & Gehalt"),
    ("der Gehaltsnachweis, die Gehaltsnachweise", "Noun", "B2", "справка о доходах / зарплатный листок", "proof of salary", "Arbeitsbedingungen & Gehalt"),
    ("die Abrechnung, die Abrechnungen", "Noun", "B1", "расчет / расчетный листок", "payslip / billing", "Arbeitsbedingungen & Gehalt"),
    ("der Gehaltszettel, die Gehaltszettel", "Noun", "B1", "расчетный листок", "payslip", "Arbeitsbedingungen & Gehalt"),
    ("die Sozialversicherung, die Sozialversicherungen", "Noun", "B2", "социальное страхование", "social insurance", "Arbeitsbedingungen & Gehalt"),
    ("die Abgabe, die Abgaben", "Noun", "B2", "пошлина / сбор", "tax / levy", "Arbeitsbedingungen & Gehalt"),
    ("der Abzug, die Abzüge", "Noun", "B2", "вычет / удержание", "deduction", "Arbeitsbedingungen & Gehalt"),
    ("die Steuer, die Steuern", "Noun", "B1", "налог", "tax", "Arbeitsbedingungen & Gehalt"),
    ("das Nettoeinkommen, die Einkommen", "Noun", "B2", "чистый доход", "net income", "Arbeitsbedingungen & Gehalt"),
    ("das Bruttoeinkommen, die Einkommen", "Noun", "B2", "доход до вычета налогов", "gross income", "Arbeitsbedingungen & Gehalt"),
    ("die Zusatzleistung, die Zusatzleistungen", "Noun", "B2", "дополнительная выгода / бенефит", "additional benefit", "Arbeitsbedingungen & Gehalt"),
    ("die Vergünstigung, die Vergünstigungen", "Noun", "B2", "льгота / скидка", "discount / benefit", "Arbeitsbedingungen & Gehalt"),

    # Category 5: Karriere & Weiterbildung (401-500)
    ("die Karriere, die Karrieren", "Noun", "B1", "карьера", "career", "Karriere & Weiterbildung"),
    ("die Laufbahn, die Laufbahnen", "Noun", "B2", "профессиональное поприще / карьера", "career path", "Karriere & Weiterbildung"),
    ("die Weiterbildung, die Weiterbildungen", "Noun", "B1", "повышение квалификации / доп. образование", "further education / training", "Karriere & Weiterbildung"),
    ("die Fortbildung, die Fortbildungen", "Noun", "B2", "профессиональное усовершенствование", "advanced training", "Karriere & Weiterbildung"),
    ("das Seminar, die Seminare", "Noun", "B1", "семинар", "seminar", "Karriere & Weiterbildung"),
    ("die Schulung, die Schulungen", "Noun", "B1", "обучение / инструктаж / курсы", "training course", "Karriere & Weiterbildung"),
    ("der Workshop, die Workshops", "Noun", "B1", "воркшоп / практический семинар", "workshop", "Karriere & Weiterbildung"),
    ("die Qualifizierung, die Qualifizierungen", "Noun", "B2", "присвоение квалификации / обучение", "qualification", "Karriere & Weiterbildung"),
    ("sich qualifizieren", "Verb", "B2", "получать квалификацию / подходить", "to qualify", "Karriere & Weiterbildung"),
    ("die Fähigkeit, die Fähigkeiten", "Noun", "B1", "способность / умение / навык", "ability / skill", "Karriere & Weiterbildung"),
    ("erwerben", "Verb", "B2", "приобретать / овладевать (навыком)", "to acquire (skills)", "Karriere & Weiterbildung"),
    ("vertiefen", "Verb", "B2", "углублять (знания)", "to deepen", "Karriere & Weiterbildung"),
    ("die Vertiefung, die Vertiefungen", "Noun", "B2", "углубление / специализация", "deepening", "Karriere & Weiterbildung"),
    ("erweitern", "Verb", "B1", "расширять (кругозор/знания)", "to expand", "Karriere & Weiterbildung"),
    ("die Erweiterung, die Erweiterungen", "Noun", "B2", "расширение", "expansion", "Karriere & Weiterbildung"),
    ("der Aufstieg, die Aufstiege", "Noun", "B2", "продвижение по службе / подъем", "advancement / promotion", "Karriere & Weiterbildung"),
    ("befördern", "Verb", "B2", "продвигать по службе / повышать", "to promote", "Karriere & Weiterbildung"),
    ("die Beförderung, die Beförderungen", "Noun", "B2", "повышение в должности", "promotion", "Karriere & Weiterbildung"),
    ("die Führungskraft, die Führungskräfte", "Noun", "B2", "руководитель / менеджер", "executive / leader", "Karriere & Weiterbildung"),
    ("die Führungsposition, die Führungspositionen", "Noun", "B2", "руководящая должность", "leadership position", "Karriere & Weiterbildung"),
    ("die Verantwortung, (nur Sg.)", "Noun", "B1", "ответственность", "responsibility", "Karriere & Weiterbildung"),
    ("Verantwortung übernehmen", "Verb", "B1", "брать на себя ответственность", "to take responsibility", "Karriere & Weiterbildung"),
    ("das Ziel, die Ziele", "Noun", "B1", "цель", "goal", "Karriere & Weiterbildung"),
    ("die Zielvereinbarung, die Zielvereinbarungen", "Noun", "B2", "соглашение о целях", "target agreement", "Karriere & Weiterbildung"),
    ("das Mitarbeitergespräch, die Mitarbeitergespräche", "Noun", "B2", "беседа руководителя с сотрудником", "appraisal interview", "Karriere & Weiterbildung"),
    ("das Feedbackgespräch, die Feedbackgespräche", "Noun", "B2", "беседа для получения отзывов", "feedback talk", "Karriere & Weiterbildung"),
    ("die Entwicklung, die Entwicklungen", "Noun", "B1", "развитие", "development", "Karriere & Weiterbildung"),
    ("die Personalentwicklung, die Personalentwicklungen", "Noun", "B2", "развитие персонала", "personnel development", "Karriere & Weiterbildung"),
    ("das Potenzial, die Potenziale", "Noun", "B2", "потенциал", "potential", "Karriere & Weiterbildung"),
    ("das Talent, die Talente", "Noun", "B1", "талант / одаренность", "talent", "Karriere & Weiterbildung"),
    ("die Talentförderung, die Talentförderungen", "Noun", "B2", "поддержка талантов", "talent promotion", "Karriere & Weiterbildung"),
    ("der Mentor, die Mentoren", "Noun", "B2", "ментор / наставник", "mentor", "Karriere & Weiterbildung"),
    ("das Mentoring, die Mentorings", "Noun", "B2", "наставничество", "mentoring", "Karriere & Weiterbildung"),
    ("das Coaching, die Coachings", "Noun", "B2", "коучинг", "coaching", "Karriere & Weiterbildung"),
    ("der Coach, die Coaches", "Noun", "B1", "коуч / тренер", "coach", "Karriere & Weiterbildung"),
    ("der Aufstiegswunsch, die Aufstiegswünsche", "Noun", "B2", "стремление к карьерному росту", "desire for advancement", "Karriere & Weiterbildung"),
    ("der Karrierepfad, die Karrierepfade", "Noun", "B2", "траектория карьеры", "career path", "Karriere & Weiterbildung"),
    ("der Karriereschritt, die Karriereschritte", "Noun", "B2", "шаг в карьере", "career step", "Karriere & Weiterbildung"),
    ("der Karrierewechsel, die Karrierewechsel", "Noun", "B2", "смена сферы деятельности", "career change", "Karriere & Weiterbildung"),
    ("der Quereinstieg, die Quereinstiege", "Noun", "B2", "переход в другую сферу", "lateral entry", "Karriere & Weiterbildung"),
    ("der Quereinsteiger, die Quereinsteiger", "Noun", "B2", "человек, сменивший профессию", "lateral entrant", "Karriere & Weiterbildung"),
    ("die Umschulung, die Umschulungen", "Noun", "B2", "переквалификация", "retraining", "Karriere & Weiterbildung"),
    ("die berufliche Veränderung, die Veränderungen", "Noun", "B2", "профессиональные перемены", "professional change", "Karriere & Weiterbildung"),
    ("sich verändern", "Verb", "B1", "меняться / менять работу", "to change (career)", "Karriere & Weiterbildung"),
    ("die Herausforderung, die Herausforderungen", "Noun", "B1", "профессиональный вызов", "challenge", "Karriere & Weiterbildung"),
    ("die Perspektive, die Perspektiven", "Noun", "B1", "перспектива / возможность", "perspective", "Karriere & Weiterbildung"),
    ("die Aufstiegschance, die Aufstiegschancen", "Noun", "B2", "шанс на повышение", "chance of promotion", "Karriere & Weiterbildung"),
    ("die Aufstiegsmöglichkeit, die Aufstiegsmöglichkeiten", "Noun", "B2", "возможность продвижения", "promotion opportunity", "Karriere & Weiterbildung"),
    ("die Fachlaufbahn, die Fachlaufbahnen", "Noun", "B2", "профессиональный рост как специалиста", "specialist career", "Karriere & Weiterbildung"),
    ("die Führungslaufbahn, die Führungslaufbahnen", "Noun", "B2", "управленческая карьера", "management career", "Karriere & Weiterbildung"),
    ("die Auslandsentsendung, die Auslandsentsendungen", "Noun", "B2", "командировка за границу", "posting abroad", "Karriere & Weiterbildung"),
    ("das Auslandsprojekt, die Auslandsprojekte", "Noun", "B2", "международный проект", "foreign project", "Karriere & Weiterbildung"),
    ("die Sprachschulung, die Sprachschulungen", "Noun", "B1", "языковой тренинг / обучение", "language training", "Karriere & Weiterbildung"),
    ("der Zertifikatskurs, die Zertifikatskurse", "Noun", "B2", "сертификационный курс", "certificate course", "Karriere & Weiterbildung"),
    ("die Prüfung, die Prüfungen", "Noun", "B1", "экзамен / тест", "examination", "Karriere & Weiterbildung"),
    ("bestehen", "Verb", "B1", "сдавать (экзамен) / выдерживать", "to pass (an exam)", "Karriere & Weiterbildung"),
    ("das Zertifikat erhalten", "Verb", "B2", "получить сертификат", "to receive a certificate", "Karriere & Weiterbildung"),
    ("die Fachkompetenz, die Fachkompetenzen", "Noun", "B2", "профессиональная компетенция", "technical competence", "Karriere & Weiterbildung"),
    ("die Methodenkompetenz, die Methodenkompetenzen", "Noun", "B2", "методологическая компетенция", "methodological competence", "Karriere & Weiterbildung"),
    ("die Sozialkompetenz, die Sozialkompetenzen", "Noun", "B2", "социальные навыки / эмпатия", "social competence", "Karriere & Weiterbildung"),
    ("die Selbstkompetenz, (nur Sg.)", "Noun", "B2", "способность к самоорганизации", "self-competence", "Karriere & Weiterbildung"),
    ("die Schlüsselkompetenz, die Schlüsselkompetenzen", "Noun", "B2", "ключевая компетенция", "key competence", "Karriere & Weiterbildung"),
    ("das Fachwissen erweitern", "Verb", "B2", "расширять профессиональные знания", "to expand specialist knowledge", "Karriere & Weiterbildung"),
    ("die Fachliteratur, (nur Sg.)", "Noun", "B2", "специализированная литература", "specialist literature", "Karriere & Weiterbildung"),
    ("der Kongress, die Kongresse", "Noun", "B2", "съезд / конгресс", "congress", "Karriere & Weiterbildung"),
    ("die Tagung, die Tagungen", "Noun", "B2", "конференция / заседание", "conference", "Karriere & Weiterbildung"),
    ("die Messe, die Messen", "Noun", "B1", "ярмарка / выставка", "fair / exhibition", "Karriere & Weiterbildung"),
    ("der Austausch, (nur Sg.)", "Noun", "B1", "обмен опытом / мнениями", "exchange / discussion", "Karriere & Weiterbildung"),
    ("das Netzwerk, die Netzwerke", "Noun", "B2", "сеть контактов / нетворкинг", "network", "Karriere & Weiterbildung"),
    ("netzwerken", "Verb", "B2", "заниматься нетворкингом", "to network", "Karriere & Weiterbildung"),
    ("der Fachverband, die Fachverbände", "Noun", "B2", "профессиональная ассоциация", "professional association", "Karriere & Weiterbildung"),
    ("der Wissenstransfer, (nur Sg.)", "Noun", "B2", "передача знаний", "knowledge transfer", "Karriere & Weiterbildung"),
    ("die Einarbeitung, die Einarbeitungen", "Noun", "B2", "ввод в курс дела / адаптация", "onboarding / induction", "Karriere & Weiterbildung"),
    ("der Einarbeitungsplan, die Einarbeitungspläne", "Noun", "B2", "план адаптации нового сотрудника", "onboarding plan", "Karriere & Weiterbildung"),
    ("die Probezeit bestehen", "Verb", "B2", "пройти испытательный срок", "to pass the probationary period", "Karriere & Weiterbildung"),
    ("der Entwicklungsplan, die Entwicklungspläne", "Noun", "B2", "план индивидуального развития", "development plan", "Karriere & Weiterbildung"),
    ("das Karriereziel, die Karriereziele", "Noun", "B2", "карьерная цель", "career goal", "Karriere & Weiterbildung"),
    ("die Zielerreichung, (nur Sg.)", "Noun", "B2", "достижение поставленной цели", "goal achievement", "Karriere & Weiterbildung"),
    ("die Leistungsbeurteilung, die Leistungsbeurteilungen", "Noun", "B2", "оценка эффективности работы", "performance appraisal", "Karriere & Weiterbildung"),
    ("die Leistung, die Leistungen", "Noun", "B1", "производительность / результат", "performance", "Karriere & Weiterbildung"),
    ("leistungsstark", "Adjective", "B2", "продуктивный / эффективный", "high-performing", "Karriere & Weiterbildung"),
    ("der Leistungsträger, die Leistungsträger", "Noun", "B2", "ключевой сотрудник / опора коллектива", "key performer", "Karriere & Weiterbildung"),
    ("die Anerkennung, die Anerkennungen", "Noun", "B2", "признание / одобрение", "recognition", "Karriere & Weiterbildung"),
    ("loben", "Verb", "B1", "хвалить", "to praise", "Karriere & Weiterbildung"),
    ("das Lob, (nur Sg.)", "Noun", "B1", "похвала", "praise", "Karriere & Weiterbildung"),
    ("der Ansporn, (nur Sg.)", "Noun", "B2", "стимул / побуждение", "incentive", "Karriere & Weiterbildung"),
    ("die Arbeitszufriedenheit, (nur Sg.)", "Noun", "B2", "удовлетворенность работой", "job satisfaction", "Karriere & Weiterbildung"),
    ("das Betriebsklima, (nur Sg.)", "Noun", "B2", "климат в коллективе", "working atmosphere", "Karriere & Weiterbildung"),
    ("die Unternehmenskultur, die Unternehmenskulturen", "Noun", "B2", "корпоративная культура", "corporate culture", "Karriere & Weiterbildung"),
]
