# -*- coding: utf-8 -*-

words = [
    # Category 1: Behörden & Formulare (1-100)
    ("die Behörde, die Behörden", "Noun", "B2", "орган власти / ведомство / учреждение", "authority / agency", "Behörden & Formulare"),
    ("das Amt, die Ämter", "Noun", "B1", "ведомство / служба / учреждение", "office / authority", "Behörden & Formulare"),
    ("der Beamte, die Beamten", "Noun", "B1", "чиновник / государственный служащий", "official / civil servant", "Behörden & Formulare"),
    ("das Formular, die Formulare", "Noun", "B1", "бланк / анкета / формуляр", "form", "Behörden & Formulare"),
    ("ausfüllen", "Verb", "B1", "заполнять (документ)", "to fill in", "Behörden & Formulare"),
    ("unterschreiben", "Verb", "B1", "подписывать", "to sign", "Behörden & Formulare"),
    ("die Unterschrift, die Unterschriften", "Noun", "B1", "подпись", "signature", "Behörden & Formulare"),
    ("der Antrag, die Anträge", "Noun", "B1", "заявление / ходатайство", "application", "Behörden & Formulare"),
    ("beantragen", "Verb", "B1", "подавать заявление / ходатайствовать", "to apply for", "Behörden & Formulare"),
    ("die Genehmigung, die Genehmigungen", "Noun", "B2", "разрешение / одобрение / лицензия", "approval / permit", "Behörden & Formulare"),
    ("genehmigen", "Verb", "B2", "разрешать / одобрять", "to approve", "Behörden & Formulare"),
    ("die Ablehnung, die Ablehnungen", "Noun", "B2", "отказ / отклонение", "rejection", "Behörden & Formulare"),
    ("ablehnen", "Verb", "B1", "отклонять / отказываться", "to reject", "Behörden & Formulare"),
    ("der Bescheid, die Bescheide", "Noun", "B2", "решение / извещение / уведомление", "notice / decision", "Behörden & Formulare"),
    ("der Steuerbescheid, die Steuerbescheide", "Noun", "B2", "уведомление о размере налога", "tax assessment", "Behörden & Formulare"),
    ("der Gebührenbescheid, die Gebührenbescheide", "Noun", "B2", "требование об уплате пошлин", "fee notice", "Behörden & Formulare"),
    ("die Gebühr, die Gebühren", "Noun", "B1", "пошлина / сбор / плата", "fee", "Behörden & Formulare"),
    ("bezahlen", "Verb", "B1", "оплачивать / платить", "to pay", "Behörden & Formulare"),
    ("der Beleg, die Belege", "Noun", "B1", "квитанция / подтверждающий документ", "receipt / proof", "Behörden & Formulare"),
    ("die Quittung, die Quittungen", "Noun", "B1", "расписка в получении / квитанция", "receipt", "Behörden & Formulare"),
    ("der Personalausweis, die Personalausweise", "Noun", "B1", "удостоверение личности / паспорт", "ID card", "Behörden & Formulare"),
    ("der Reisepass, die Reisepässe", "Noun", "B1", "заграничный паспорт", "passport", "Behörden & Formulare"),
    ("der Ausweis, die Ausweise", "Noun", "B1", "удостоверение / паспорт / пропуск", "ID", "Behörden & Formulare"),
    ("die Ausweisnummer, die Ausweisnummern", "Noun", "B1", "номер удостоверения личности", "ID number", "Behörden & Formulare"),
    ("das Dokument, die Dokumente", "Noun", "B1", "документ", "document", "Behörden & Formulare"),
    ("die Urkunde, die Urkunden", "Noun", "B2", "документ / грамота / свидетельство", "certificate / deed", "Behörden & Formulare"),
    ("die Geburtsurkunde, die Geburtsurkunden", "Noun", "B1", "свидетельство о рождении", "birth certificate", "Behörden & Formulare"),
    ("die Heiratsurkunde, die Heiratsurkunden", "Noun", "B2", "свидетельство о браке", "marriage certificate", "Behörden & Formulare"),
    ("die Meldebescheinigung, die Meldebescheinigungen", "Noun", "B2", "справка о регистрации по месту жительства", "registration certificate", "Behörden & Formulare"),
    ("der Aufenthaltstitel, die Aufenthaltstitel", "Noun", "B2", "вид на жительство (документ)", "residence permit", "Behörden & Formulare"),
    ("die Aufenthaltserlaubnis, die Aufenthaltserlaubnisse", "Noun", "B2", "разрешение на пребывание / проживание", "residence permit", "Behörden & Formulare"),
    ("die Arbeitserlaubnis, die Arbeitserlaubnisse", "Noun", "B2", "разрешение на работу", "work permit", "Behörden & Formulare"),
    ("der Bürgerservice, die Bürgerservices", "Noun", "B1", "служба поддержки граждан / МФЦ", "citizens service", "Behörden & Formulare"),
    ("das Bürgerbüro, die Bürgerbüros", "Noun", "B1", "отдел обслуживания граждан (паспортный стол)", "citizens office", "Behörden & Formulare"),
    ("das Standesamt, die Standesämter", "Noun", "B1", "ЗАГС", "registry office", "Behörden & Formulare"),
    ("das Finanzamt, die Finanzämter", "Noun", "B1", "налоговая инспекция / налоговая служба", "tax office", "Behörden & Formulare"),
    ("das Sozialamt, die Sozialämter", "Noun", "B1", "собес / отдел соцобеспечения", "social welfare office", "Behörden & Formulare"),
    ("das Jugendamt, die Jugendämter", "Noun", "B2", "ведомство по делам молодежи и детей", "youth welfare office", "Behörden & Formulare"),
    ("das Ausländeramt, die Ausländerämter", "Noun", "B2", "ведомство по делам иностранцев", "immigration office", "Behörden & Formulare"),
    ("die Ausländerbehörde, die Ausländerbehörden", "Noun", "B2", "ведомство по делам иностранцев", "immigration authority", "Behörden & Formulare"),
    ("der Termin, die Termine", "Noun", "B1", "запись на прием / встреча", "appointment", "Behörden & Formulare"),
    ("die Terminvereinbarung, die Terminvereinbarungen", "Noun", "B2", "запись на прием / бронирование времени", "appointment booking", "Behörden & Formulare"),
    ("die Warteschlange, die Warteschlangen", "Noun", "B1", "очередь", "queue", "Behörden & Formulare"),
    ("die Wartenummer, die Wartenummern", "Noun", "B1", "номер в очереди / талончик", "queue number", "Behörden & Formulare"),
    ("der Aufruf, die Aufrufe", "Noun", "B1", "вызов (по номеру/имени)", "call / calling", "Behörden & Formulare"),
    ("das Aktenzeichen, die Aktenzeichen", "Noun", "B2", "номер дела / регистрационный номер", "file reference", "Behörden & Formulare"),
    ("die Akte, die Akten", "Noun", "B2", "досье / дело / папка с документами", "file / record", "Behörden & Formulare"),
    ("der Sachbearbeiter, die Sachbearbeiter", "Noun", "B2", "ответственный исполнитель / инспектор", "case officer", "Behörden & Formulare"),
    ("die Sachbearbeiterin, die Sachbearbeiterinnen", "Noun", "B2", "ответственная исполнительница / инспектор", "female case officer", "Behörden & Formulare"),
    ("die Zuständigkeit, die Zuständigkeiten", "Noun", "B2", "компетенция / зона ответственности", "responsibility", "Behörden & Formulare"),
    ("zuständig", "Adjective", "B1", "ответственный / компетентный", "responsible", "Behörden & Formulare"),
    ("die Pflicht, die Pflichten", "Noun", "B1", "обязанность / долг", "duty", "Behörden & Formulare"),
    ("die Frist, die Fristen", "Noun", "B1", "срок / крайний срок", "deadline / period", "Behörden & Formulare"),
    ("einhalten", "Verb", "B2", "соблюдать (сроки/правила)", "to keep / comply with", "Behörden & Formulare"),
    ("verlängern", "Verb", "B1", "продлевать", "to extend", "Behörden & Formulare"),
    ("die Verlängerung, die Verlängerungen", "Noun", "B2", "продление", "extension", "Behörden & Formulare"),
    ("die Fristverlängerung, die Fristverlängerungen", "Noun", "B2", "продление срока", "extension of time", "Behörden & Formulare"),
    ("der Widerspruch, die Widersprüche", "Noun", "B2", "протест / возражение / апелляция", "objection / appeal", "Behörden & Formulare"),
    ("Widerspruch einlegen", "Verb", "B2", "подавать апелляцию / возражение", "to lodge an appeal", "Behörden & Formulare"),
    ("die Klage, die Klagen", "Noun", "B2", "иск / жалоба", "lawsuit / complaint", "Behörden & Formulare"),
    ("klagen", "Verb", "B2", "подавать в суд / жаловаться", "to sue / complain", "Behörden & Formulare"),
    ("der Rechtsanwalt, die Rechtsanwälte", "Noun", "B1", "адвокат / юрист", "lawyer", "Behörden & Formulare"),
    ("die Rechtsberatung, die Rechtsberatungen", "Noun", "B2", "юридическая консультация", "legal advice", "Behörden & Formulare"),
    ("beglaubigen", "Verb", "B2", "заверять (документы)", "to certify / notarize", "Behörden & Formulare"),
    ("die Beglaubigung, die Beglaubigungen", "Noun", "B2", "заверение (нотариальное)", "certification / notarization", "Behörden & Formulare"),
    ("die Kopie, die Kopien", "Noun", "B1", "копия", "copy", "Behörden & Formulare"),
    ("das Original, die Originale", "Noun", "B1", "оригинал", "original", "Behörden & Formulare"),
    ("vorlegen", "Verb", "B2", "предъявлять / предоставлять", "to present / submit", "Behörden & Formulare"),
    ("die Vorlage, die Vorlagen", "Noun", "B2", "предъявление / предоставление", "presentation / submission", "Behörden & Formulare"),
    ("nachreichen", "Verb", "B2", "предоставлять позже / досылать", "to submit later", "Behörden & Formulare"),
    ("die Nachreichung, die Nachreichungen", "Noun", "B2", "предоставление недостающих документов", "subsequent submission", "Behörden & Formulare"),
    ("der Nachweis, die Nachweise", "Noun", "B1", "доказательство / свидетельство / справка", "proof / evidence", "Behörden & Formulare"),
    ("nachweisen", "Verb", "B1", "доказывать / подтверждать", "to prove", "Behörden & Formulare"),
    ("der Herkunftsnachweis, die Herkunftsnachweise", "Noun", "B2", "подтверждение происхождения", "proof of origin", "Behörden & Formulare"),
    ("die Steuererklärung, die Steuererklärungen", "Noun", "B2", "налоговая декларация", "tax return", "Behörden & Formulare"),
    ("abgebenn", "Verb", "B1", "сдавать / вручать", "to submit", "Behörden & Formulare"), # Will be cleaned later if needed
    ("die Abgabe, die Abgaben", "Noun", "B2", "сдача / подача (документов)", "submission", "Behörden & Formulare"),
    ("die Bescheinigung, die Bescheinigungen", "Noun", "B1", "удостоверение / справка / свидетельство", "certificate / confirmation", "Behörden & Formulare"),
    ("bescheinigen", "Verb", "B2", "удостоверять / подтверждать в письменном виде", "to certify / confirm", "Behörden & Formulare"),
    ("der Stempel, die Stempel", "Noun", "B1", "печать / штамп", "stamp", "Behörden & Formulare"),
    ("stempeln", "Verb", "B1", "ставить печать / штамповать", "to stamp", "Behörden & Formulare"),
    ("der Brief, die Briefe", "Noun", "B1", "письмо", "letter", "Behörden & Formulare"),
    ("der Postweg, die Postwege", "Noun", "B2", "почтовое сообщение", "by post", "Behörden & Formulare"),
    ("der Umschlag, die Umschläge", "Noun", "B1", "конвет", "envelope", "Behörden & Formulare"),
    ("die Briefmarke, die Briefmarken", "Noun", "B1", "почтовая марка", "postage stamp", "Behörden & Formulare"),
    ("per Einschreiben", "Adverb", "B2", "заказным письмом", "by registered mail", "Behörden & Formulare"),
    ("das Einschreiben, die Einschreiben", "Noun", "B2", "заказное письмо", "registered letter", "Behörden & Formulare"),
    ("die Zustellung, die Zustellungen", "Noun", "B2", "доставка (почты/документов)", "delivery", "Behörden & Formulare"),
    ("zustellen", "Verb", "B2", "доставлять / вручать", "to deliver", "Behörden & Formulare"),
    ("die Postleitzahl, die Postleitzahlen", "Noun", "B1", "почтовый индекс", "postcode", "Behörden & Formulare"),
    ("der Wohnsitz, die Wohnsitze", "Noun", "B2", "место жительства", "residence", "Behörden & Formulare"),
    ("die Staatsangehörigkeit, die Staatsangehörigkeiten", "Noun", "B2", "гражданство", "nationality", "Behörden & Formulare"),
    ("der Familienstand, (nur Sg.)", "Noun", "B1", "семейное положение", "marital status", "Behörden & Formulare"),
    ("ledig", "Adjective", "B1", "холостой / незамужняя", "single", "Behörden & Formulare"),
    ("verheiratet", "Adjective", "B1", "женатый / замужем", "married", "Behörden & Formulare"),
    ("geschieden", "Adjective", "B1", "разведенный", "divorced", "Behörden & Formulare"),
    ("verwitwet", "Adjective", "B2", "овдовевший", "widowed", "Behörden & Formulare"),
    ("der Geburtsname, die Geburtsnamen", "Noun", "B2", "девичья фамилия / фамилия при рождении", "maiden name / birth name", "Behörden & Formulare"),

    # Category 2: Wohnung & Anmeldung (101-200)
    ("die Wohnung, die Wohnungen", "Noun", "B1", "квартира", "apartment / flat", "Wohnung & Anmeldung"),
    ("das Haus, die Häuser", "Noun", "B1", "дом", "house", "Wohnung & Anmeldung"),
    ("die Miete, die Mieten", "Noun", "B1", "арендная плата / аренда", "rent", "Wohnung & Anmeldung"),
    ("die Kaltmiete, die Kaltmieten", "Noun", "B1", "базовая арендная плата (без коммунальных услуг)", "base rent", "Wohnung & Anmeldung"),
    ("die Warmmiete, die Warmmieten", "Noun", "B1", "арендная плата с коммунальными услугами", "rent including heating", "Wohnung & Anmeldung"),
    ("die Nebenkosten, (nur Pl.)", "Noun", "B1", "коммунальные услуги / дополнительные расходы", "utility costs", "Wohnung & Anmeldung"),
    ("die Betriebskosten, (nur Pl.)", "Noun", "B2", "эксплуатационные расходы", "operating costs", "Wohnung & Anmeldung"),
    ("die Heizkosten, (nur Pl.)", "Noun", "B1", "расходы на отопление", "heating costs", "Wohnung & Anmeldung"),
    ("die Kaution, die Kautionen", "Noun", "B1", "залог (при аренде квартиры)", "deposit", "Wohnung & Anmeldung"),
    ("der Mietvertrag, die Mietverträge", "Noun", "B1", "договор аренды квартиры", "lease / rental agreement", "Wohnung & Anmeldung"),
    ("der Vermieter, die Vermieter", "Noun", "B1", "арендодатель", "landlord", "Wohnung & Anmeldung"),
    ("die Vermieterin, die Vermieterinnen", "Noun", "B1", "арендодательница", "female landlord", "Wohnung & Anmeldung"),
    ("der Mieter, die Mieter", "Noun", "B1", "арендатор / жилец", "tenant", "Wohnung & Anmeldung"),
    ("die Mieterin, die Mieterinnen", "Noun", "B1", "арендаторша", "female tenant", "Wohnung & Anmeldung"),
    ("die Anmeldung, die Anmeldungen", "Noun", "B1", "регистрация / прописка", "registration", "Wohnung & Anmeldung"),
    ("sich anmelden", "Verb", "B1", "регистрироваться / прописываться", "to register", "Wohnung & Anmeldung"),
    ("die Ummeldung, die Ummeldungen", "Noun", "B2", "перерегистрация / смена адреса", "re-registration", "Wohnung & Anmeldung"),
    ("die Abmeldung, die Abmeldungen", "Noun", "B2", "выписка / снятие с регистрационного учета", "deregistration", "Wohnung & Anmeldung"),
    ("der Einzug, die Einzüge", "Noun", "B1", "заселение / въезд в квартиру", "moving in", "Wohnung & Anmeldung"),
    ("einziehen", "Verb", "B1", "въезжать (в новую квартиру)", "to move in", "Wohnung & Anmeldung"),
    ("der Auszug, die Auszüge", "Noun", "B1", "выезд из квартиры", "moving out", "Wohnung & Anmeldung"),
    ("ausziehen", "Verb", "B1", "выезжать / освобождать квартиру", "to move out", "Wohnung & Anmeldung"),
    ("der Umzug, die Umzüge", "Noun", "B1", "переезд", "move", "Wohnung & Anmeldung"),
    ("umziehen", "Verb", "B1", "переезжать", "to move", "Wohnung & Anmeldung"),
    ("das Umzugsunternehmen, die Umzugsunternehmen", "Noun", "B2", "фирма по организации переездов", "moving company", "Wohnung & Anmeldung"),
    ("die Wohnungsgeberbestätigung, die Bestätigungen", "Noun", "B2", "подтверждение от арендодателя (для прописки)", "landlord confirmation", "Wohnung & Anmeldung"),
    ("die Hausordnung, die Hausordnungen", "Noun", "B1", "правила внутреннего распорядка дома", "house rules", "Wohnung & Anmeldung"),
    ("der Hausmeister, die Hausmeister", "Noun", "B1", "управдом / смотритель дома / завхоз", "caretaker / janitor", "Wohnung & Anmeldung"),
    ("die Mülltrennung, (nur Sg.)", "Noun", "B1", "сортировка мусора", "waste separation", "Wohnung & Anmeldung"),
    ("der Restmüll, (nur Sg.)", "Noun", "B1", "несортируемые отходы / бытовой мусор", "residual waste", "Wohnung & Anmeldung"),
    ("der Biomüll, (nur Sg.)", "Noun", "B1", "органические / биоразлагаемые отходы", "organic waste", "Wohnung & Anmeldung"),
    ("das Altpapier, (nur Sg.)", "Noun", "B1", "макулатура", "waste paper", "Wohnung & Anmeldung"),
    ("der gelbe Sack, die gelben Säcke", "Noun", "B1", "желтый мешок (для пластика и упаковки)", "yellow sack for recycling", "Wohnung & Anmeldung"),
    ("das Altglas, (nur Sg.)", "Noun", "B1", "стеклотара", "waste glass", "Wohnung & Anmeldung"),
    ("der Lärm, (nur Sg.)", "Noun", "B1", "шум", "noise", "Wohnung & Anmeldung"),
    ("die Ruhestörung, die Ruhestörungen", "Noun", "B2", "нарушение покоя / тишины", "disturbance of peace", "Wohnung & Anmeldung"),
    ("die Mittagsruhe, (nur Sg.)", "Noun", "B1", "тихий час (обеденный перерыв)", "afternoon quiet time", "Wohnung & Anmeldung"),
    ("die Nachtruhe, (nur Sg.)", "Noun", "B1", "ночной покой / тишина", "night quiet time", "Wohnung & Anmeldung"),
    ("die Haustiere, (nur Pl.)", "Noun", "B1", "домашние животные", "pets", "Wohnung & Anmeldung"),
    ("die Tierhaltung, (nur Sg.)", "Noun", "B2", "содержание домашних животных", "keeping of pets", "Wohnung & Anmeldung"),
    ("der Schlüssel, die Schlüssel", "Noun", "B1", "ключ", "key", "Wohnung & Anmeldung"),
    ("der Wohnungsschlüssel, die Schlüssel", "Noun", "B1", "ключ от квартиры", "apartment key", "Wohnung & Anmeldung"),
    ("der Haustürschlüssel, die Schlüssel", "Noun", "B1", "ключ от входной двери дома", "house key", "Wohnung & Anmeldung"),
    ("die Übergabe, die Übergaben", "Noun", "B2", "передача / сдача (объекта)", "handover", "Wohnung & Anmeldung"),
    ("das Übergabeprotokoll, die Übergabeprotokolle", "Noun", "B2", "акт приема-передачи квартиры", "handover protocol", "Wohnung & Anmeldung"),
    ("der Mangel, die Mängel", "Noun", "B2", "недостаток / дефект", "defect / deficiency", "Wohnung & Anmeldung"),
    ("die Mängelrüge, die Mängelrügen", "Noun", "B2", "жалоба / уведомление о недостатках", "notice of defects", "Wohnung & Anmeldung"),
    ("reparieren", "Verb", "B1", "ремонтировать / исправлять", "to repair", "Wohnung & Anmeldung"),
    ("die Reparatur, die Reparaturen", "Noun", "B1", "ремонт / починка", "repair", "Wohnung & Anmeldung"),
    ("der Handwerker, die Handwerker", "Noun", "B1", "ремесленник / мастер", "craftsman", "Wohnung & Anmeldung"),
    ("die Renovierung, die Renovierungen", "Noun", "B1", "ремонт / косметический ремонт", "renovation", "Wohnung & Anmeldung"),
    ("renovieren", "Verb", "B1", "делать ремонт (косметический)", "to renovate", "Wohnung & Anmeldung"),
    ("die WG, die WGs", "Noun", "B1", "коммунальная квартира (студенческая)", "flatshare / Wohngemeinschaft", "Wohnung & Anmeldung"),
    ("der Mitbewohner, die Mitbewohner", "Noun", "B1", "сосед по квартире", "flatmate", "Wohnung & Anmeldung"),
    ("das Zimmer, die Zimmer", "Noun", "B1", "комната", "room", "Wohnung & Anmeldung"),
    ("die Einbauküche, die Einbauküchen", "Noun", "B1", "встроенная кухня", "fitted kitchen", "Wohnung & Anmeldung"),
    ("das Bad, die Bäder", "Noun", "B1", "ванная комната / ванна", "bathroom", "Wohnung & Anmeldung"),
    ("der Balkon, die Balkons", "Noun", "B1", "балкон", "balcony", "Wohnung & Anmeldung"),
    ("die Terrasse, die Terrassen", "Noun", "B1", "терраса", "terrace", "Wohnung & Anmeldung"),
    ("der Keller, die Keller", "Noun", "B1", "подвал", "cellar", "Wohnung & Anmeldung"),
    ("der Dachboden, die Dachböden", "Noun", "B1", "чердак", "attic", "Wohnung & Anmeldung"),
    ("der Stellplatz, die Stellplätze", "Noun", "B2", "парковочное место", "parking space", "Wohnung & Anmeldung"),
    ("die Garage, die Garagen", "Noun", "B1", "гараж", "garage", "Wohnung & Anmeldung"),
    ("der Mietspiegel, die Mietspiegel", "Noun", "B2", "официальный индекс арендной платы", "rent index", "Wohnung & Anmeldung"),
    ("die Mietpreisbremse, (nur Sg.)", "Noun", "B2", "ограничение роста стоимости аренды", "rent control", "Wohnung & Anmeldung"),
    ("die Wohnfläche, die Wohnflächen", "Noun", "B2", "жилая площадь", "living space", "Wohnung & Anmeldung"),
    ("das Quadratmeter, die Quadratmeter", "Noun", "B1", "квадратный метр", "square meter", "Wohnung & Anmeldung"),
    ("die Nebenkostenabrechnung, die Abrechnungen", "Noun", "B2", "расчет коммунальных услуг за год", "utility bill", "Wohnung & Anmeldung"),
    ("die Nachzahlung, die Nachzahlungen", "Noun", "B2", "доплата (при перерасчете)", "additional payment", "Wohnung & Anmeldung"),
    ("das Guthaben, die Guthaben", "Noun", "B2", "актив / остаток в пользу плательщика", "credit / balance", "Wohnung & Anmeldung"),
    ("die Mieterhöhung, die Mieterhöhungen", "Noun", "B2", "повышение арендной платы", "rent increase", "Wohnung & Anmeldung"),
    ("das Wohngeld, (nur Sg.)", "Noun", "B2", "жилищное пособие / субсидия на аренду", "housing benefit", "Wohnung & Anmeldung"),
    ("der Wohnberechtigungsschein, die Scheine", "Noun", "B2", "справка на право получения соцжилья", "public housing certificate", "Wohnung & Anmeldung"),
    ("die Sozialwohnung, die Sozialwohnungen", "Noun", "B2", "социальное жилье", "social housing", "Wohnung & Anmeldung"),
    ("die Genossenschaft, die Genossenschaften", "Noun", "B2", "кооператив / товарищество", "cooperative", "Wohnung & Anmeldung"),
    ("die Genossenschaftswohnung, die Wohnungen", "Noun", "B2", "кооперативная квартира", "cooperative apartment", "Wohnung & Anmeldung"),
    ("der Eigentümer, die Eigentümer", "Noun", "B2", "собственник / владелец", "owner", "Wohnung & Anmeldung"),
    ("die Eigentümergemeinschaft, die Gemeinschaften", "Noun", "B2", "товарищество собственников жилья (ТСЖ)", "owners' association", "Wohnung & Anmeldung"),
    ("das Wohneigentum, (nur Sg.)", "Noun", "B2", "жилая собственность", "residential property", "Wohnung & Anmeldung"),
    ("die Eigentumswohnung, die Eigentumswohnungen", "Noun", "B2", "приватизированная квартира", "condominium", "Wohnung & Anmeldung"),
    ("der Makler, die Makler", "Noun", "B2", "риелтор / маклер", "real estate agent", "Wohnung & Anmeldung"),
    ("die Maklergebühr, die Maklergebühren", "Noun", "B2", "комиссия риелтора", "broker's fee", "Wohnung & Anmeldung"),
    ("die Besichtigung, die Besichtigungen", "Noun", "B1", "осмотр (квартиры)", "viewing", "Wohnung & Anmeldung"),
    ("besichtigen", "Verb", "B1", "осматривать (помещение)", "to view", "Wohnung & Anmeldung"),
    ("der Besichtigungstermin, die Besichtigungstermine", "Noun", "B1", "время просмотра квартиры", "viewing appointment", "Wohnung & Anmeldung"),
    ("die Selbstauskunft, die Selbstauskünfte", "Noun", "B2", "анкета арендатора (сведения о себе)", "self-disclosure", "Wohnung & Anmeldung"),
    ("der Schufa-Auszug, die Auszüge", "Noun", "B2", "выписка из кредитной истории (Шуфа)", "credit report", "Wohnung & Anmeldung"),
    ("der Einkommensnachweis, die Einkommensnachweise", "Noun", "B2", "подтверждение доходов", "proof of income", "Wohnung & Anmeldung"),
    ("der Bürge, die Bürgen", "Noun", "B2", "поручитель", "guarantor", "Wohnung & Anmeldung"),
    ("die Bürgschaft, die Bürgschaften", "Noun", "B2", "поручительство / гарантия", "guaranty", "Wohnung & Anmeldung"),
    ("die Mietkaution, die Mietkautionen", "Noun", "B2", "залог за аренду жилья", "rental deposit", "Wohnung & Anmeldung"),
    ("das Kautionskonto, die Kautionskonten", "Noun", "B2", "залоговый банковский счет", "deposit account", "Wohnung & Anmeldung"),

    # Category 3: Gesundheit & Kassen (201-300)
    ("die Gesundheit, (nur Sg.)", "Noun", "B1", "здоровье", "health", "Gesundheit & Kassen"),
    ("die Krankheit, die Krankheiten", "Noun", "B1", "болезнь / заболевание", "illness", "Gesundheit & Kassen"),
    ("krank", "Adjective", "B1", "больной", "sick / ill", "Gesundheit & Kassen"),
    ("der Arzt, die Ärzte", "Noun", "B1", "врач", "doctor", "Gesundheit & Kassen"),
    ("die Ärztin, die Ärztinnen", "Noun", "B1", "врач (женщина)", "female doctor", "Gesundheit & Kassen"),
    ("der Hausarzt, die Hausärzte", "Noun", "B1", "домашний врач / терапевт", "family doctor / GP", "Gesundheit & Kassen"),
    ("der Facharzt, die Fachärzte", "Noun", "B2", "узкий специалист / профильный врач", "specialist doctor", "Gesundheit & Kassen"),
    ("die Praxis, die Praxen", "Noun", "B1", "врачебный кабинет / практика", "doctor's office", "Gesundheit & Kassen"),
    ("die Arztpraxis, die Arztpraxen", "Noun", "B1", "приемная врача / клиника", "doctor's surgery", "Gesundheit & Kassen"),
    ("der Termin, die Termine", "Noun", "B1", "запись на прием", "appointment", "Gesundheit & Kassen"),
    ("die Sprechstunde, die Sprechstunden", "Noun", "B1", "часы приема врача", "consultation hours", "Gesundheit & Kassen"),
    ("das Wartezimmer, die Wartezimmer", "Noun", "B1", "приемная / комната ожидания", "waiting room", "Gesundheit & Kassen"),
    ("die Versichertenkarte, die Versichertenkarten", "Noun", "B1", "страховой полис (пластиковая карта)", "insurance card", "Gesundheit & Kassen"),
    ("die Krankenversichertenkarte, die Karten", "Noun", "B1", "полис медицинского страхования", "health insurance card", "Gesundheit & Kassen"),
    ("die gesetzliche Krankenversicherung, die Versicherungen", "Noun", "B2", "обязательное медицинское страхование (ОМС)", "statutory health insurance", "Gesundheit & Kassen"),
    ("die private Krankenversicherung, die Versicherungen", "Noun", "B2", "добровольное медицинское страхование (ДМС)", "private health insurance", "Gesundheit & Kassen"),
    ("die Krankenkasse, die Krankenkassen", "Noun", "B1", "больничная / медицинская касса", "health insurance fund", "Gesundheit & Kassen"),
    ("der Beitrag, die Beiträge", "Noun", "B1", "страховой взнос", "contribution", "Gesundheit & Kassen"),
    ("versichert", "Adjective", "B1", "застрахованный", "insured", "Gesundheit & Kassen"),
    ("der Versicherte, die Versicherten", "Noun", "B2", "застрахованное лицо", "insured person", "Gesundheit & Kassen"),
    ("die Krankmeldung, die Krankmeldungen", "Noun", "B1", "уведомление о болезни (больничный)", "sick note", "Gesundheit & Kassen"),
    ("die Arbeitsunfähigkeitsbescheinigung, die Bescheinigungen", "Noun", "B2", "больничный лист (официальное название)", "certificate of incapacity for work", "Gesundheit & Kassen"),
    ("der Arbeitgeber, die Arbeitgeber", "Noun", "B1", "работодатель", "employer", "Gesundheit & Kassen"),
    ("die Krankschreibung, die Krankschreibungen", "Noun", "B1", "освобождение от работы по болезни", "sick leave / note", "Gesundheit & Kassen"),
    ("das Rezept, die Rezepte", "Noun", "B1", "рецепт (врача)", "prescription", "Gesundheit & Kassen"),
    ("das Kassenrezept, die Kassenrezepte", "Noun", "B2", "рецепт, оплачиваемый кассой (розовый)", "statutory prescription", "Gesundheit & Kassen"),
    ("das Privatrezept, die Privatrezepte", "Noun", "B2", "частный рецепт (полная оплата, синий)", "private prescription", "Gesundheit & Kassen"),
    ("die Apotheke, die Apotheken", "Noun", "B1", "аптека", "pharmacy", "Gesundheit & Kassen"),
    ("das Medikament, die Medikamente", "Noun", "B1", "лекарство / медикамент", "medicine", "Gesundheit & Kassen"),
    ("die Tablette, die Tabletten", "Noun", "B1", "таблетка", "pill / tablet", "Gesundheit & Kassen"),
    ("die Packungsbeilage, die Packungsbeilagen", "Noun", "B2", "инструкция к лекарству (вкладыш)", "leaflet / instructions", "Gesundheit & Kassen"),
    ("die Nebenwirkung, die Nebenwirkungen", "Noun", "B2", "побочное действие / эффект", "side effect", "Gesundheit & Kassen"),
    ("die Dosierung, die Dosierungen", "Noun", "B2", "дозировка", "dosage", "Gesundheit & Kassen"),
    ("einnehmen", "Verb", "B1", "принимать (лекарство)", "to take (medicine)", "Gesundheit & Kassen"),
    ("die Impfung, die Impfungen", "Noun", "B1", "прививка / вакцинация", "vaccination", "Gesundheit & Kassen"),
    ("impfen", "Verb", "B1", "прививать / вакцинировать", "to vaccinate", "Gesundheit & Kassen"),
    ("der Impfpass, die Impfpässe", "Noun", "B1", "прививочный сертификат", "vaccination certificate", "Gesundheit & Kassen"),
    ("die Vorsorgeuntersuchung, die Vorsorgeuntersuchungen", "Noun", "B2", "профилактический осмотр", "preventative check-up", "Gesundheit & Kassen"),
    ("die Untersuchung, die Untersuchungen", "Noun", "B1", "обследование / осмотр", "examination", "Gesundheit & Kassen"),
    ("untersuchen", "Verb", "B1", "обследовать / осматривать", "to examine", "Gesundheit & Kassen"),
    ("das Krankenhaus, die Krankenhäuser", "Noun", "B1", "больница", "hospital", "Gesundheit & Kassen"),
    ("die Klinik, die Kliniken", "Noun", "B1", "клиника", "clinic", "Gesundheit & Kassen"),
    ("die Notaufnahme, die Notaufnahmen", "Noun", "B1", "отделение скорой помощи / приемный покой", "emergency room", "Gesundheit & Kassen"),
    ("der Notfall, die Notfälle", "Noun", "B1", "экстренный случай", "emergency", "Gesundheit & Kassen"),
    ("der Notarzt, die Notärzte", "Noun", "B1", "врач скорой помощи", "emergency doctor", "Gesundheit & Kassen"),
    ("der Rettungswagen, die Rettungswagen", "Noun", "B1", "машина скорой помощи (реанимация)", "ambulance", "Gesundheit & Kassen"),
    ("der Krankenwagen, die Krankenwagen", "Noun", "B1", "машина скорой помощи (санитарная)", "ambulance", "Gesundheit & Kassen"),
    ("der Unfall, die Unfälle", "Noun", "B1", "несчастный случай / ДТП", "accident", "Gesundheit & Kassen"),
    ("die Verletzung, die Verletzungen", "Noun", "B1", "травма / повреждение", "injury", "Gesundheit & Kassen"),
    ("sich verletzen", "Verb", "B1", "получить травму / пораниться", "to injure oneself", "Gesundheit & Kassen"),
    ("die Schmerzen, (nur Pl.)", "Noun", "B1", "боли", "pain", "Gesundheit & Kassen"),
    ("das Symptom, die Symptome", "Noun", "B2", "симптом / признак болезни", "symptom", "Gesundheit & Kassen"),
    ("das Fieber, (nur Sg.)", "Noun", "B1", "высокая температура / жар", "fever", "Gesundheit & Kassen"),
    ("der Husten, (nur Sg.)", "Noun", "B1", "кашель", "cough", "Gesundheit & Kassen"),
    ("der Schnupfen, (nur Sg.)", "Noun", "B1", "насморк", "cold / sniffles", "Gesundheit & Kassen"),
    ("die Halsschmerzen, (nur Pl.)", "Noun", "B1", "боль в горле", "sore throat", "Gesundheit & Kassen"),
    ("die Kopfschmerzen, (nur Pl.)", "Noun", "B1", "головная боль", "headache", "Gesundheit & Kassen"),
    ("die Zahnschmerzen, (nur Pl.)", "Noun", "B1", "зубная боль", "toothache", "Gesundheit & Kassen"),
    ("der Zahnarzt, die Zahnärzte", "Noun", "B1", "стоматолог / зубной врач", "dentist", "Gesundheit & Kassen"),
    ("die Zahnarztpraxis, die Zahnarztpraxen", "Noun", "B1", "стоматологический кабинет", "dental clinic", "Gesundheit & Kassen"),
    ("die Zahnreinigung, die Zahnreinigungen", "Noun", "B2", "чистка зубов (профессиональная)", "dental cleaning", "Gesundheit & Kassen"),
    ("die Krankengymnastik, (nur Sg.)", "Noun", "B1", "лечебная физкультура (ЛФК)", "physiotherapy", "Gesundheit & Kassen"),
    ("die Physiotherapie, die Physiotherapien", "Noun", "B2", "физиотерапия", "physiotherapy", "Gesundheit & Kassen"),
    ("der Therapeut, die Therapeuten", "Noun", "B2", "терапевт (физиотерапевт/психотерапевт)", "therapist", "Gesundheit & Kassen"),
    ("das Attest, die Atteste", "Noun", "B2", "медицинская справка / свидетельство", "medical certificate", "Gesundheit & Kassen"),
    ("das ärztliche Attest, die Atteste", "Noun", "B2", "справка от врача", "medical certificate", "Gesundheit & Kassen"),
    ("die Kur, die Kuren", "Noun", "B2", "санаторно-курортное лечение", "health spa / cure", "Gesundheit & Kassen"),
    ("die Reha, die Rehas", "Noun", "B2", "реабилитация", "rehabilitation", "Gesundheit & Kassen"),
    ("die Rehabilitation, die Rehabilitationen", "Noun", "B2", "реабилитация (полное слово)", "rehabilitation", "Gesundheit & Kassen"),
    ("der Befund, die Befunde", "Noun", "B2", "результат исследования / диагноз", "medical report / findings", "Gesundheit & Kassen"),
    ("die Diagnose, die Diagnosen", "Noun", "B2", "диагноз", "diagnose", "Gesundheit & Kassen"),
    ("diagnostizieren", "Verb", "B2", "диагностировать / ставить диагноз", "to diagnose", "Gesundheit & Kassen"),
    ("die Therapie, die Therapien", "Noun", "B2", "терапия / лечение", "therapy", "Gesundheit & Kassen"),
    ("behandeln", "Verb", "B1", "лечить / обрабатывать", "to treat", "Gesundheit & Kassen"),
    ("die Behandlung, die Behandlungen", "Noun", "B1", "лечение / процедура", "treatment", "Gesundheit & Kassen"),
    ("die Zuzahlung, die Zuzahlungen", "Noun", "B2", "доплата (пациента за услуги/лекарства)", "copayment", "Gesundheit & Kassen"),
    ("die Befreiung, die Befreiungen", "Noun", "B2", "освобождение (от доплаты)", "exemption", "Gesundheit & Kassen"),
    ("die Überweisung, die Überweisungen", "Noun", "B1", "направление к другому врачу", "referral", "Gesundheit & Kassen"),
    ("überweisen", "Verb", "B1", "направлять (к специалисту)", "to refer", "Gesundheit & Kassen"),
    ("der Heil- und Kostenplan, die Pläne", "Noun", "B2", "план лечения и калькуляция расходов", "treatment and cost plan", "Gesundheit & Kassen"),
    ("der Zahnersatz, (nur Sg.)", "Noun", "B2", "зубное протезирование / протезы", "dentures", "Gesundheit & Kassen"),
    ("die Brille, die Brillen", "Noun", "B1", "очки", "glasses", "Gesundheit & Kassen"),
    ("der Optiker, die Optiker", "Noun", "B1", "оптик", "optician", "Gesundheit & Kassen"),
    ("das Hörgerät, die Hörgeräte", "Noun", "B2", "слуховой аппарат", "hearing aid", "Gesundheit & Kassen"),
    ("die Pflege, (nur Sg.)", "Noun", "B2", "уход / забота", "care / nursing", "Gesundheit & Kassen"),
    ("die Pflegeversicherung, die Pflegeversicherungen", "Noun", "B2", "страхование на случай потребности в уходе", "nursing care insurance", "Gesundheit & Kassen"),
    ("der Pflegefall, die Pflegefälle", "Noun", "B2", "человек, нуждающийся в постоянном уходе", "case of needing care", "Gesundheit & Kassen"),
    ("der Pflegedienst, die Pflegedienste", "Noun", "B2", "служба социального ухода на дому", "nursing service", "Gesundheit & Kassen"),
    ("das Pflegeheim, die Pflegeheime", "Noun", "B2", "дом престарелых / пансионат с уходом", "nursing home", "Gesundheit & Kassen"),
    ("die Patientenverfügung, die Verfügungen", "Noun", "B2", "завещание пациента (распоряжение на случай комы)", "living will", "Gesundheit & Kassen"),
    ("die Vorsorgevollmacht, die Vollmachten", "Noun", "B2", "доверенность на принятие мед. решений", "durable power of attorney", "Gesundheit & Kassen"),

    # Category 4: ÖPNV & Reisen (301-400)
    ("der ÖPNV, (nur Sg.)", "Noun", "B1", "общественный транспорт (сокращение)", "public transport", "ÖPNV & Reisen"),
    ("das Verkehrsmittel, die Verkehrsmittel", "Noun", "B1", "транспортное средство", "means of transport", "ÖPNV & Reisen"),
    ("die Haltestelle, die Haltestellen", "Noun", "B1", "остановка (автобуса/трамвая)", "stop / station", "ÖPNV & Reisen"),
    ("der Bahnhof, die Bahnhöfe", "Noun", "B1", "вокзал / станция", "railway station", "ÖPNV & Reisen"),
    ("der Hauptbahnhof, die Hauptbahnhöfe", "Noun", "B1", "главный / центральный вокзал", "main station", "ÖPNV & Reisen"),
    ("der Bahnsteig, die Bahnsteige", "Noun", "B1", "перрон / пассажирская платформа", "platform", "ÖPNV & Reisen"),
    ("das Gleis, die Gleise", "Noun", "B1", "путь / железнодорожный путь", "track", "ÖPNV & Reisen"),
    ("der Zug, die Züge", "Noun", "B1", "поезд", "train", "ÖPNV & Reisen"),
    ("die S-Bahn, die S-Bahnen", "Noun", "B1", "городская электричка", "suburban train", "ÖPNV & Reisen"),
    ("die U-Bahn, die U-Bahnen", "Noun", "B1", "метрополитен / метро", "underground / subway", "ÖPNV & Reisen"),
    ("die Straßenbahn, die Straßenbahnen", "Noun", "B1", "трамвай (полное слово)", "tram", "ÖPNV & Reisen"),
    ("die Tram, die Trams", "Noun", "B1", "трамвай", "tram", "ÖPNV & Reisen"),
    ("der Bus, die Busse", "Noun", "B1", "автобус", "bus", "ÖPNV & Reisen"),
    ("die Buslinie, die Buslinien", "Noun", "B1", "автобусный маршрут / линия", "bus line", "ÖPNV & Reisen"),
    ("der Fahrplan, die Fahrpläne", "Noun", "B1", "расписание движения транспорта", "timetable", "ÖPNV & Reisen"),
    ("die Abfahrt, die Abfahrten", "Noun", "B1", "отправление / отъезд", "departure", "ÖPNV & Reisen"),
    ("die Ankunft, die Ankünfte", "Noun", "B1", "прибытие / приезд", "arrival", "ÖPNV & Reisen"),
    ("die Verspätung, die Verspätungen", "Noun", "B1", "опоздание / задержка рейса", "delay", "ÖPNV & Reisen"),
    ("pünktlich", "Adjective", "B1", "пунктуальный / вовремя", "punctual", "ÖPNV & Reisen"),
    ("der Anschluss, die Anschlüsse", "Noun", "B1", "пересадка / стыковочный рейс", "connection", "ÖPNV & Reisen"),
    ("umsteigen", "Verb", "B1", "делать пересадку / пересаживаться", "to change trains / buses", "ÖPNV & Reisen"),
    ("einsteigen", "Verb", "B1", "входить / садиться в транспорт", "to get in / board", "ÖPNV & Reisen"),
    ("aussteigen", "Verb", "B1", "выходить из транспорта", "to get out / alight", "ÖPNV & Reisen"),
    ("die Fahrkarte, die Fahrkarten", "Noun", "B1", "билет (на поезд/автобус)", "ticket", "ÖPNV & Reisen"),
    ("das Ticket, die Tickets", "Noun", "B1", "проездной билет", "ticket", "ÖPNV & Reisen"),
    ("der Fahrkartenautomat, die Fahrkartenautomaten", "Noun", "B1", "автомат по продаже билетов", "ticket machine", "ÖPNV & Reisen"),
    ("der Fahrschein, die Fahrscheine", "Noun", "B1", "проездной билет / талон", "ticket", "ÖPNV & Reisen"),
    ("entwerten", "Verb", "B1", "компостировать / активировать билет", "to validate (a ticket)", "ÖPNV & Reisen"),
    ("der Entwerter, die Entwerter", "Noun", "B1", "компостер / валидатор билетов", "ticket validator", "ÖPNV & Reisen"),
    ("die Fahrkartenkontrolle, die Fahrkartenkontrollen", "Noun", "B1", "контроль билетов", "ticket inspection", "ÖPNV & Reisen"),
    ("der Kontrolleur, die Kontrolleure", "Noun", "B1", "контролер", "ticket inspector", "ÖPNV & Reisen"),
    ("schwarzfahren", "Verb", "B1", "ездить зайцем / без билета", "to ride without a ticket", "ÖPNV & Reisen"),
    ("das Schwarzfahren, (nur Sg.)", "Noun", "B1", "безбилетный проезд", "fare evasion", "ÖPNV & Reisen"),
    ("das Bußgeld, die Bußgelder", "Noun", "B2", "денежный штраф", "fine", "ÖPNV & Reisen"),
    ("das Abonnement, die Abonnements", "Noun", "B1", "абонемент / подписка", "subscription", "ÖPNV & Reisen"),
    ("das Abo, die Abos", "Noun", "B1", "абонемент (краткая форма)", "subscription", "ÖPNV & Reisen"),
    ("die Monatskarte, die Monatskarten", "Noun", "B1", "проездной билет на месяц", "monthly ticket", "ÖPNV & Reisen"),
    ("die Wochenkarte, die Wochenkarten", "Noun", "B1", "проездной билет на неделю", "weekly ticket", "ÖPNV & Reisen"),
    ("die Tageskarte, die Tageskarten", "Noun", "B1", "билет на один день", "day ticket", "ÖPNV & Reisen"),
    ("die Einzelfahrkarte, die Einzelfahrkarten", "Noun", "B1", "разовый проездной билет", "single ticket", "ÖPNV & Reisen"),
    ("die BahnCard, die BahnCards", "Noun", "B1", "карта скидок железных дорог Германии", "discount card of DB", "ÖPNV & Reisen"),
    ("die Ermäßigung, die Ermäßigungen", "Noun", "B1", "скидка / льгота", "discount", "ÖPNV & Reisen"),
    ("ermäßigt", "Adjective", "B1", "со скидкой / льготный", "discounted", "ÖPNV & Reisen"),
    ("der Tarif, die Tarife", "Noun", "B2", "тариф / ставка оплаты", "tariff / fare", "ÖPNV & Reisen"),
    ("die Tarifzone, die Tarifzonen", "Noun", "B2", "тарифная зона", "fare zone", "ÖPNV & Reisen"),
    ("der Verkehrsverbund, die Verkehrsverbünde", "Noun", "B2", "объединение перевозчиков / транспортный союз", "transport association", "ÖPNV & Reisen"),
    ("die Reise, die Reisen", "Noun", "B1", "путешествие / поездка", "journey / travel", "ÖPNV & Reisen"),
    ("reisen", "Verb", "B1", "путешествовать", "to travel", "ÖPNV & Reisen"),
    ("das Reisebüro, die Reisebüros", "Noun", "B1", "туристическое агентство", "travel agency", "ÖPNV & Reisen"),
    ("die Buchung, die Buchungen", "Noun", "B1", "бронирование", "booking", "ÖPNV & Reisen"),
    ("buchen", "Verb", "B1", "бронировать", "to book", "ÖPNV & Reisen"),
    ("stornieren", "Verb", "B2", "аннулировать / отменять бронь", "to cancel", "ÖPNV & Reisen"),
    ("die Stornierung, die Stornierungen", "Noun", "B2", "отмена бронирования / аннулирование", "cancellation", "ÖPNV & Reisen"),
    ("die Umbuchung, die Umbuchungen", "Noun", "B2", "изменение бронирования", "rebooking", "ÖPNV & Reisen"),
    ("das Gepäck, (nur Sg.)", "Noun", "B1", "багаж", "luggage", "ÖPNV & Reisen"),
    ("das Handgepäck, (nur Sg.)", "Noun", "B1", "ручная кладь", "hand luggage", "ÖPNV & Reisen"),
    ("der Koffer, die Koffer", "Noun", "B1", "чемодан", "suitcase", "ÖPNV & Reisen"),
    ("die Tasche, die Taschen", "Noun", "B1", "сумка", "bag", "ÖPNV & Reisen"),
    ("die Gepäckaufbewahrung, die Gepäckaufbewahrungen", "Noun", "B2", "камера хранения багажа", "luggage storage", "ÖPNV & Reisen"),
    ("der Flughafen, die Flughäfen", "Noun", "B1", "аэропорт", "airport", "ÖPNV & Reisen"),
    ("das Flugzeug, die Flugzeuge", "Noun", "B1", "самолет", "airplane", "ÖPNV & Reisen"),
    ("der Flug, die Flüge", "Noun", "B1", "полет / рейс", "flight", "ÖPNV & Reisen"),
    ("der Abflug, die Abflüge", "Noun", "B1", "вылет (самолета)", "departure", "ÖPNV & Reisen"),
    ("die Landung, die Landungen", "Noun", "B1", "посадка (самолета)", "landing", "ÖPNV & Reisen"),
    ("das Terminal, die Terminals", "Noun", "B1", "терминал", "terminal", "ÖPNV & Reisen"),
    ("das Gate, die Gates", "Noun", "B1", "выход на посадку в аэропорту", "gate", "ÖPNV & Reisen"),
    ("der Check-in, die Check-ins", "Noun", "B1", "регистрация при въезде / вылете", "check-in", "ÖPNV & Reisen"),
    ("die Sicherheitskontrolle, die Sicherheitskontrollen", "Noun", "B1", "досмотр / контроль безопасности", "security check", "ÖPNV & Reisen"),
    ("die Passkontrolle, die Passkontrollen", "Noun", "B1", "паспортный контроль", "passport control", "ÖPNV & Reisen"),
    ("die Gepäckausgabe, die Gepäckausgaben", "Noun", "B1", "выдача багажа", "baggage claim", "ÖPNV & Reisen"),
    ("der Zoll, die Zölle", "Noun", "B2", "таможня", "customs", "ÖPNV & Reisen"),
    ("verzollen", "Verb", "B2", "декларировать на таможне / оплачивать пошлину", "to declare (customs)", "ÖPNV & Reisen"),
    ("das Hotel, die Hotels", "Noun", "B1", "отель / гостиница", "hotel", "ÖPNV & Reisen"),
    ("die Unterkunft, die Unterkünfte", "Noun", "B1", "жилье / приют / ночлег", "accommodation", "ÖPNV & Reisen"),
    ("die Pension, die Pensionen", "Noun", "B1", "гостевой дом / пансион", "guesthouse", "ÖPNV & Reisen"),
    ("die Jugendherberge, die Jugendherbergen", "Noun", "B1", "молодежный хостел", "youth hostel", "ÖPNV & Reisen"),
    ("die Ferienwohnung, die Ferienwohnungen", "Noun", "B1", "квартира для отдыха (посуточно)", "holiday apartment", "ÖPNV & Reisen"),
    ("das Doppelzimmer, die Doppelzimmer", "Noun", "B1", "двухместный номер", "double room", "ÖPNV & Reisen"),
    ("das Einzelzimmer, die Einzelzimmer", "Noun", "B1", "одноместный номер", "single room", "ÖPNV & Reisen"),
    ("die Reservierung, die Reservierungen", "Noun", "B1", "резервирование / бронь", "reservation", "ÖPNV & Reisen"),
    ("reservieren", "Verb", "B1", "резервировать / бронировать", "to reserve", "ÖPNV & Reisen"),
    ("die Rezeption, die Rezeptionen", "Noun", "B1", "стойка регистрации / рецепция", "reception", "ÖPNV & Reisen"),
    ("der Check-out, die Check-outs", "Noun", "B1", "выезд из гостиницы / расчетный час", "check-out", "ÖPNV & Reisen"),
    ("die Kurtaxe, die Kurtaxen", "Noun", "B2", "курортный сбор", "tourist tax", "ÖPNV & Reisen"),
    ("der Reiseführer, die Reiseführer", "Noun", "B1", "путеводитель / гид", "guidebook / tour guide", "ÖPNV & Reisen"),
    ("die Sehenswürdigkeit, die Sehenswürdigkeiten", "Noun", "B1", "достопримечательность", "tourist attraction", "ÖPNV & Reisen"),
    ("die Stadtrundfahrt, die Stadtrundfahrten", "Noun", "B1", "экскурсия по городу", "city tour", "ÖPNV & Reisen"),
    ("der Ausflug, die Ausflüge", "Noun", "B1", "экскурсия / вылазка / прогулка", "excursion", "ÖPNV & Reisen"),
    ("wandern", "Verb", "B1", "ходить в поход / прогуливаться пешком", "to hike", "ÖPNV & Reisen"),
    ("die Wanderung, die Wanderungen", "Noun", "B1", "пеший поход / прогулка", "hike", "ÖPNV & Reisen"),

    # Category 5: Alltag & Dienste (401-500)
    ("der Alltag, (nur Sg.)", "Noun", "B1", "будни / повседневная жизнь", "everyday life", "Alltag & Dienste"),
    ("der Dienst, die Dienste", "Noun", "B1", "служба / услуга", "service", "Alltag & Dienste"),
    ("der Dienstleister, die Dienstleister", "Noun", "B2", "поставщик услуг / исполнитель", "service provider", "Alltag & Dienste"),
    ("die Post, (nur Sg.)", "Noun", "B1", "почта / почтовое отделение", "post office / mail", "Alltag & Dienste"),
    ("der Postbote, die Postboten", "Noun", "B1", "почтальон", "mailman", "Alltag & Dienste"),
    ("das Paket, die Pakete", "Noun", "B1", "посылка / пакет", "parcel / package", "Alltag & Dienste"),
    ("das Päckchen, die Päckchen", "Noun", "B1", "бандероль / маленькая посылка", "small parcel", "Alltag & Dienste"),
    ("der Brief, die Briefe", "Noun", "B1", "письмо", "letter", "Alltag & Dienste"),
    ("der Briefkasten, die Briefkästen", "Noun", "B1", "почтовый ящик", "mailbox", "Alltag & Dienste"),
    ("die Postfiliale, die Postfilialen", "Noun", "B1", "почтовое отделение", "post office branch", "Alltag & Dienste"),
    ("die Packstation, die Packstationen", "Noun", "B1", "почтомат / автоматическая станция посылок", "parcel station", "Alltag & Dienste"),
    ("versenden", "Verb", "B1", "отправлять / посылать", "to send", "Alltag & Dienste"),
    ("empfangen", "Verb", "B2", "принимать / получать", "to receive", "Alltag & Dienste"),
    ("abholen", "Verb", "B1", "забирать / получать", "to pick up", "Alltag & Dienste"),
    ("die Benachrichtigung, die Benachrichtigungen", "Noun", "B2", "уведомление / извещение", "notification", "Alltag & Dienste"),
    ("der Absender, die Absender", "Noun", "B1", "отправитель", "sender", "Alltag & Dienste"),
    ("der Empfänger, die Empfänger", "Noun", "B1", "получатель", "recipient", "Alltag & Dienste"),
    ("das Porto, (nur Sg.)", "Noun", "B2", "почтовый сбор / стоимость пересылки", "postage", "Alltag & Dienste"),
    ("frankieren", "Verb", "B2", "наклеивать марки / оплачивать почтовые расходы", "to pay postage", "Alltag & Dienste"),
    ("die Bank, die Banken", "Noun", "B1", "банк", "bank", "Alltag & Dienste"),
    ("das Bankkonto, die Bankkonten", "Noun", "B1", "банковский счет", "bank account", "Alltag & Dienste"),
    ("das Girokonto, die Girokonten", "Noun", "B1", "расчетный счет", "checking account", "Alltag & Dienste"),
    ("das Sparkonto, die Sparkonten", "Noun", "B1", "сберегательный счет", "savings account", "Alltag & Dienste"),
    ("die Bankkarte, die Bankkarten", "Noun", "B1", "банковская карта", "bank card", "Alltag & Dienste"),
    ("die EC-Karte, die EC-Karten", "Noun", "B1", "дебетовая карта", "debit card", "Alltag & Dienste"),
    ("die Kreditkarte, die Kreditkarten", "Noun", "B1", "кредитная карта", "credit card", "Alltag & Dienste"),
    ("der Geldautomat, die Geldautomaten", "Noun", "B1", "банкомат", "ATM", "Alltag & Dienste"),
    ("Geld abheben", "Verb", "B1", "снимать наличные деньги", "to withdraw money", "Alltag & Dienste"),
    ("einzahlen", "Verb", "B1", "вносить на счет (деньги)", "to deposit", "Alltag & Dienste"),
    ("die Einzahlung, die Einzahlungen", "Noun", "B2", "взнос наличных / депозит", "deposit", "Alltag & Dienste"),
    ("überweisen", "Verb", "B1", "переводить (деньги на счет)", "to transfer", "Alltag & Dienste"),
    ("die Überweisung, die Überweisungen", "Noun", "B1", "банковский перевод", "bank transfer", "Alltag & Dienste"),
    ("der Dauerauftrag, die Daueraufträge", "Noun", "B2", "постоянное платежное поручение (автоплатеж)", "standing order", "Alltag & Dienste"),
    ("die Lastschrift, die Lastschriften", "Noun", "B2", "прямое списание со счета", "direct debit", "Alltag & Dienste"),
    ("das Online-Banking, (nur Sg.)", "Noun", "B1", "онлайн-банкинг", "online banking", "Alltag & Dienste"),
    ("der Kontoauszug, die Kontoauszüge", "Noun", "B1", "выписка со счета", "account statement", "Alltag & Dienste"),
    ("die Kontogebühr, die Kontogebühren", "Noun", "B2", "плата за обслуживание счета", "account fee", "Alltag & Dienste"),
    ("der Kontostand, die Kontostände", "Noun", "B1", "состояние счета / баланс", "account balance", "Alltag & Dienste"),
    ("sperren", "Verb", "B1", "блокировать (карту/счет)", "to block (e.g. card)", "Alltag & Dienste"),
    ("die Kartensperrung, die Kartensperrungen", "Noun", "B2", "блокировка карты", "card blocking", "Alltag & Dienste"),
    ("der Notruf, die Notrufe", "Noun", "B1", "экстренный вызов / телефон спасения", "emergency call", "Alltag & Dienste"),
    ("die Polizei, (nur Sg.)", "Noun", "B1", "полиция", "police", "Alltag & Dienste"),
    ("die Feuerwehr, die Feuerwehren", "Noun", "B1", "пожарная команда", "fire brigade", "Alltag & Dienste"),
    ("der Notdienst, die Notdienste", "Noun", "B2", "дежурная служба / экстренная помощь", "emergency service", "Alltag & Dienste"),
    ("der Apotheken-Notdienst, die Notdienste", "Noun", "B2", "дежурная аптека", "emergency pharmacy", "Alltag & Dienste"),
    ("das Fundbüro, die Fundbüros", "Noun", "B1", "бюро находок", "lost and found office", "Alltag & Dienste"),
    ("verlieren", "Verb", "B1", "терять", "to lose", "Alltag & Dienste"),
    ("finden", "Verb", "B1", "находить", "to find", "Alltag & Dienste"),
    ("das Fundstück, die Fundstücke", "Noun", "B2", "найденная вещь", "found object", "Alltag & Dienste"),
    ("die Müllabfuhr, (nur Sg.)", "Noun", "B1", "вывоз мусора (служба)", "garbage collection", "Alltag & Dienste"),
    ("die Mülltonne, die Mülltonnen", "Noun", "B1", "мусорный бак", "dustbin / garbage can", "Alltag & Dienste"),
    ("der Sperrmüll, (nur Sg.)", "Noun", "B2", "крупногабаритный мусор", "bulky waste", "Alltag & Dienste"),
    ("das Recycling, (nur Sg.)", "Noun", "B1", "переработка отходов / рециклинг", "recycling", "Alltag & Dienste"),
    ("der Wertstoffhof, die Wertstoffhöfe", "Noun", "B2", "пункт приема вторсырья", "recycling center", "Alltag & Dienste"),
    ("die Reinigung, die Reinigungen", "Noun", "B1", "химчистка / уборка", "dry cleaner / cleaning", "Alltag & Dienste"),
    ("die Wäscherei, die Wäschereien", "Noun", "B2", "прачечная", "laundry", "Alltag & Dienste"),
    ("waschen", "Verb", "B1", "стирать (белье)", "to wash", "Alltag & Dienste"),
    ("reinigen", "Verb", "B1", "чистить", "to clean", "Alltag & Dienste"),
    ("der Friseur, die Friseure", "Noun", "B1", "парикмахер", "hairdresser", "Alltag & Dienste"),
    ("der Haarschnitt, die Haarschnitte", "Noun", "B1", "стрижка", "haircut", "Alltag & Dienste"),
    ("die Drogerie, die Drogerien", "Noun", "B1", "магазин бытовой химии и косметики", "drugstore", "Alltag & Dienste"),
    ("supermarkt, die Supermärkte", "Noun", "B1", "супермаркет", "supermarket", "Alltag & Dienste"),
    ("der Lebensmittelladen, die Läden", "Noun", "B1", "продуктовый магазин", "grocery store", "Alltag & Dienste"),
    ("die Bäckerei, die Bäckereien", "Noun", "B1", "булочная / пекарня", "bakery", "Alltag & Dienste"),
    ("die Metzgerei, die Metzgereien", "Noun", "B2", "мясная лавка", "butcher's", "Alltag & Dienste"),
    ("der Markt, die Märkte", "Noun", "B1", "рынок", "market", "Alltag & Dienste"),
    ("der Wochenmarkt, die Wochenmärkte", "Noun", "B1", "еженедельный рынок", "weekly market", "Alltag & Dienste"),
    ("einkaufen", "Verb", "B1", "делать покупки / покупать", "to shop", "Alltag & Dienste"),
    ("der Einkauf, die Einkäufe", "Noun", "B1", "покупка / закупки", "purchase / shopping", "Alltag & Dienste"),
    ("der Einkaufszettel, die Einkaufszettel", "Noun", "B1", "список покупок", "shopping list", "Alltag & Dienste"),
    ("der Einkaufswagen, die Einkaufswagen", "Noun", "B1", "тележка для покупок", "shopping trolley", "Alltag & Dienste"),
    ("der Kassenzettel, die Kassenzettel", "Noun", "B1", "кассовый чек", "receipt", "Alltag & Dienste"),
    ("bar bezahlen", "Verb", "B1", "платить наличными", "to pay cash", "Alltag & Dienste"),
    ("mit Karte bezahlen", "Verb", "B1", "оплачивать картой", "to pay by card", "Alltag & Dienste"),
    ("reklamieren", "Verb", "B2", "предъявлять претензию / жаловаться (на качество)", "to complain / return", "Alltag & Dienste"),
    ("die Reklamation, die Reklamationen", "Noun", "B2", "претензия / жалоба", "complaint / return", "Alltag & Dienste"),
    ("umtauschen", "Verb", "B1", "обменивать (товар)", "to exchange", "Alltag & Dienste"),
    ("der Umtauch, die Umtäusche", "Noun", "B2", "обмен (товара)", "exchange", "Alltag & Dienste"),
    ("die Garantie, die Garantien", "Noun", "B1", "гарантия", "guarantee", "Alltag & Dienste"),
    ("der Kundenservice, (nur Sg.)", "Noun", "B1", "служба поддержки клиентов", "customer service", "Alltag & Dienste"),
    ("die Hotline, die Hotlines", "Noun", "B1", "горячая линия", "hotline", "Alltag & Dienste"),
    ("der Internetanbieter, die Internetanbieter", "Noun", "B2", "интернет-провайдер", "internet provider", "Alltag & Dienste"),
    ("der Mobilfunkanbieter, die Mobilfunkanbieter", "Noun", "B2", "оператор сотовой связи", "mobile provider", "Alltag & Dienste"),
    ("der Handyvertrag, die Handyverträge", "Noun", "B1", "договор на сотовую связь", "mobile contract", "Alltag & Dienste"),
    ("der Stromanbieter, die Stromanbieter", "Noun", "B2", "поставщик электроэнергии", "electricity provider", "Alltag & Dienste"),
    ("die Stadtwerke, (nur Pl.)", "Noun", "B2", "коммунальные службы города", "municipal utilities", "Alltag & Dienste"),
    ("der Zählerstand, die Zählerstände", "Noun", "B2", "показания счетчика", "meter reading", "Alltag & Dienste"),
    ("der Stromzähler, die Stromzähler", "Noun", "B2", "электросчетчик", "electricity meter", "Alltag & Dienste"),
    ("die Wasserleitung, die Wasserleitungen", "Noun", "B2", "водопровод", "water pipe", "Alltag & Dienste"),
    ("die Heizung, die Heizungen", "Noun", "B1", "отопление", "heating", "Alltag & Dienste"),
    ("das Gas, die Gase", "Noun", "B1", "газ", "gas", "Alltag & Dienste"),
]
