# -*- coding: utf-8 -*-

words = [
    # Category 1: SAP FI/CO (Finanzwesen & Controlling) (1-100)
    ("das Hauptbuch, die Hauptbücher", "Noun", "B2", "главная книга", "general ledger", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Kostenstelle, die Kostenstellen", "Noun", "B2", "место возникновения затрат (МВЗ)", "cost center", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("das Profit-Center, die Profit-Center", "Noun", "B2", "центр прибыли", "profit center", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Anlagenbuchhaltung, die Anlagenbuchhaltungen", "Noun", "B2", "учет основных средств", "asset accounting", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Kreditorenbuchhaltung, die Kreditorenbuchhaltungen", "Noun", "B2", "бухгалтерия кредиторов (AP)", "accounts payable", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Debitorenbuchhaltung, die Debitorenbuchhaltungen", "Noun", "B2", "бухгалтерия дебиторов (AR)", "accounts receivable", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("der Buchungskreis, die Buchungskreise", "Noun", "B2", "балансовая единица (БЕ)", "company code", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("buchen", "Verb", "B1", "проводить (документ) / бронировать", "to post / book", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("ausgleichen", "Verb", "B2", "выравнивать (открытые позиции)", "to clear / reconcile", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("der Beleg, die Belege", "Noun", "B1", "документ / проводка", "document / voucher", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Belegart, die Belegarten", "Noun", "B2", "вид документа", "document type", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Buchungsperiode, die Buchungsperioden", "Noun", "B2", "период проведения", "posting period", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("das Geschäftsjahr, die Geschäftsjahre", "Noun", "B2", "финансовый / отчетный год", "fiscal year", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Bilanz, die Bilanzen", "Noun", "B2", "баланс", "balance sheet", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Gewinn- und Verlustrechnung, die Rechnungen", "Noun", "B2", "отчет о прибылях и убытках (ПиУ)", "profit and loss statement (P&L)", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("das Sachkonto, die Sachkonten", "Noun", "B2", "счет главной книги", "G/L account", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Kostenstellenrechnung, die Rechnungen", "Noun", "B2", "учет затрат по МВЗ", "cost center accounting", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Gemeinkosten, (nur Pl.)", "Noun", "B2", "косвенные / накладные расходы", "overhead costs", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Einzelkosten, (nur Pl.)", "Noun", "B2", "прямые затраты", "direct costs", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Leistungsart, die Leistungsarten", "Noun", "B2", "вид работ", "activity type", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("der Tarif, die Tarife", "Noun", "B2", "тариф / ставка", "activity rate / tariff", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Kostenart, die Kostenarten", "Noun", "B2", "вид затрат", "cost element", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die primäre Kostenart, die Kostenarten", "Noun", "B2", "первичный вид затрат", "primary cost element", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die sekundäre Kostenart, die Kostenarten", "Noun", "B2", "вторичный вид затрат", "secondary cost element", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Umlage, die Umlagen", "Noun", "B2", "раскладка (затрат)", "assessment", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Verteilung, die Verteilungen", "Noun", "B2", "распределение (затрат)", "distribution", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("der statistische Kennzahl, die Kennzahlen", "Noun", "B2", "статистический показатель", "statistical key figure", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("der Innenauftrag, die Innenaufträge", "Noun", "B2", "внутренний заказ", "internal order", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Abrechnung, die Abrechnungen", "Noun", "B2", "расчет / калькуляция / расчет заказа", "settlement / billing", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Ergebnisrechnung, die Rechnungen", "Noun", "B2", "учет результатов (CO-PA)", "profitability analysis (CO-PA)", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("das Profit-Center-Accounting, (nur Sg.)", "Noun", "B2", "учет по центрам прибыли (EC-PCA)", "profit center accounting", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Konsolidierung, die Konsolidierungen", "Noun", "B2", "консолидация", "consolidation", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Abschreibung, die Abschreibungen", "Noun", "B2", "амортизация", "depreciation", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("der Anlagenspiegel, die Anlagenspiegel", "Noun", "B2", "ведомость движения основных средств", "asset history sheet", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Anschaffungskosten, (nur Pl.)", "Noun", "B2", "первоначальная стоимость (ОС)", "acquisition costs", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("der Buchwert, die Buchwerte", "Noun", "B2", "балансовая стоимость", "book value", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Anzahlung, die Anzahlungen", "Noun", "B1", "авансовый платеж / предоплата", "down payment", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Schlussrechnung, die Schlussrechnungen", "Noun", "B2", "финальный счет", "final invoice", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die offene Posten, (nur Pl.)", "Noun", "B2", "открытые позиции", "open items", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("mahnen", "Verb", "B2", "напоминать о платеже / слать претензии", "to dun / send reminder", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("das Mahnverfahren, die Mahnverfahren", "Noun", "B2", "процедура напоминания платежей", "dunning procedure", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("der Mahnlauf, die Mahnläufe", "Noun", "B2", "прогон программы напоминаний", "dunning run", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("der Zahllauf, die Zahlläufe", "Noun", "B2", "прогон программы платежей", "payment run", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Bankverbindung, die Bankverbindungen", "Noun", "B1", "банковские реквизиты", "bank details", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("der Kontoauszug, die Kontoauszüge", "Noun", "B1", "выписка по счету", "bank statement", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("das Übergangskonto, die Übergangskonten", "Noun", "B2", "транзитный счет", "clearing account", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Abstimmvereinbarung, die Abstimmvereinbarungen", "Noun", "B2", "соглашение о выравнивании", "reconciliation agreement", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("das Abstimmkonto, die Abstimmkonten", "Noun", "B2", "контрольный счет", "reconciliation account", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("der Kontenplan, die Kontenpläne", "Noun", "B2", "план счетов", "chart of accounts", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Saldovortrag, die Saldovorträge", "Noun", "B2", "перенос сальдо", "balance carryforward", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Umsatzsteuer, die Umsatzsteuern", "Noun", "B2", "налог с оборота / НДС", "sales tax / VAT", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Vorsteuer, die Vorsteuern", "Noun", "B2", "входящий НДС", "input tax", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Zahllast, die Zahllasten", "Noun", "B2", "сумма налога к уплате", "tax liability", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("stornieren", "Verb", "B1", "стонировать / аннулировать", "to reverse / cancel", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Stornierung, die Stornierungen", "Noun", "B1", "сторнирование / красное сторно", "reversal / cancellation", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("der Buchungsbeleg, die Buchungsbelege", "Noun", "B2", "бухгалтерский документ", "accounting document", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("das Sachkontenbuch, die Sachkontenbücher", "Noun", "B2", "регистр счетов главной книги", "G/L ledger", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Belegaufteilung, die Belegaufteilungen", "Noun", "B2", "разделение документа (document splitting)", "document splitting", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("das Segment, die Segmente", "Noun", "B2", "сегмент", "segment", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("der Funktionsbereich, die Funktionsbereiche", "Noun", "B2", "функциональная сфера", "functional area", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Konzernwährung, die Konzernwährungen", "Noun", "B2", "концерновая валюта", "group currency", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Kreiswährung, die Kreiswährungen", "Noun", "B2", "местная валюта", "local currency", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Fremdwährung, die Fremdwährungen", "Noun", "B2", "иностранная валюта", "foreign currency", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Fremdwährungsbewertung, die Bewertungen", "Noun", "B2", "оценка в иностранной валюте", "foreign currency valuation", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("das Kursdifferenzkonto, die Kursdifferenzkonten", "Noun", "B2", "счет курсовых разниц", "exchange rate difference account", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("das Intercompany-Geschäft, die Geschäfte", "Noun", "B2", "межфилиальные / межкомпанейские сделки", "intercompany transaction", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Verrechnung, die Verrechnungen", "Noun", "B2", "взаимозачет / аллокация / распределение", "allocation / clearing", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Kostenstellen-Gruppe, die Gruppen", "Noun", "B2", "группа мест возникновения затрат", "cost center group", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Profit-Center-Gruppe, die Gruppen", "Noun", "B2", "группа центров прибыли", "profit center group", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Standardhierarchie, die Standardhierarchien", "Noun", "B2", "стандартная иерархия", "standard hierarchy", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Plankalkulation, die Plankalkulationen", "Noun", "B2", "плановая калькуляция", "planned costing", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Istkalkulation, die Istkalkulationen", "Noun", "B2", "фактическая калькуляция", "actual costing", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Tarifermittlung, die Tarifermittlungen", "Noun", "B2", "расчет тарифа", "activity price calculation", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Abweichungsanalyse, die Abweichungsanalysen", "Noun", "B2", "анализ отклонений", "variance analysis", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Deckungsbeitragsrechnung, die Rechnungen", "Noun", "B2", "учет сумм покрытия (маржинальный доход)", "contribution margin accounting", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("der Buchungsschlüssel, die Buchungsschlüssel", "Noun", "B2", "ключ проводки", "posting key", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("das Soll, (nur Sg.)", "Noun", "B2", "дебет", "debit", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("das Haben, (nur Sg.)", "Noun", "B2", "кредит (бухгалтерский)", "credit", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("der Saldo, die Salden", "Noun", "B2", "сальдо", "balance", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Abstimmungsarbeit, die Abstimmungsarbeiten", "Noun", "B2", "работа по согласованию / сверке", "reconciliation work", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Abschlussarbeiten, (nur Pl.)", "Noun", "B2", "операции закрытия периода", "closing operations", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("der Monatsabschluss, die Monatsabschlüsse", "Noun", "B2", "закрытие месяца", "month-end closing", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("der Jahresabschluss, die Jahresabschlüsse", "Noun", "B2", "закрытие года", "year-end closing", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("das Kreditlimit, die Kreditlimits", "Noun", "B2", "кредитный лимит", "credit limit", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Kreditkontrolle, die Kreditkontrollen", "Noun", "B2", "кредитный контроль", "credit control", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("der Zahlungsbeleg, die Zahlungsbelege", "Noun", "B2", "платежный документ", "payment document", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Zahlungsbedingung, die Zahlungsbedingungen", "Noun", "B2", "условие платежа", "terms of payment", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("das Skonto, die Skontos", "Noun", "B2", "скидка за быструю оплату", "cash discount", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("der Verzugszins, die Verzugszinsen", "Noun", "B2", "процент за просрочку платежа", "interest on arrears", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Wertberichtigung, die Wertberichtigungen", "Noun", "B2", "корректировка стоимости", "value adjustment", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Rückstellung, die Rückstellungen", "Noun", "B2", "резерв (на будущие обязательства)", "accrual / provision", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Rechnungsabgrenzung, die Rechnungsabgrenzungen", "Noun", "B2", "разграничение доходов и расходов", "accruals and deferrals", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Anzahlungsanforderung, die Anzahlungsanforderungen", "Noun", "B2", "запрос авансового платежа", "down payment request", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Steuererklärung, die Steuererklärungen", "Noun", "B2", "налоговая декларация", "tax return", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Umsatzsteuer-Voranmeldung, die Voranmeldungen", "Noun", "B2", "предварительная декларация по НДС", "advance return for tax on sales/purchases", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("das Steuerkennzeichen, die Steuerkennzeichen", "Noun", "B2", "код налога", "tax code", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Anlagenklasse, die Anlagenklassen", "Noun", "B2", "класс основных средств", "asset class", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("die Nutzungsdauer, die Nutzungsdauern", "Noun", "B2", "срок полезного использования", "useful life", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("der Abschreibungsbereich, die Abschreibungsbereiche", "Noun", "B2", "область амортизации", "depreciation area", "SAP FI/CO (Finanzwesen & Controlling)"),
    ("der Abschreibungsschlüssel, die Abschreibungsschlüssel", "Noun", "B2", "код амортизации", "depreciation key", "SAP FI/CO (Finanzwesen & Controlling)"),

    # Category 2: Materialwirtschaft & Bestandsbewertung (MM/ML) (101-200)
    ("das Material-Ledger, die Material-Ledger", "Noun", "B2", "регистр материалов", "material ledger", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Materialbewertung, die Materialbewertungen", "Noun", "B2", "оценка материала", "material valuation", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der gleitende Durchschnittspreis, die Durchschnittspreise", "Noun", "B2", "среднескользящая цена", "moving average price", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der Standardpreis, die Standardpreise", "Noun", "B2", "стандартная цена", "standard price", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Preissteuerung, die Preissteuerungen", "Noun", "B2", "управление ценой", "price control", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Umbewertung, die Umbewertungen", "Noun", "B2", "переоценка", "revaluation", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Ist-Kalkulation, die Ist-Kalkulationen", "Noun", "B2", "фактическая калькуляция", "actual costing", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der Materialbeleg, die Materialbelege", "Noun", "B2", "документ материала", "material document", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Materialart, die Materialarten", "Noun", "B2", "вид материала", "material type", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Warengruppe, die Warengruppen", "Noun", "B2", "товарная группа", "material group", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Bewertungsebene, die Bewertungsebenen", "Noun", "B2", "уровень оценки", "valuation level", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der Bewertungskreis, die Bewertungskreise", "Noun", "B2", "область оценки", "valuation area", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Bewertungsklasse, die Bewertungsklassen", "Noun", "B2", "класс оценки", "valuation class", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Kontenfindung, die Kontenfindungen", "Noun", "B2", "определение счетов", "account determination", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die automatische Kontenfindung, die Kontenfindungen", "Noun", "B2", "автоматический выбор счетов", "automatic account determination", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der Lagerort, die Lagerorte", "Noun", "B2", "склад / место хранения", "storage location", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("das Werk, die Werke", "Noun", "B1", "завод", "plant", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der Bestand, die Bestände", "Noun", "B2", "запас / остаток", "stock / inventory", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Bestandsveränderung, die Bestandsveränderungen", "Noun", "B2", "изменение запасов", "changes in inventories", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Bestandsbuchung, die Bestandsbuchungen", "Noun", "B2", "проводка запасов", "inventory posting", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Inventur, die Inventuren", "Noun", "B2", "инвентаризация", "physical inventory", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Inventurdifferenz, die Inventurdifferenzen", "Noun", "B2", "инвентаризационная разница", "inventory difference", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der Wareneingang, die Wareneingänge", "Noun", "B2", "поступление материала (ПМ)", "goods receipt (GR)", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der Warenausgang, die Warenausgänge", "Noun", "B2", "отпуск материала (ОМ)", "goods issue (GI)", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Umlagerung, die Umlagerungen", "Noun", "B2", "перемещение запасов", "stock transfer", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Umbuchung, die Umbuchungen", "Noun", "B2", "перенос проводки / изменение статуса", "transfer posting", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Materialbuchung, die Materialbuchungen", "Noun", "B2", "проводка материала", "material posting", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die WE/RE-Abstimmung, die Abstimmungen", "Noun", "B2", "сверка ПМ/Сchild (поступление материала/счет)", "GR/IR reconciliation", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("das WE/RE-Verrechnungskonto, die Verrechnungskonten", "Noun", "B2", "счет перерасчета ПМ/Счет (GR/IR)", "GR/IR clearing account", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der Sonderbestand, die Sonderbestände", "Noun", "B2", "особый запас", "special stock", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der Konsignationsbestand, die Konsignationsbestände", "Noun", "B2", "консигнационный запас", "consignment stock", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der Kundenauftragsbestand, die Bestände", "Noun", "B2", "запас для заказа клиента", "sales order stock", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der Projektbestand, die Projektbestände", "Noun", "B2", "запас проекта", "project stock", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Chargenverwaltung, die Chargenverwaltungen", "Noun", "B2", "управление партиями", "batch management", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Charge, die Chargen", "Noun", "B2", "партия", "batch", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Serialnummer, die Serialnummern", "Noun", "B2", "серийный номер", "serial number", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Verwendbarkeit, (nur Sg.)", "Noun", "B2", "применимость / годность", "usability / shelf life", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("das Verfallsdatum, die Verfallsdaten", "Noun", "B2", "срок годности", "expiration date", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("das Mindesthaltbarkeitsdatum, die Daten", "Noun", "B2", "минимальный срок годности", "shelf life expiration date", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Qualitätsprüfung, die Qualitätsprüfungen", "Noun", "B2", "контроль качества", "quality inspection", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der Prüfbestand, die Prüfbestände", "Noun", "B2", "запас на контроле качества", "quality inspection stock", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der gesperrte Bestand, die Bestände", "Noun", "B2", "блокированный запас", "blocked stock", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der frei verwendbare Bestand, die Bestände", "Noun", "B2", "свободно используемый запас", "unrestricted-use stock", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Bestandsart, die Bestandsarten", "Noun", "B2", "вид запаса", "stock type", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Bewegungsart, die Bewegungsarten", "Noun", "B2", "вид движения (запасов)", "movement type", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Bestandsunterdeckung, die Unterdeckungen", "Noun", "B2", "дефицит запасов", "stock deficit", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Bedarfsplanung, die Bedarfsplanungen", "Noun", "B2", "планирование потребностей (MRP)", "material requirements planning (MRP)", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Disposition, die Dispositionen", "Noun", "B2", "диспетчеризация / планирование запасов", "material planning", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der Disponent, die Disponenten", "Noun", "B2", "планировщик / диспетчер", "material planner", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der Sicherheitsbestand, die Sicherheitsbestände", "Noun", "B2", "страховой запас", "safety stock", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der Meldebestand, die Meldebestände", "Noun", "B2", "точка заказа / пороговый запас", "reorder point", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Losgröße, die Losgrößen", "Noun", "B2", "размер партии (заказа)", "lot size", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Mindestbestellmenge, die Mindestbestellmengen", "Noun", "B2", "минимальный объем заказа", "minimum order quantity", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("das Materialstammblatt, die Materialstammblätter", "Noun", "B2", "основная запись материала", "material master record", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Materialnummer, die Materialnummern", "Noun", "B2", "номер материала", "material number", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Mengeneinheit, die Mengeneinheiten", "Noun", "B1", "единица измерения", "unit of measure", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Basismengeneinheit, die Mengeneinheiten", "Noun", "B2", "базовая единица измерения", "base unit of measure", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Alternativmengeneinheit, die Mengeneinheiten", "Noun", "B2", "альтернативная единица измерения", "alternative unit of measure", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Umrechnung, die Umrechnungen", "Noun", "B2", "перерасчет / конвертация", "conversion", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Stückliste, die Stücklisten", "Noun", "B2", "спецификация (BOM)", "bill of materials (BOM)", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Baugruppe, die Baugruppen", "Noun", "B2", "узел / сборка", "assembly / subassembly", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("das Halbfabrikat, die Halbfabrikate", "Noun", "B2", "полуфабрикат", "semi-finished product", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("das Fertigerzeugnis, die Fertigerzeugnisse", "Noun", "B2", "готовое изделие", "finished product", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der Rohstoff, die Rohstoffe", "Noun", "B2", "сырье / исходный материал", "raw material", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("das Handelsgut, die Handelsgüter", "Noun", "B2", "товар для перепродажи", "trading goods", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Verpackung, die Verpackungen", "Noun", "B1", "упаковка", "packaging", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("das Packmittel, die Packmittel", "Noun", "B2", "упаковочный материал", "packaging material", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Chargenklasse, die Chargenklassen", "Noun", "B2", "класс партий", "batch class", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Bewertung für geteilte Bestände, die Bewertungen", "Noun", "B2", "раздельная оценка запасов", "split valuation", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Bewertungsart, die Bewertungsarten", "Noun", "B2", "вид оценки (при раздельной оценке)", "valuation type", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Herkunft, die Herkünfte", "Noun", "B2", "происхождение (страна/источник)", "origin", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("das Zollverfahren, die Zollverfahren", "Noun", "B2", "таможенная процедура", "customs procedure", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Zollanmeldung, die Zollanmeldungen", "Noun", "B2", "таможенная декларация", "customs declaration", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Lagerverwaltung, die Lagerverwaltungen", "Noun", "B2", "управление складом (WM/EWM)", "warehouse management", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("das Lager, die Lager", "Noun", "B1", "склад", "warehouse / store", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Lagernummer, die Lagernummern", "Noun", "B2", "номер склада", "warehouse number", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der Lagertyp, die Lagertypen", "Noun", "B2", "тип склада", "storage type", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der Lagerbereich, die Lagerbereiche", "Noun", "B2", "складская секция", "storage section", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der Lagerplatz, die Lagerplätze", "Noun", "B2", "складское место / ячейка", "storage bin", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("das Transport-Management, (nur Sg.)", "Noun", "B2", "управление транспортировками (TM)", "transport management", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der Transportbedarf, die Transportbedarfe", "Noun", "B2", "потребность в переносе (TR)", "transfer requirement", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der Transportauftrag, die Transportaufträge", "Noun", "B2", "заказ на перенос (TO)", "transfer order", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Quittierung, die Quittierungen", "Noun", "B2", "подтверждение (заказа на перенос)", "confirmation", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("quittieren", "Verb", "B2", "подтверждать / квитировать", "to confirm / acknowledge", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Bestandsdifferenz, die Bestandsdifferenzen", "Noun", "B2", "разница в запасах", "stock difference", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("das Schnittstellenkonto, die Schnittstellenkonten", "Noun", "B2", "промежуточный счет / интерфейсный счет", "interface account", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der physische Bestand, die Bestände", "Noun", "B2", "фактический (физический) запас", "physical stock", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der Buchbestand, die Buchbestände", "Noun", "B2", "книжный запас (по данным системы)", "book inventory", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Inventuraufnahme, die Inventuraufnahmen", "Noun", "B2", "инвентаризационная опись", "physical inventory count", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Nachzählung, die Nachzählungen", "Noun", "B2", "повторный подсчет", "re-count", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("abgleichen", "Verb", "B2", "сверять / сопоставлять", "to reconcile / match", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der Abgleich, die Abgleiche", "Noun", "B2", "сверка / сопоставление", "reconciliation / comparison", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("bewerten", "Verb", "B1", "оценивать", "to evaluate / value", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("der Bewertungspreis, die Bewertungspreise", "Noun", "B2", "цена оценки", "valuation price", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("das Bewertungsverfahren, die Bewertungsverfahren", "Noun", "B2", "метод оценки", "valuation method", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die FIFO-Methode, (nur Sg.)", "Noun", "B2", "метод ФИФО", "FIFO method", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die LIFO-Methode, (nur Sg.)", "Noun", "B2", "метод ЛИФО", "LIFO method", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Anschaffungskosten, (nur Pl.)", "Noun", "B2", "затраты на приобретение", "acquisition costs", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("die Herstellungskosten, (nur Pl.)", "Noun", "B2", "производственная себестоимость", "cost of goods manufactured", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),
    ("das Periodenende, die Periodenenden", "Noun", "B2", "конец периода", "period end", "Materialwirtschaft & Bestandsbewertung (MM/ML)"),

    # Category 3: Vertrieb & Kundenmanagement (SD) (201-300)
    ("der Kundenauftrag, die Kundenaufträge", "Noun", "B2", "заказ клиента", "sales order", "Vertrieb & Kundenmanagement (SD)"),
    ("die Lieferung, die Lieferungen", "Noun", "B1", "поставка", "delivery", "Vertrieb & Kundenmanagement (SD)"),
    ("die Faktura, die Fakturen", "Noun", "B2", "фактура / счет-фактура", "billing document / invoice", "Vertrieb & Kundenmanagement (SD)"),
    ("fakturieren", "Verb", "B2", "выставлять счет-фактуру", "to bill / invoice", "Vertrieb & Kundenmanagement (SD)"),
    ("die Vertriebslinie, die Vertriebslinien", "Noun", "B2", "канал сбыта / сбытовая линия", "sales line / distribution channel", "Vertrieb & Kundenmanagement (SD)"),
    ("der Vertriebskanal, die Vertriebskanäle", "Noun", "B2", "канал сбыта", "distribution channel", "Vertrieb & Kundenmanagement (SD)"),
    ("die Sparte, die Sparten", "Noun", "B2", "сектор деятельности / сектор сбыта", "division", "Vertrieb & Kundenmanagement (SD)"),
    ("die Verkaufsorganisation, die Verkaufsorganisationen", "Noun", "B2", "сбытовая организация", "sales organization", "Vertrieb & Kundenmanagement (SD)"),
    ("der Vertriebsbereich, die Vertriebsbereiche", "Noun", "B2", "сектор сбыта (продаж)", "sales area", "Vertrieb & Kundenmanagement (SD)"),
    ("die Vertriebsorganisation, die Vertriebsorganisationen", "Noun", "B2", "сбытовая организация", "sales organization", "Vertrieb & Kundenmanagement (SD)"),
    ("die Versandstelle, die Versandstellen", "Noun", "B2", "пункт отгрузки", "shipping point", "Vertrieb & Kundenmanagement (SD)"),
    ("der Lieferbeleg, die Lieferbelege", "Noun", "B2", "документ поставки", "delivery document", "Vertrieb & Kundenmanagement (SD)"),
    ("die Auslieferung, die Auslieferungen", "Noun", "B2", "исходящая поставка", "outbound delivery", "Vertrieb & Kundenmanagement (SD)"),
    ("die Anlieferung, die Anlieferungen", "Noun", "B2", "входящая поставка", "inbound delivery", "Vertrieb & Kundenmanagement (SD)"),
    ("der Warenausgang, die Warenausgänge", "Noun", "B2", "отпуск материала (ОМ)", "goods issue", "Vertrieb & Kundenmanagement (SD)"),
    ("buchen", "Verb", "B1", "проводить (проводку)", "to post", "Vertrieb & Kundenmanagement (SD)"),
    ("das Angebot, die Angebote", "Noun", "B1", "коммерческое предложение", "quotation / offer", "Vertrieb & Kundenmanagement (SD)"),
    ("die Anfrage, die Anfragen", "Noun", "B1", "запрос", "inquiry", "Vertrieb & Kundenmanagement (SD)"),
    ("die Kontraktverwaltung, die Kontraktverwaltungen", "Noun", "B2", "управление контрактами", "contract management", "Vertrieb & Kundenmanagement (SD)"),
    ("der Kontrakt, die Kontrakte", "Noun", "B2", "контракт / договор", "contract", "Vertrieb & Kundenmanagement (SD)"),
    ("der Mengenkontrakt, die Mengenkontrakte", "Noun", "B2", "количественный контракт", "quantity contract", "Vertrieb & Kundenmanagement (SD)"),
    ("der Wertkontrakt, die Wertkontrakte", "Noun", "B2", "стоимостный контракт", "value contract", "Vertrieb & Kundenmanagement (SD)"),
    ("der Lieferplan, die Lieferpläne", "Noun", "B2", "соглашение о поставках / график поставок", "scheduling agreement", "Vertrieb & Kundenmanagement (SD)"),
    ("die Einteilung, die Einteilungen", "Noun", "B2", "партия поставки (строка графика)", "schedule line", "Vertrieb & Kundenmanagement (SD)"),
    ("die Partnerrolle, die Partnerrollen", "Noun", "B2", "роль партнера", "partner function", "Vertrieb & Kundenmanagement (SD)"),
    ("der Auftraggeber, die Auftraggeber", "Noun", "B2", "заказчик (участник сделки)", "sold-to party", "Vertrieb & Kundenmanagement (SD)"),
    ("der Warenempfänger, die Warenempfänger", "Noun", "B2", "получатель материала", "ship-to party", "Vertrieb & Kundenmanagement (SD)"),
    ("der Rechnungsempfänger, die Rechnungsempfänger", "Noun", "B2", "получатель счета", "bill-to party", "Vertrieb & Kundenmanagement (SD)"),
    ("der Regulierer, die Regulierer", "Noun", "B2", "плательщик", "payer", "Vertrieb & Kundenmanagement (SD)"),
    ("der Ansprechpartner, die Ansprechpartner", "Noun", "B1", "контактное лицо", "contact person", "Vertrieb & Kundenmanagement (SD)"),
    ("die Preisfindung, die Preisfindungen", "Noun", "B2", "ценообразование", "pricing", "Vertrieb & Kundenmanagement (SD)"),
    ("das Kalkulationsschema, die Kalkulationsschemata", "Noun", "B2", "схема калькуляции", "pricing procedure", "Vertrieb & Kundenmanagement (SD)"),
    ("die Konditionsart, die Konditionsarten", "Noun", "B2", "вид условия", "condition type", "Vertrieb & Kundenmanagement (SD)"),
    ("der Konditionssatz, die Konditionssätze", "Noun", "B2", "запись условия", "condition record", "Vertrieb & Kundenmanagement (SD)"),
    ("die Konditionstabelle, die Konditionstabellen", "Noun", "B2", "таблица условий", "condition table", "Vertrieb & Kundenmanagement (SD)"),
    ("die Zugriffsfolge, die Zugriffsfolgen", "Noun", "B2", "последовательность доступа", "access sequence", "Vertrieb & Kundenmanagement (SD)"),
    ("der Rabatt, die Rabatte", "Noun", "B1", "скидка", "discount", "Vertrieb & Kundenmanagement (SD)"),
    ("der Zuschlag, die Zuschläge", "Noun", "B2", "наценка / доплата", "surcharge", "Vertrieb & Kundenmanagement (SD)"),
    ("die Frachtkosten, (nur Pl.)", "Noun", "B2", "расходы на транспортировку", "freight costs", "Vertrieb & Kundenmanagement (SD)"),
    ("die Steuer, die Steuern", "Noun", "B1", "налог", "tax", "Vertrieb & Kundenmanagement (SD)"),
    ("die Verfügbarkeitsprüfung, die Verfügbarkeitsprüfungen", "Noun", "B2", "проверка доступности (ATP)", "availability check (ATP)", "Vertrieb & Kundenmanagement (SD)"),
    ("der Kundenauftragsbestand, die Bestände", "Noun", "B2", "запас для заказа клиента", "sales order stock", "Vertrieb & Kundenmanagement (SD)"),
    ("die Streckenabwicklung, die Streckenabwicklungen", "Noun", "B2", "транзитная поставка (третьим лицам)", "third-party order processing", "Vertrieb & Kundenmanagement (SD)"),
    ("die Umlagerungsbestellung, die Umlagerungsbestellungen", "Noun", "B2", "заказ на перемещение запаса", "stock transport order", "Vertrieb & Kundenmanagement (SD)"),
    ("der Konsignationsbeschaffung, (nur Sg.)", "Noun", "B2", "пополнение консигнационного запаса", "consignment replenishment", "Vertrieb & Kundenmanagement (SD)"),
    ("die Konsignationsentnahme, die Entnahmen", "Noun", "B2", "отпуск с консигнационного запаса", "consignment issue", "Vertrieb & Kundenmanagement (SD)"),
    ("die Konsignationsbeschickung, die Beschickungen", "Noun", "B2", "поставка на консигнацию", "consignment fill-up", "Vertrieb & Kundenmanagement (SD)"),
    ("die Konsignationsrücknahme, die Rücknahmen", "Noun", "B2", "возврат с консигнации", "consignment pick-up", "Vertrieb & Kundenmanagement (SD)"),
    ("die Retoure, die Retouren", "Noun", "B2", "возврат товара", "return", "Vertrieb & Kundenmanagement (SD)"),
    ("die Retourenabwicklung, die Retourenabwicklungen", "Noun", "B2", "обработка возвратов", "returns processing", "Vertrieb & Kundenmanagement (SD)"),
    ("die Gutschrift, die Gutschriften", "Noun", "B2", "кредитовое авизо / кредит", "credit memo", "Vertrieb & Kundenmanagement (SD)"),
    ("die Lastschrift, die Lastschriften", "Noun", "B2", "дебетовое авизо", "debit memo", "Vertrieb & Kundenmanagement (SD)"),
    ("die Gutschriftenanforderung, die Gutschriftenanforderungen", "Noun", "B2", "запрос кредитового авизо", "credit memo request", "Vertrieb & Kundenmanagement (SD)"),
    ("die Lastschriftenanforderung, die Lastschriftenanforderungen", "Noun", "B2", "запрос дебетового авизо", "debit memo request", "Vertrieb & Kundenmanagement (SD)"),
    ("die Fakturasperre, die Fakturasperren", "Noun", "B2", "блокировка фактурирования", "billing block", "Vertrieb & Kundenmanagement (SD)"),
    ("die Liefersperre, die Liefersperren", "Noun", "B2", "блокировка поставки", "delivery block", "Vertrieb & Kundenmanagement (SD)"),
    ("die Kreditprüfung, die Kreditprüfungen", "Noun", "B2", "проверка кредитного лимита", "credit limit check", "Vertrieb & Kundenmanagement (SD)"),
    ("die Kreditsperre, die Kreditsperren", "Noun", "B2", "кредитная блокировка", "credit block", "Vertrieb & Kundenmanagement (SD)"),
    ("das Kreditmanagement, (nur Sg.)", "Noun", "B2", "управление кредитами (FSCM)", "credit management", "Vertrieb & Kundenmanagement (SD)"),
    ("der Bonitätsindex, die Bonitätsindizes", "Noun", "B2", "индекс платежеспособности", "credit rating index", "Vertrieb & Kundenmanagement (SD)"),
    ("die Bonitätsprüfung, die Bonitätsprüfungen", "Noun", "B2", "проверка кредитоспособности", "creditworthiness check", "Vertrieb & Kundenmanagement (SD)"),
    ("der Kundenstamm, die Kundenstämme", "Noun", "B2", "основные данные клиента", "customer master record", "Vertrieb & Kundenmanagement (SD)"),
    ("der Debitorenstamm, die Debitorenstämme", "Noun", "B2", "основная запись дебитора", "customer master", "Vertrieb & Kundenmanagement (SD)"),
    ("der Geschäftspartner, die Geschäftspartner", "Noun", "B2", "деловой партнер (BP)", "business partner (BP)", "Vertrieb & Kundenmanagement (SD)"),
    ("die GP-Rolle, die GP-Rollen", "Noun", "B2", "роль делового партнера", "business partner function", "Vertrieb & Kundenmanagement (SD)"),
    ("die Kontengruppe, die Kontengruppen", "Noun", "B2", "группа счетов", "account group", "Vertrieb & Kundenmanagement (SD)"),
    ("der Nummernkreis, die Nummernkreise", "Noun", "B2", "диапазон номеров", "number range", "Vertrieb & Kundenmanagement (SD)"),
    ("die Nachrichtenfindung, die Nachrichtenfindungen", "Noun", "B2", "определение выходных документов", "output determination", "Vertrieb & Kundenmanagement (SD)"),
    ("die Nachricht, die Nachrichten", "Noun", "B1", "сообщение / выходной документ", "output / message", "Vertrieb & Kundenmanagement (SD)"),
    ("das Sendemedium, die Sendemedien", "Noun", "B2", "средство отправки", "transmission medium", "Vertrieb & Kundenmanagement (SD)"),
    ("der Drucker, die Drucker", "Noun", "B1", "принтер", "printer", "Vertrieb & Kundenmanagement (SD)"),
    ("der Spool-Auftrag, die Spool-Aufträge", "Noun", "B2", "запрос на печать (спул)", "spool request", "Vertrieb & Kundenmanagement (SD)"),
    ("das Versanddokument, die Versanddokumente", "Noun", "B2", "отгрузочный документ", "shipping document", "Vertrieb & Kundenmanagement (SD)"),
    ("der Lieferschein, die Lieferscheine", "Noun", "B2", "накладная на поставку", "delivery note", "Vertrieb & Kundenmanagement (SD)"),
    ("die Frachtbrief, die Frachtbriefe", "Noun", "B2", "транспортная накладная", "consignment note / waybill", "Vertrieb & Kundenmanagement (SD)"),
    ("die Packliste, die Packlisten", "Noun", "B2", "упаковочный лист", "packing list", "Vertrieb & Kundenmanagement (SD)"),
    ("das Transportmittel, die Transportmittel", "Noun", "B2", "транспортное средство", "means of transport", "Vertrieb & Kundenmanagement (SD)"),
    ("die Route, die Routen", "Noun", "B2", "маршрут", "route", "Vertrieb & Kundenmanagement (SD)"),
    ("die Routenfindung, die Routenfindungen", "Noun", "B2", "определение маршрута", "route determination", "Vertrieb & Kundenmanagement (SD)"),
    ("die Versandbedingung, die Versandbedingungen", "Noun", "B2", "условие отгрузки", "shipping condition", "Vertrieb & Kundenmanagement (SD)"),
    ("die Ladegruppe, die Ladegruppen", "Noun", "B2", "группа погрузки", "loading group", "Vertrieb & Kundenmanagement (SD)"),
    ("die Transportgruppe, die Transportgruppen", "Noun", "B2", "транспортная группа", "transportation group", "Vertrieb & Kundenmanagement (SD)"),
    ("das Belegflussschema, die Belegflussschemata", "Noun", "B2", "структура потока документов", "document flow diagram", "Vertrieb & Kundenmanagement (SD)"),
    ("der Belegfluss, die Belegflüsse", "Noun", "B2", "поток документов", "document flow", "Vertrieb & Kundenmanagement (SD)"),
    ("der Status, die Status", "Noun", "B2", "статус", "status", "Vertrieb & Kundenmanagement (SD)"),
    ("vollständig", "Adjective", "B1", "полный / завершенный", "complete", "Vertrieb & Kundenmanagement (SD)"),
    ("offen", "Adjective", "B1", "открытый (о заказе)", "open", "Vertrieb & Kundenmanagement (SD)"),
    ("in Bearbeitung", "Phrase", "B1", "в процессе обработки", "in process", "Vertrieb & Kundenmanagement (SD)"),
    ("die Reklamation, die Reklamationen", "Noun", "B2", "рекламация / жалоба", "complaint / claim", "Vertrieb & Kundenmanagement (SD)"),
    ("das Retouren-Material, die Materialien", "Noun", "B2", "возвращаемый материал", "returned material", "Vertrieb & Kundenmanagement (SD)"),
    ("die Erstattung, die Erstattungen", "Noun", "B2", "возмещение / компенсация", "refund / reimbursement", "Vertrieb & Kundenmanagement (SD)"),
    ("erstatten", "Verb", "B2", "возмещать / компенсировать", "to refund / reimburse", "Vertrieb & Kundenmanagement (SD)"),
    ("die Gutschriftsanforderung, die Gutschriftsanforderungen", "Noun", "B2", "запрос кредитового авизо", "credit memo request", "Vertrieb & Kundenmanagement (SD)"),
    ("die Preiskondition, die Preiskonditionen", "Noun", "B2", "ценовое условие", "price condition", "Vertrieb & Kundenmanagement (SD)"),
    ("der Nettowert, die Nettowerte", "Noun", "B2", "чистая стоимость", "net value", "Vertrieb & Kundenmanagement (SD)"),
    ("der Bruttowert, die Bruttowerte", "Noun", "B2", "стоимость брутто", "gross value", "Vertrieb & Kundenmanagement (SD)"),
    ("die Währungsdifferenz, die Währungsdifferenzen", "Noun", "B2", "валютная разница", "currency difference", "Vertrieb & Kundenmanagement (SD)"),
    ("der Wechselkurs, die Wechselkurse", "Noun", "B2", "валютный курс", "exchange rate", "Vertrieb & Kundenmanagement (SD)"),
    ("die Vertriebsbelege, (nur Pl.)", "Noun", "B2", "сбытовые документы", "sales documents", "Vertrieb & Kundenmanagement (SD)"),
    ("die Liefertreue, (nur Sg.)", "Noun", "B2", "надежность поставок / соблюдение сроков поставки", "delivery reliability", "Vertrieb & Kundenmanagement (SD)"),

    # Category 4: S4 HANA & Fiori Benutzeroberfläche (301-400)
    ("die Fiori-App, die Fiori-Apps", "Noun", "B2", "приложение Fiori", "Fiori app", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Launchpad-Kachel, die Launchpad-Kacheln", "Noun", "B2", "плитка Launchpad (панели запуска)", "launchpad tile", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Benutzeroberfläche, die Benutzeroberflächen", "Noun", "B2", "интерфейс пользователя", "user interface (UI)", "S4 HANA & Fiori Benutzeroberfläche"),
    ("das Universal-Journal, die Universal-Journale", "Noun", "B2", "единый журнал проводок (ACDOCA)", "universal journal", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die In-Memory-Datenbank, die Datenbanken", "Noun", "B2", "база данных в оперативной памяти", "in-memory database", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Echtzeit-Datenverarbeitung, (nur Sg.)", "Noun", "B2", "обработка данных в реальном времени", "real-time data processing", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Spaltenorientierung, (nur Sg.)", "Noun", "B2", "колоночное / поколоночное хранение данных", "column orientation", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Zeilenorientierung, (nur Sg.)", "Noun", "B2", "построчное хранение данных", "row orientation", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Tabelle, die Tabellen", "Noun", "B1", "таблица", "table", "S4 HANA & Fiori Benutzeroberfläche"),
    ("das Datenmodell, die Datenmodelle", "Noun", "B2", "модель данных", "data model", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Redundanz, die Redundanzen", "Noun", "B2", "избыточность (данных)", "redundancy", "S4 HANA & Fiori Benutzeroberfläche"),
    ("redundanzfrei", "Adjective", "B2", "без избыточности", "redundancy-free", "S4 HANA & Fiori Benutzeroberfläche"),
    ("das Hauptbuch-Journal, die Journale", "Noun", "B2", "журнал главной книги", "general ledger journal", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Einzelposten-Tabelle, die Tabellen", "Noun", "B2", "таблица позиций документа (ACDOCA)", "line item table", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Aggregation, die Aggregationen", "Noun", "B2", "агрегация / суммирование", "aggregation", "S4 HANA & Fiori Benutzeroberfläche"),
    ("aggregieren", "Verb", "B2", "агрегировать / суммировать", "to aggregate", "S4 HANA & Fiori Benutzeroberfläche"),
    ("der Index, die Indizes", "Noun", "B2", "индекс", "index", "S4 HANA & Fiori Benutzeroberfläche"),
    ("der Performance-Gewinn, die Performance-Gewinne", "Noun", "B2", "прирост производительности", "performance gain", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Ladezeit, die Ladezeiten", "Noun", "B2", "время загрузки", "loading time", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Cloud-Variante, die Cloud-Varianten", "Noun", "B2", "облачная версия", "cloud variant", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die On-Premise-Variante, die On-Premise-Varianten", "Noun", "B2", "локальная версия (на собственных серверах)", "on-premise variant", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Hybrid-Lösung, die Hybrid-Lösungen", "Noun", "B2", "гибридное решение", "hybrid solution", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Fiori-Kachel, die Fiori-Kacheln", "Noun", "B2", "плитка Fiori", "Fiori tile", "S4 HANA & Fiori Benutzeroberfläche"),
    ("das Launchpad, die Launchpads", "Noun", "B2", "панель запуска Fiori", "launchpad", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die App-Gruppe, die App-Gruppen", "Noun", "B2", "группа приложений", "app group", "S4 HANA & Fiori Benutzeroberfläche"),
    ("der App-Store, die App-Stores", "Noun", "B2", "библиотека приложений Fiori", "app library / store", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Personalisierung, die Personalisierungen", "Noun", "B2", "персонализация / настройка под себя", "personalization", "S4 HANA & Fiori Benutzeroberfläche"),
    ("personalisieren", "Verb", "B2", "настраивать под себя / персонализировать", "to personalize", "S4 HANA & Fiori Benutzeroberfläche"),
    ("das Dashboard, die Dashboards", "Noun", "B2", "информационная панель", "dashboard", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Kennzahl, die Kennzahlen", "Noun", "B2", "ключевой показатель (KPI)", "key performance indicator (KPI)", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Echtzeit-Analyse, die Echtzeit-Analysen", "Noun", "B2", "аналитика в реальном времени", "real-time analytics", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Suchfunktion, die Suchfunktionen", "Noun", "B2", "функция поиска", "search function", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Enterprise-Search, (nur Sg.)", "Noun", "B2", "глобальный поиск по всей системе", "enterprise search", "S4 HANA & Fiori Benutzeroberfläche"),
    ("der Filter, die Filter", "Noun", "B1", "фильтр", "filter", "S4 HANA & Fiori Benutzeroberfläche"),
    ("filtern", "Verb", "B1", "фильтровать", "to filter", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Variante, die Varianten", "Noun", "B2", "вариант выбора (маска фильтра)", "variant", "S4 HANA & Fiori Benutzeroberfläche"),
    ("speichern", "Verb", "B1", "сохранять", "to save", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Ansicht, die Ansichten", "Noun", "B2", "ракурс / представление данных / вид", "view / layout", "S4 HANA & Fiori Benutzeroberfläche"),
    ("das Layout, die Layouts", "Noun", "B2", "формат отображения / макет", "layout", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Spalte, die Spalten", "Noun", "B2", "колонка / столбец", "column", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Zeile, die Zeilen", "Noun", "B2", "строка", "row", "S4 HANA & Fiori Benutzeroberfläche"),
    ("sortieren", "Verb", "B1", "сортировать", "to sort", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Sortierung, die Sortierungen", "Noun", "B2", "сортировка", "sorting", "S4 HANA & Fiori Benutzeroberfläche"),
    ("gruppieren", "Verb", "B2", "группировать", "to group", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Gruppierung, die Gruppierungen", "Noun", "B2", "группировка", "grouping", "S4 HANA & Fiori Benutzeroberfläche"),
    ("der Export, die Exporte", "Noun", "B2", "экспорт (выгрузка)", "export", "S4 HANA & Fiori Benutzeroberfläche"),
    ("exportieren", "Verb", "B2", "экспортировать (выгружать в файл)", "to export", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Excel-Tabelle, die Excel-Tabellen", "Noun", "B1", "таблица Excel", "Excel sheet", "S4 HANA & Fiori Benutzeroberfläche"),
    ("das SAP GUI, (nur Sg.)", "Noun", "B2", "классический интерфейс SAP GUI", "SAP GUI", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Transaktion, die Transaktionen", "Noun", "B2", "транзакция / код транзакции", "transaction", "S4 HANA & Fiori Benutzeroberfläche"),
    ("der Transaktionscode, die Transaktionscodes", "Noun", "B2", "код транзакции (T-code)", "transaction code (T-code)", "S4 HANA & Fiori Benutzeroberfläche"),
    ("das Befehlsfeld, die Befehlsfelder", "Noun", "B2", "поле ввода команд", "command field", "S4 HANA & Fiori Benutzeroberfläche"),
    ("der Report, die Reports", "Noun", "B2", "отчет / программа отчета", "report", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Selektionsmaske, die Selektionsmasken", "Noun", "B2", "экран выбора параметров", "selection screen", "S4 HANA & Fiori Benutzeroberfläche"),
    ("das Pflichtfeld, die Pflichtfelder", "Noun", "B2", "обязательное для заполнения поле", "mandatory field", "S4 HANA & Fiori Benutzeroberfläche"),
    ("das Optionsfeld, die Optionsfelder", "Noun", "B2", "радиокнопка", "radio button", "S4 HANA & Fiori Benutzeroberfläche"),
    ("das Kontrollkästchen, die Kontrollkästchen", "Noun", "B2", "флажок / чекбокс", "checkbox", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Dropdown-Liste, die Dropdown-Listen", "Noun", "B2", "выпадающий список", "dropdown list", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Wertehilfe, die Wertehilfen", "Noun", "B2", "справка по допустимым значениям (F4)", "search help (F4)", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Schnellsuche, (nur Sg.)", "Noun", "B2", "быстрый поиск", "quick search", "S4 HANA & Fiori Benutzeroberfläche"),
    ("der Favorit, die Favoriten", "Noun", "B1", "избранное", "favorite", "S4 HANA & Fiori Benutzeroberfläche"),
    ("hinzufügen", "Verb", "B1", "добавлять", "to add", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Benutzerdaten, (nur Pl.)", "Noun", "B2", "данные пользователя", "user master data", "S4 HANA & Fiori Benutzeroberfläche"),
    ("das Benutzerprofil, die Benutzerprofile", "Noun", "B2", "профиль пользователя", "user profile", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Rolle, die Rollen", "Noun", "B2", "роль (авторизации)", "role", "S4 HANA & Fiori Benutzeroberfläche"),
    ("das Berechtigungsobjekt, die Berechtigungsobjekte", "Noun", "B2", "объект полномочий", "authorization object", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Berechtigungsprüfung, die Berechtigungsprüfungen", "Noun", "B2", "проверка полномочий", "authorization check", "S4 HANA & Fiori Benutzeroberfläche"),
    ("der Berechtigungsfehler, die Berechtigungsfehler", "Noun", "B2", "ошибка полномочий / прав доступа", "authorization error", "S4 HANA & Fiori Benutzeroberfläche"),
    ("fehlen", "Verb", "B1", "не хватать / отсутствовать", "to lack / be missing", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Fehlermeldung, die Fehlermeldungen", "Noun", "B2", "сообщение об ошибке", "error message", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Warnung, die Warnungen", "Noun", "B1", "предупреждение", "warning", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Erfolgsmeldung, die Erfolgsmeldungen", "Noun", "B2", "сообщение об успешном выполнении", "success message", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Statusleiste, die Statusleisten", "Noun", "B2", "строка состояния", "status bar", "S4 HANA & Fiori Benutzeroberfläche"),
    ("das Dialogfenster, die Dialogfenster", "Noun", "B2", "диалоговое окно", "dialog box / pop-up", "S4 HANA & Fiori Benutzeroberfläche"),
    ("bestätigen", "Verb", "B1", "подтверждать", "to confirm", "S4 HANA & Fiori Benutzeroberfläche"),
    ("abbrechen", "Verb", "B1", "прерывать / отменять", "to cancel", "S4 HANA & Fiori Benutzeroberfläche"),
    ("speichern", "Verb", "B1", "сохранять", "to save / store", "S4 HANA & Fiori Benutzeroberfläche"),
    ("das Customizing-Menü, die Menüs", "Noun", "B2", "меню настройки системы", "customizing menu", "S4 HANA & Fiori Benutzeroberfläche"),
    ("das Launchpad-Design, die Designs", "Noun", "B2", "тема оформления Launchpad", "launchpad theme", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Barrierefreiheit, (nur Sg.)", "Noun", "B2", "доступность для инвалидов", "accessibility", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Web-Dynpro-App, die Web-Dynpro-Apps", "Noun", "B2", "приложение Web Dynpro", "Web Dynpro app", "S4 HANA & Fiori Benutzeroberfläche"),
    ("der App-Inhalt, die App-Inhalte", "Noun", "B2", "контент / содержимое приложения", "app content", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Kachel-Bibliothek, die Bibliotheken", "Noun", "B2", "каталог плиток", "tile catalog", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Kachel-Gruppe, die Kachel-Gruppen", "Noun", "B2", "группа плиток", "tile group", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Zielzuordnung, die Zielzuordnungen", "Noun", "B2", "сопоставление целей (target mapping)", "target mapping", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die semantische Objekt, die Objekte", "Noun", "B2", "семантический объект", "semantic object", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Aktion, die Aktionen", "Noun", "B2", "действие", "action", "S4 HANA & Fiori Benutzeroberfläche"),
    ("der Parameter, die Parameter", "Noun", "B2", "параметр", "parameter", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die URL-Adresse, die URL-Adressen", "Noun", "B1", "URL-адрес", "URL address", "S4 HANA & Fiori Benutzeroberfläche"),
    ("das Browser-Fenster, die Browser-Fenster", "Noun", "B1", "окно браузера", "browser window", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Cloud-Platform, die Cloud-Platformen", "Noun", "B2", "облачная платформа SAP BTP", "SAP Business Technology Platform (BTP)", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Schnittstelle, die Schnittstellen", "Noun", "B2", "интерфейс / шлюз", "API / interface", "S4 HANA & Fiori Benutzeroberfläche"),
    ("der Service, die Services", "Noun", "B2", "сервис / служба", "service", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die OData-Schnittstelle, die Schnittstellen", "Noun", "B2", "протокол OData (для связи с UI)", "OData service", "S4 HANA & Fiori Benutzeroberfläche"),
    ("der Gateway-Server, die Gateway-Server", "Noun", "B2", "сервер SAP Gateway", "SAP Gateway server", "S4 HANA & Fiori Benutzeroberfläche"),
    ("das Backend-System, die Backend-Systeme", "Noun", "B2", "бэкэнд-система", "backend system", "S4 HANA & Fiori Benutzeroberfläche"),
    ("das Frontend-System, die Frontend-Systeme", "Noun", "B2", "фронтэнд-система", "frontend system", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Replikation, die Replikationen", "Noun", "B2", "репликация данных", "data replication", "S4 HANA & Fiori Benutzeroberfläche"),
    ("synchronisieren", "Verb", "B2", "синхронизировать", "to synchronize", "S4 HANA & Fiori Benutzeroberfläche"),
    ("die Synchronisation, die Synchronisationen", "Noun", "B2", "синхронизация", "synchronization", "S4 HANA & Fiori Benutzeroberfläche"),

    # Category 5: SAP-Einführung & Customizing (401-500)
    ("das Customizing, (nur Sg.)", "Noun", "B2", "кастомизация / настройка системы под клиента", "customizing / configuration", "SAP-Einführung & Customizing"),
    ("der Einführungsleitfaden, (nur Sg.)", "Noun", "B2", "руководство по внедрению (IMG)", "Implementation Guide (IMG)", "SAP-Einführung & Customizing"),
    ("der Transportauftrag, die Transportaufträge", "Noun", "B2", "запрос на перенос", "transport request", "SAP-Einführung & Customizing"),
    ("die Customizing-Tabelle, die Customizing-Tabellen", "Noun", "B2", "таблица настроек", "customizing table", "SAP-Einführung & Customizing"),
    ("die Systemlandschaft, die Systemlandschaften", "Noun", "B2", "системный ландшафт", "system landscape", "SAP-Einführung & Customizing"),
    ("das Entwicklungssystem, die Entwicklungssysteme", "Noun", "B2", "система разработки (DEV)", "development system", "SAP-Einführung & Customizing"),
    ("das Qualitätssicherungssystem, die Systeme", "Noun", "B2", "тестовая система / система качества (QA)", "quality assurance system", "SAP-Einführung & Customizing"),
    ("das Produktivsystem, die Produktivsysteme", "Noun", "B2", "продуктивная / рабочая система (PRD)", "production system", "SAP-Einführung & Customizing"),
    ("der Mandant, die Mandanten", "Noun", "B2", "мандант (клиент в базе данных)", "client", "SAP-Einführung & Customizing"),
    ("die Datenübernahme, die Datenübernahmen", "Noun", "B2", "миграция / перенос данных", "data migration", "SAP-Einführung & Customizing"),
    ("die Altdatenübernahme, (nur Sg.)", "Noun", "B2", "миграция исторических данных", "legacy data transfer", "SAP-Einführung & Customizing"),
    ("die Lückenanalyse, die Lückenanalysen", "Noun", "B2", "анализ разрывов (Fit-Gap)", "fit-gap analysis", "SAP-Einführung & Customizing"),
    ("der Go-Live, die Go-Lives", "Noun", "B2", "запуск системы / промышленный старт", "Go-Live", "SAP-Einführung & Customizing"),
    ("der Support, die Supports", "Noun", "B2", "поддержка / сопровождение", "support", "SAP-Einführung & Customizing"),
    ("das SAP-Einführungsprojekt, die Projekte", "Noun", "B2", "проект внедрения SAP", "SAP implementation project", "SAP-Einführung & Customizing"),
    ("der Funktionstest, die Funktionstests", "Noun", "B2", "функциональное тестирование", "functional test", "SAP-Einführung & Customizing"),
    ("der Integrationstest, die Integrationstests", "Noun", "B2", "интеграционное тестирование", "integration test", "SAP-Einführung & Customizing"),
    ("der Benutzertest, die Benutzertests", "Noun", "B2", "пользовательское тестирование (UAT)", "user acceptance test (UAT)", "SAP-Einführung & Customizing"),
    ("die Schulung, die Schulungen", "Noun", "B1", "обучение / тренинг", "training", "SAP-Einführung & Customizing"),
    ("der Endanwender, die Endanwender", "Noun", "B2", "конечный пользователь", "end user", "SAP-Einführung & Customizing"),
    ("das Ticket-System, die Ticket-Systeme", "Noun", "B2", "система тикетов (поддержки)", "ticketing system", "SAP-Einführung & Customizing"),
    ("der Incident, die Incidents", "Noun", "B2", "инцидент / сбой / запрос на поддержку", "incident", "SAP-Einführung & Customizing"),
    ("der Änderungsantrag, die Änderungsanträge", "Noun", "B2", "запрос на изменение (CR)", "change request", "SAP-Einführung & Customizing"),
    ("die Freigabe, die Freigaben", "Noun", "B2", "выпуск / утверждение / деблокирование", "release / approval", "SAP-Einführung & Customizing"),
    ("freigeben", "Verb", "B2", "деблокировать / выпускать / утверждать", "to release / approve", "SAP-Einführung & Customizing"),
    ("importieren", "Verb", "B2", "импортировать", "to import", "SAP-Einführung & Customizing"),
    ("exportieren", "Verb", "B2", "экспортировать", "to export", "SAP-Einführung & Customizing"),
    ("die Workbench, (nur Sg.)", "Noun", "B2", "рабочая среда разработчика (Workbench)", "workbench", "SAP-Einführung & Customizing"),
    ("das Workbench-Objekt, die Workbench-Objekte", "Noun", "B2", "объект среды разработки", "workbench object", "SAP-Einführung & Customizing"),
    ("die Tabellenpflege, die Tabellenpflegen", "Noun", "B2", "ведение таблицы (настройка)", "table maintenance", "SAP-Einführung & Customizing"),
    ("die Pflegesicht, die Pflegesichten", "Noun", "B2", "ракурс ведения (таблицы)", "maintenance view", "SAP-Einführung & Customizing"),
    ("das SAP-Standard-Verhalten, (nur Sg.)", "Noun", "B2", "стандартное поведение системы SAP", "SAP standard behavior", "SAP-Einführung & Customizing"),
    ("die Modifikation, die Modifikationen", "Noun", "B2", "модификация стандарта (изменение кода)", "modification", "SAP-Einführung & Customizing"),
    ("die Erweiterung, die Erweiterungen", "Noun", "B2", "расширение (User Exit / BAdI)", "enhancement / extension", "SAP-Einführung & Customizing"),
    ("das BAdI, die BAdIs", "Noun", "B2", "технология расширения BAdI", "Business Add-In (BAdI)", "SAP-Einführung & Customizing"),
    ("der User-Exit, die User-Exits", "Noun", "B2", "пользовательский выход (точка расширения)", "user exit", "SAP-Einführung & Customizing"),
    ("die Eigenentwicklung, die Eigenentwicklungen", "Noun", "B2", "собственная разработка / Z-объекты", "custom development", "SAP-Einführung & Customizing"),
    ("das Z-Programm, die Z-Programme", "Noun", "B2", "программа Z-класса (кастомная)", "Z-program", "SAP-Einführung & Customizing"),
    ("die Z-Tabelle, die Z-Tabellen", "Noun", "B2", "кастомная таблица (Z-таблица)", "Z-table", "SAP-Einführung & Customizing"),
    ("das ABAP, (nur Sg.)", "Noun", "B2", "язык программирования ABAP", "ABAP programming language", "SAP-Einführung & Customizing"),
    ("der ABAP-Entwickler, die ABAP-Entwickler", "Noun", "B2", "разработчик ABAP", "ABAP developer", "SAP-Einführung & Customizing"),
    ("die Funktionsbeschreibung, die Funktionsbeschreibungen", "Noun", "B2", "функциональная спецификация", "functional specification", "SAP-Einführung & Customizing"),
    ("das Konzept, die Konzepte", "Noun", "B2", "концепция / проектное решение", "blueprint / concept", "SAP-Einführung & Customizing"),
    ("das Fachkonzept, die Fachkonzepte", "Noun", "B2", "бизнес-концепция / ТЗ", "business blueprint (BBP)", "SAP-Einführung & Customizing"),
    ("der Projektschritt, die Projektschritte", "Noun", "B2", "этап проекта", "project step / phase", "SAP-Einführung & Customizing"),
    ("die Projektphase, die Projektphasen", "Noun", "B2", "фаза проекта", "project phase", "SAP-Einführung & Customizing"),
    ("der Meilenstein, die Meilensteine", "Noun", "B2", "веха / контрольная точка", "milestone", "SAP-Einführung & Customizing"),
    ("der Lenkungsausschuss, die Lenkungsausschüsse", "Noun", "B2", "руководящий комитет", "steering committee", "SAP-Einführung & Customizing"),
    ("die Anforderung, die Anforderungen", "Noun", "B2", "требование / бизнес-требование", "requirement", "SAP-Einführung & Customizing"),
    ("die Anforderungserhebung, die Anforderungserhebungen", "Noun", "B2", "сбор требований", "requirements gathering", "SAP-Einführung & Customizing"),
    ("der Workshop, die Workshops", "Noun", "B1", "семинар / воркшоп", "workshop", "SAP-Einführung & Customizing"),
    ("das Protokoll, die Protokolle", "Noun", "B2", "протокол встречи", "minutes / protocol", "SAP-Einführung & Customizing"),
    ("die Aufgabe, die Aufgaben", "Noun", "B1", "задача", "task", "SAP-Einführung & Customizing"),
    ("die Zuständigkeit, die Zuständigkeiten", "Noun", "B2", "область ответственности", "responsibility", "SAP-Einführung & Customizing"),
    ("zuständig", "Adjective", "B2", "ответственный (за задачу)", "responsible", "SAP-Einführung & Customizing"),
    ("der Key-User, die Key-User", "Noun", "B2", "ключевой пользователь", "key user", "SAP-Einführung & Customizing"),
    ("das Testdrehbuch, die Testdrehbücher", "Noun", "B2", "сценарий тестирования", "test script / scenario", "SAP-Einführung & Customizing"),
    ("der Testfall, die Testfälle", "Noun", "B2", "тест-кейс / тестовый случай", "test case", "SAP-Einführung & Customizing"),
    ("der Fehler, die Fehler", "Noun", "B1", "ошибка / дефект", "error / bug", "SAP-Einführung & Customizing"),
    ("beheben", "Verb", "B2", "исправлять (ошибку)", "to resolve / fix (bug)", "SAP-Einführung & Customizing"),
    ("die Fehlerbehebung, die Fehlerbehebungen", "Noun", "B2", "исправление ошибок", "bug fixing", "SAP-Einführung & Customizing"),
    ("das Testprotokoll, die Testprotokolle", "Noun", "B2", "протокол тестирования", "test log / report", "SAP-Einführung & Customizing"),
    ("die Abnahme, die Abnahmen", "Noun", "B2", "приемка / утверждение", "acceptance / sign-off", "SAP-Einführung & Customizing"),
    ("abnehmen", "Verb", "B2", "принимать (работу/систему)", "to sign off / accept", "SAP-Einführung & Customizing"),
    ("das Abnahmeprotokoll, die Abnahmeprotokolle", "Noun", "B2", "акт приемки-передачи", "sign-off document", "SAP-Einführung & Customizing"),
    ("der Produktivstart, (nur Sg.)", "Noun", "B2", "продуктивный старт", "Go-Live", "SAP-Einführung & Customizing"),
    ("die Hypercare-Phase, die Hypercare-Phasen", "Noun", "B2", "период усиленной поддержки после старта", "hypercare phase", "SAP-Einführung & Customizing"),
    ("der Regelbetrieb, (nur Sg.)", "Noun", "B2", "регулярная эксплуатация системы", "normal operations / run", "SAP-Einführung & Customizing"),
    ("das Ticket-Volumen, (nur Sg.)", "Noun", "B2", "объем поступающих заявок", "ticket volume", "SAP-Einführung & Customizing"),
    ("die Bearbeitungszeit, die Bearbeitungszeiten", "Noun", "B2", "время обработки (тикета)", "processing time", "SAP-Einführung & Customizing"),
    ("das Service Level Agreement (SLA), (nur Sg.)", "Noun", "B2", "соглашение об уровне услуг (SLA)", "Service Level Agreement (SLA)", "SAP-Einführung & Customizing"),
    ("die Eskalation, die Eskalationen", "Noun", "B2", "эскалация проблемы", "escalation", "SAP-Einführung & Customizing"),
    ("eskalieren", "Verb", "B2", "эскалировать", "to escalate", "SAP-Einführung & Customizing"),
    ("die Bereinigung, die Bereinigungen", "Noun", "B2", "очистка / выверка (данных)", "cleansing / cleanup", "SAP-Einführung & Customizing"),
    ("die Datenbereinigung, (nur Sg.)", "Noun", "B2", "очистка данных", "data cleansing", "SAP-Einführung & Customizing"),
    ("die Schnittstellenabstimmung, die Abstimmungen", "Noun", "B2", "согласование интерфейсов", "interface reconciliation", "SAP-Einführung & Customizing"),
    ("das Migrationswerkzeug, die Migrationswerkzeuge", "Noun", "B2", "инструмент миграции (например, LSMW, LTMC)", "migration tool", "SAP-Einführung & Customizing"),
    ("das LTMC (Legacy Transfer Migration Cockpit), (nur Sg.)", "Noun", "B2", "миграционный кокпит (LTMC)", "Migration Cockpit", "SAP-Einführung & Customizing"),
    ("die Datenstruktur, die Datenstrukturen", "Noun", "B2", "структура данных", "data structure", "SAP-Einführung & Customizing"),
    ("die Mapping-Regel, die Mapping-Regeln", "Noun", "B2", "правило сопоставления данных", "mapping rule", "SAP-Einführung & Customizing"),
    ("das Quellfeld, die Quellfelder", "Noun", "B2", "исходное поле", "source field", "SAP-Einführung & Customizing"),
    ("das Zielfeld, die Zielfelder", "Noun", "B2", "целевое поле", "target field", "SAP-Einführung & Customizing"),
    ("die Konvertierungsregel, die Konvertierungsregeln", "Noun", "B2", "правило конвертации", "conversion rule", "SAP-Einführung & Customizing"),
    ("das Testsystem, die Testsysteme", "Noun", "B2", "тестовая система", "test system", "SAP-Einführung & Customizing"),
    ("das Sandbox-System, die Sandbox-Systeme", "Noun", "B2", "песочница (изолированная тестовая система)", "sandbox system", "SAP-Einführung & Customizing"),
    ("das Release-Upgrade, die Release-Upgrades", "Noun", "B2", "обновление версии системы", "release upgrade", "SAP-Einführung & Customizing"),
    ("das Support Package, die Support Packages", "Noun", "B2", "пакет поддержки (обновлений)", "Support Package", "SAP-Einführung & Customizing"),
    ("der SAP-Hinweis, die SAP-Hinweise", "Noun", "B2", "нота SAP (исправление бага)", "SAP Note", "SAP-Einführung & Customizing"),
    ("einspielen", "Verb", "B2", "устанавливать / применять (ноту/патч)", "to apply / implement (note/patch)", "SAP-Einführung & Customizing"),
    ("der Hotfix, die Hotfixes", "Noun", "B2", "срочное исправление", "hotfix", "SAP-Einführung & Customizing"),
    ("die Systemaktualisierung, die Systemaktualisierungen", "Noun", "B2", "обновление системы", "system update", "SAP-Einführung & Customizing"),
    ("die Datensicherung, die Datensicherungen", "Noun", "B2", "резервное копирование данных", "data backup", "SAP-Einführung & Customizing"),
    ("das Backup, die Backups", "Noun", "B2", "резервная копия", "backup", "SAP-Einführung & Customizing"),
    ("wiederherstellen", "Verb", "B2", "восстанавливать (из бэкапа)", "to restore", "SAP-Einführung & Customizing"),
    ("der Systemausfall, die Systemausfälle", "Noun", "B2", "сбой / простой системы", "system outage / downtime", "SAP-Einführung & Customizing"),
    ("die Ausfallzeit, die Ausfallzeiten", "Noun", "B2", "время простоя", "downtime", "SAP-Einführung & Customizing"),
    ("die Wiederherstellungszeit, (nur Sg.)", "Noun", "B2", "время восстановления (RTO)", "recovery time", "SAP-Einführung & Customizing"),
    ("die Katastrophenfall-Vorsorge, (nur Sg.)", "Noun", "B2", "планирование аварийного восстановления", "disaster recovery planning", "SAP-Einführung & Customizing"),
    ("der Datenverlust, die Datenverluste", "Noun", "B2", "потеря данных", "data loss", "SAP-Einführung & Customizing"),
    ("das Berechtigungskonzept, die Berechtigungskonzepte", "Noun", "B2", "концепция полномочий (прав доступа)", "authorization concept", "SAP-Einführung & Customizing")
]
